### ISSUE TITLE
subrepo push fails when changing added file

### ISSUE THREAD

**Issue by martinKupec** [ingydotnet/git-subrepo#104]
When I change file of subrepository which was added in the previous commit the "subrepo push" fails in rebase phase.

Here is simple test case:
```
set -ex

rm -fr repo{1,2,3}
mkdir repo{1,2}
(
  cd repo1/
  git init
  git config receive.denyCurrentBranch ignore
  echo "First commit" >> foo
  git add foo
  git commit -m "First commit"
)
(
  cd repo2
  git init
  git config receive.denyCurrentBranch ignore
  echo "add bar" >> bar
  git add bar
  git commit -m "add bar"
)
git clone repo1 repo3
(
  cd repo3/
  git subrepo clone ../repo2 subrepo
  git subrepo pull subrepo
  echo "update bar" >> subrepo/bar
  git commit -a -m "bar update"
  git push
  git subrepo push subrepo
)
```

**Comment by grimmySwe** [comment]
What version are you running? Could you please test branch issue/98 and see
if this problem still exist there?

söndag 29 november 2015 skrev Martin Kupec <notifications@github.com>:

**Comment by martinKupec** [comment]
I was using master branch.
The problem is solved in branch issue/98.

Thank you
