### ISSUE TITLE
The creator of git-stree reached with the queries...

### ISSUE THREAD

**Issue by ingydotnet** [ingydotnet/git-subrepo#116]
Christophe Porteneuve, the creator of
https://github.com/deliciousinsights/git-stree emailed me to consider joining
forces with subrepo.

I'll paste his email here and link to individual issues for his outstanding
questions/concerns.

----

Hey @ingydotnet as I finally can spare some time to look at git-stree again and
decide whether to do a complete rewrite (which I was about to do) or whether to
call it a day and encourage people to use git-subrepo, I looked more in-depth
into git-subrepo usage.

Generally, this is way more advanced than stree. I like the level of UI/UX
(smart outputs, smart storage, proper docs and man page, proper tests, good
dual-shell completion…). However, before I decide whether to stop my own
efforts, there are a couple things I worry about. Would you care to spend a
moment answering these questions? I'd appreciate it.

#119 Apparently it doesn't work yet in Git for Windows's Git Bash. It's been updated
recently to a much more recent Bash and Git. Is that scheduled soon?

1) #117 I don't see any way to push only selected local work back upstream. I get that request many times, and this is one of the core tenets of stree. What about subrepo?
2) #118 The README speaks of various things nowhere to be found: the …/upstream ref mentioned everywhere is apparently …/fetch now, and the git subrepo upgrade feature doesn't seem to exist. What gives?
3) These are my main concerns. Everything else looks dandy, I must say.

Thank you for your time,

**Comment by ingydotnet** [comment]
Just realized the email was from https://github.com/deliciousinsights/git-stree/issues/20

Need more coffee.

**Comment by grimmySwe** [comment]
@ingydotnet  @tdd I added comment on #117, please let me know what you think.

**Comment by tdd** [comment]
Hey Magnus, don't worry, I subscribed to all the relevant issues and get notified :grin:


On Tue, Jan 5, 2016, at 09:15, Magnus Karlsson wrote:
> @ingydotnet[1] @tdd[2] I added comment on #117[3], please let me know
> what you think.


> — Reply to this email directly or view it on GitHub[4].


>

--
Christophe Porteneuve
tdd@tddsworld.com
 


Links:

  1. https://github.com/ingydotnet
  2. https://github.com/tdd
  3. https://github.com/ingydotnet/git-subrepo/issues/117
  4. https://github.com/ingydotnet/git-subrepo/issues/116#issuecomment-168931757

**Comment by grimmySwe** [comment]
Closing this as all things described here are handled in other issues.
