### ISSUE TITLE
Add a 'diff' subcommand:

### ISSUE THREAD

**Issue by ingydotnet** [ingydotnet/git-subrepo#129]
The command:

    git subrepo diff ext/bashplus

Should:

* Check if there is already a subrepo branch for `ext/bashplus`
  * Create one if not: `git subrepo branch ext/bashplus`
* If neither `ext/bashplus/.gitrepo`s 'commit' or refs/subrepo/ext/bashplus/fetch exists
  * `git subrepo fetch ext/bashplus`
  * Maybe throw error telling user to fetch first (instead)
* `git diff refs/subrepo/ext/bashplus/fetch subrepo/ext/bashplus`
* Remove any created refs or branches

Also the `-F` flag should force a fetch, `-f` should force a branch, and `-r`,
`-b`, `-a` should DTRTs.

I want the command to honor the current state and not overwrite branches or do
a fetch by default. It should work offline by default.

Thoughts? Takers?

See #32

**Comment by grimmySwe** [comment]
I like your suggestion, regarding DTRT I would say that -a should give an error as having multiple diffs seems a little complex. -r/-b should probably work as redirecting the fetch target.

**Comment by ingydotnet** [comment]
@grimmySwe,

OK on the `-a` for starters. If we can figure out a nice way to display it, it
might be good, since often times you'll want to know which local changes (if
any) apply to my subrepos.

Not sure what you mean by `-r/-b`.

Hopefully you mean that they will just be passed on to the internal fetch
command. The branch command supports neither.

**Comment by grimmySwe** [comment]
> Not sure what you mean by -r/-b.

> Hopefully you mean that they will just be passed on to the internal fetch
> command. The branch command supports neither.

Thats exactly what I meant. -r/-b is fetch only.

A second thought on this is that people might be interested in using additional arguments to the diff (like --summary/--patch), should we support that or simply say that if you want more advanced functionality you should do the steps yourself? 

Or should we skip the `git subrepo diff` and instead supply a new argument to `git subrepo pull` that performs everything except the last step? So if you want to diff you will actually do `git subrepo pull --no-commit <subrepo>`and then `git diff <subrepo_branch> <subrepo_fetch_ref>`

**Comment by ingydotnet** [comment]
Yeah I forgot to add that sometimes I will want to see my diff from the
upstream PoV and sometimes from the local PoV (reversed).

I think this `subrepo` diff is probably not needed. People should just `git
diff A..B` and we should make it easy to make and discover A-s and B-s.

Diff is just one example. Log is another. Git is all about commits. Replicating
Git tools is the wrong approach.

That said, a right thing to do is write documentation about how to diff and how
to log.

I feel a "git-subrepo Tutorial" issue coming on. :-)

**Comment by ingydotnet** [comment]
Closing this in favor of #131 (tutorial)
