### ISSUE TITLE
Support `--all` for status command.

### ISSUE THREAD

**Issue by ingydotnet** [ingydotnet/git-subrepo#132]
This will show all the nested subrepos in addition to the top level ones.

See #82

**Comment by stsquared99** [comment]
Should this really be an '--all' flag? It would be inconsistent with the function of push --all or fetch --all, for example. Unless we also modify those commands to work for all nested subrepos as well, but I'm not sure we want that. Perhaps a --recursive flag?

**Comment by ingydotnet** [comment]
@stsquared99 I realize this, but: https://github.com/ingydotnet/git-subrepo/issues/82#issuecomment-175363231

For better or worse, I've set things up so that all the commands share the same options. We don't have any options that only apply to a single command. I'm ok with 'all' meaning something different for status, show and clean.

**Comment by ingydotnet** [comment]
@stsquared99 I had a think on this, and you are probably right. We should have consistency for `--all`.

I'd like to propose a `--ALL` (`-A`) flag for subsubrepos. This can be applied to the `status`, `show` and `clean` commands at a minimum.

I'll go ahead and add it for `clean` and then you can use it for `status` and `show`?

FWIW, `--all` should still be the default for `status` and `show`.

**Comment by stsquared99** [comment]
Hmm, I see. I think that works fairly nicely. I'll resend my latest pull when you have that added in.
Should we try to add -A to the rest of the commands as well?

**Comment by ingydotnet** [comment]
I'd rather not, until there is a real need for it. People can always do the other commands explicitly per subsubrepo.

**Comment by ingydotnet** [comment]
Pushed `--ALL` support to branch `issue/132b`. Please test out. Need to doc it, and make a test for it.

**Comment by stsquared99** [comment]
Thanks, that logic looks much better than what I originally was going to do

**Comment by ingydotnet** [comment]
Done. Closing.
