### ISSUE TITLE
Can't find common ancestor on every pull

### ISSUE THREAD

**Issue by blucz** [ingydotnet/git-subrepo#133]
I'm new to git-subrepo, so I could be doing something wrong. I am getting a "can't find a common ancestor" error each time I try to pull my subrepo.

I tried re-cloning the repository as it suggested, and the next time I attempted to pull the same thing happened.

Synopsis of what I'm doing:

```
$ git --version
git version 2.3.2 (Apple Git-55)

$ git subrepo --version                                                                                                              
0.3.0

Setting up the parent repository:

$ cd /path/to/parent_repo
$ git checkout parentrepo_branch_that_is_not_master          
$ git subrepo clone git@github.com:XXX/subdir.git subdir -b subrepo_branch_that_is_not_master

Adding a commit to the sub-repository:

$ cd /path/to/local/checkout/of/subdir.git
$ git checkout my_branch
$ touch foo 
$ git add foo
$ git commit -m 'foo' foo
... creates a commit ...
$ git push
... successful push to my_branch on git@github.com:XXX/subdir.git ...

Now, back to the parent repository to pull:

$ cd /path/to/parent_repo
$ git subrepo pull subdir
git-subrepo: Can't find a common ancestor between refs/subrepo/subdir/fetch and subrepo/subdir. This might be the case if someone used push --force on the subrepo. You need to find out why and possibly reclone the subrepo.
```

I completely control both repositories. There have been no intervening commits or any --force usage. The history looks right on the common ancestor is clearly visible in 'git log' on the subrepo branch.

I'm confused as to why this is happening. Any ideas?

**Comment by ingydotnet** [comment]
@blucz, thanks for this report.

I took what you've said and created this runnable script. It leaves things in a
state so that I can run it over and over and expect the same results:

https://gist.github.com/6e36636636ca98ea399c

Here is the output from a run:

https://gist.github.com/44c23e6e644f1a5195f4

As you can see, it works like one would expect. Can you find out what is
different about your situation? You should be able to fork both repos and
change the script to use your forks.

@grimmySwe, any thoughts?

**Comment by grimmySwe** [comment]
@blucz  @ingydotnet We had an issue (#122) with subrepo command having trouble with empty commits in the subrepo. When we try to find ancestors we ignore all duplicates and if you perform operations on a subrepo where you happen to find similar commits it might fail.
There is a solution for some of the cases in #122 and that is merged to master.

For better debugging you can perform the `git subrepo merge-base --all` command to list all the possible candidates. If you do the steps below it will inform you on the ancestry:
```
git subrepo fetch my_subrepo      # Fetch the subrepo and create a reference refs/my_subrepo/fetch
git subrepo branch my_subrepo   # Create local branch with your my_subrepo related changes
git subrepo merge-base --all refs/my_subrepo/fetch subrepo/my_subrepo    # List ancestry
```

**Comment by blucz** [comment]
Thanks for the help and responsiveness. 

I ran the script (modified to use my repositories) and found that it worked on a fresh clone of the parent repository, but not on my pre-existing well-used working tree.

Then I started debugging. Then after a while I found the problem. It's pretty messy...

I had two problems:

- My parent repository has a generated (meaning: un-tracked) file called 'Makefile' and the sub-repository has a checked-in file called 'Makefile'. This causes one of the git filter-branch commands to blow up when creating the subrepo/foo branch
- My repository has hooks (post-checkout, post-merge, pre-commit) that are OK when executed on the working tree from the parent repository, but which fail when run against the working tree from the sub-repository. One of the intermediate states during the pull puts the working tree into a state that causes the hooks to fail.

I can work around both of these:

- rm the generated Makefiles before pulling the branch.
- make my git-subrepo export IS_GIT_SUBREPO=1, which the hooks can respect by exiting gracefully

IMO, the worst problem here is an error message that has nothing to do with the actual problem. Once I started reading the git-subrepo code and running the commands by hand one by one, I started getting useful feedback from git about these failures.

**Comment by ingydotnet** [comment]
@blucz, thanks for the follow up.

I can easily reproduce your issue with this adaptation:
https://gist.github.com/f8b9f09a5617ae942050

Here is the diff from the original: https://gist.github.com/c2e462416c6149dcda0a

I just touch an untracked file that collides with the subrepo.

Here's the output of the run: https://gist.github.com/2950df2c7e2e9d6c4cb3

I will create a new issue for this problem. I suspect there is an easy fix.

----

I hadn't thought about hook interaction. I will also create an issue for that.

I like your simple solution. Can you push your fork of git-subrepo?

**Comment by ingydotnet** [comment]
Closing. Moved to #134 and #135
