### ISSUE TITLE
Ready for beta release?

### ISSUE THREAD

**Issue by aktau** [ingydotnet/git-subrepo#14]
As someone who is tired of the submodules/subtree shenanigans, and eager to see an easier way to install this and get this to a wider audience, could there be a formal beta release?

I'm asking because that seems to be a requirement for getting it into mac homebrew: https://github.com/Homebrew/homebrew/issues/27484

**Comment by ingydotnet** [comment]
I just finished a multi-week push to get this all working great. The new code
is on the `remix` branch. After I get a bit of review over the next days, I
will merge to master, and fully support this going Beta!

Let me know if you are still interested.

**Comment by aktau** [comment]
I am still interested of course, but currently shorter on time than I've ever been (new job, new country, ...) :). I'll be happy to investigate when I get some more of that precious quantity in the future. I'm happy to hear it's making progress though.

**Comment by ingydotnet** [comment]
@aktau cool. I'll keep you posted and think about if there is anything I can do
to help on your side.

**Comment by ingydotnet** [comment]
Using a mac now. Closing this issue as this command:

    brew install git-subrepo

installs the latest tagged version for me. \o/

**Comment by AlJohri** [comment]
@ingydotnet would you consider adding `brew install git-subrepo` to the `README.md` under Installation Instructions?
