### ISSUE TITLE
Is there a way to pull subrepo tags into the parent repo?

### ISSUE THREAD

**Issue by robe070** [ingydotnet/git-subrepo#146]

**Comment by grimmySwe** [comment]
The subrepo is first fetched into a local subrepo/subdir/fetch branch, then all the new commits from subrepo is squashed into a parent repo commit and commited in the parent repo.

I don't see the use case here, could you please elaborate?

**Comment by robe070** [comment]
My bad. I actually don't want the commits to be squashed in the Parent repo for the first pull, which of course is not a choice. Only thereafter does squash make sense for us. And if they are not squashed I'd like the tags too.

I've re-architected our work procedures to accommodate it.

**Comment by grimmySwe** [comment]
So what you wanted is a `git subrepo clone --no-squash`? And maybe a `git subrepo pull --no-squash` later on?

**Comment by robe070** [comment]
@grimmySwe 
> So what you wanted is a git subrepo clone --no-squash? And maybe a git subrepo pull --no-squash later on

Thats correct. Our situation is we have a very old non-git repo which has been converted to git. So all the old releases have tags attached to various commits. The non-git repo had to be split into more than one git repo, hence the need for subrepo. So in order to build old releases we would need all the commits and their tags. Going forward, we will not require every commit as we would pull from the subrepo as required to build a release and the squashed commit would be tagged. But we may want to keep the history intact even then too.

Is not a show stopper at all. We can work directly with the subrepos in the build enviornment.

**Comment by ingydotnet** [comment]
I think the appropriate workflow here is:

* Convert the non-git repo (X) and keep it as a an addressable git repo.
* In your "super" repo:
  * Make a branch for each build
  * `subrepo clone` the appropriate tag from X

Remember, subrepo only ties a single commit from an external repo to a single
subdir of your repo, on a single branch of your repo. Every branch can be
different than the others.

**Comment by robe070** [comment]
​Thats an interesting idea. Sounds like it will work better than my
in-progress ideas.​

**Comment by camlafit** [comment]
Hi

I'm not sure if I may follow this thread or open an another, my apologies if I've wrong.

I'm interesting to get in subrepo at a specific tag. We develop some extensions from an external projectn, idea is to get a freezed external project, as branch can be move in the time, looks better to follow a specific tag.

In mine idea looks as this : 
our_project (global container)/
 |--  /external_project - subrepo tagged -
         |-- {extensions|plugins|themes}/
               |-- first_extension - our remote project -
               |-- tuple_extension - our remote project -
           
Looks possible ? I'm in wrong way.

Thanks a lot

**Comment by grimmySwe** [comment]
As @ingydotnet said above:
> Remember, subrepo only ties a single commit from an external repo to a single
subdir of your repo, on a single branch of your repo. Every branch can be
different than the others.

So if I understand you correctly you should be able to have the external_project as a subrepo at a specifc tag in  you repo.

Closing this as the questions raised have been answered.

**Comment by camlafit** [comment]
Hi

Ok as we can tie only commit, follow tag or branche is same. 
Maybe could be nice to have an improvement allowing tag link as :
`git subrepo clone <repository> [<subdir>] [-b <upstream-branch>] [-t <upstream-tag>] [-f]`

Thanks
