### ISSUE TITLE
"git subrepo pull" on a rebased branch sees all new changes on subrepo as collisions

### ISSUE THREAD

**Issue by kentfredric** [ingydotnet/git-subrepo#15]
There's a lengthy example of replicating this here: https://gist.github.com/kentfredric/6e06db0933e27e414e93#file-gistfile1-txt

But the gist of it is this:

```
| - A
| - B 
| - C
| - Subrepo clone (D)
| - E
```
When rebased becomes

```
| - A
| - B+C (B')
| - Subrepo clone (D')
| - E'
```

On an unrebased branch you'd expect to see:
```
| - A
| - B 
| - C
| - Subrepo clone (D)
| - E
| - Subrepo pull  (F)
```

However, the rebased one is different, and for some reason the "Pull" sees the changes between D and F as collisions 

I'm not sure what's going on, I don't seem to be able to rig any values to trick it into working :/

**Comment by AndrewSmart** [comment]
I put together this non-interactive test for this: https://gist.github.com/AndrewSmart/5ef45b3cebfc8e4540ab

**Comment by ingydotnet** [comment]
Can we get a set of actual commands that reproduce this? We could then add it
as a test.

It is pretty easy to use existing repos to create these reproductions. Nothing
is permanent until you push to a master (ususally), and most of the commands
take tags and  arbitrary commits as branches.

Please use the new subrepo code on the remix branch until I merge to master.
FWIW, the checkout command is gone. I suspect this bug might no longer be a
problem.

**Comment by grimmySwe** [comment]
Closing this old issue, if someone disagrees please open again (please check with latest master)
