### ISSUE TITLE
Commits in local after subrepo push

### ISSUE THREAD

**Issue by shlomiassaf** [ingydotnet/git-subrepo#153]
Hi,

I'm sure this is me not understanding the flow but I will appreciate any help.

I have 2 remote repo's, lets call them **master** and **plugin**
**plugin** is a subrepo in **master**.

After adding the subrepo I have 1 clean commit, cool!
I start making changes in **plugin** and commit them using `git commit -m "something"`.
I then push using `git subrepo push plugin`
All the data is in the remote repository of the external module, cool!

What I don't understand is the local commits I now have in my local **master**.
If for example 2 commits were made and then pushed my local repo history will show them and the HEAD will now point to the last commit of that 2.

I was sure that all of these commits will be squashed (on local **master**) into 1 single commit (like `git subrepo pull` does). 
The history is saved in the remote **plugin** repository anyway so why is it needed in the **master**?

Thanks!

**Comment by grimmySwe** [comment]
If I understand correctly your expected workflow would be that when you push stuff to the **plugin** repository these commits would be squashed in your local **master** as well?

To accomplish this we would be forced to rewrite the tree and commits in the local **master** and that would cause a lot of trouble. Performing these kind of operations would almost certain end up in  `git push --force` and your other repo users will not like that. So everything that you do on your own **master** will be left intact, when you pull in new changes from the **plugin**, these changes will be squashed.

Does that answer your question?

**Comment by shlomiassaf** [comment]
@grimmySwe, thank you for the prompt answer.

I understand the issue.

Enough that a commit involves different repositories to make it hell.

But, if to say, all commits are unique to the submodule being pushed (**plugin**) and the **master** wasn't pushed to a repo, meaning the head of the remote points to a point before these commits, then we can squash, theoretically speaking, right?

This is a workflow one can adopt... 

It might be tricky, but that from the top of my head, the process can be a little bit different and more friendly.

**Comment by robe070** [comment]
Personally, I like that the repo making the original change records the
details of the change.  This is the team that's making the changes. All the
commit messages they leave in should be relevant to that team.

And of course the details are recorded in the subrepo for posterity. And
any repo subscribing to the subrepo just gets a one-line summary, cos they
are not interested in any details. Or if they are, they can clone the
subrepo directly to see those.

Its all good in my mind. Makes sense.

warm regards

Rob Goodridge

**Comment by grimmySwe** [comment]
@shlomiassaf I believe that you will quickly end up in a mess if you try to squash things in you master repo. As commits can span both the plugin and non-plugin content you don't know how to handle them. Because you absolutely don't want to mess with things that are pushed. 

You are free to prove me wrong, create your own fork and make an attempt!

You can though accomplish something similar to this if you use separate branches when you develop new changes. Instead of merging branches you simply push to the plugin subrepo and then go back to master and pull in the changes from the subrepo. That way you will have the complete history on the feature branch but on you master you will only have the squashed history.

But unless you come up with a use case and some good thoughts on how to actually make it happen it will not be in the git-subrepo roadmap.

**Comment by grimmySwe** [comment]
@shlomiassaf I have been sketching on a version that actually squashes both ways #142, it will still not change anything in you current repo.

**Comment by shlomiassaf** [comment]
@grimmySwe Don't get me wrong, It is not something for the faint of heart.
It is risky and thats an understatement.

You'r first comment was enough for me to understand that.

After saying that, I think its doable but frankly doesn't worth the time...

**Comment by grimmySwe** [comment]
@shlomiassaf I am always open for new ideas and suggestions so I find these discussions very good. And it seems that we agree that this suggestion is not worth the effort.
