### ISSUE TITLE
Does the order of merging in subrepo creation points matter?

### ISSUE THREAD

**Issue by robe070** [ingydotnet/git-subrepo#154]
I have a `trunk` branch which is the `develop` equivalent in the git-flow paradigm. Its a mirror of a Vault (not git) repo. Development is ongoing in Vault repo. I create a new branch off `trunk` to add in git-specific features - `feature/gitignore`. I added in .gitignore files and also replaced duplicated sub-directories with `subrepo` in this branch.

Note that `trunk` has the subrepo as a normal sub-directory. `feature/gitignore` has changed it to a subrepo. 

`trunk` had progressed - continually mirrored from Vault to git. Some 100 commits ahead of `feature/gitignore`. Busy bees here :smile: . But no commits make changes to sub-directory in `trunk`.

The subrepo had one new commit -.gitignore had been added. Its a slow moving subrepo.

I stopped the mirroring and merged `feature/gitignore` into `trunk`. 

I then executed a `subrepo pull` and `subrepo push`. The push failed as follows

```
$ git subrepo push X_WIN95/X_LANSA/x_apps/SAMPLES --debug
>>> git rev-parse --verify HEAD
>>> git fetch --quiet lansagit@gitsrv:/home/git-repo/vl_samples.git trunk
>>> git rev-parse FETCH_HEAD^0
fatal: ambiguous argument 'FETCH_HEAD^0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: FETCH_HEAD^0: not a valid SHA1
```

[full session here](https://gist.github.com/robe070/be085fa39c4ccef5e403)

I restored back to pre-merge state.

This time I merged `trunk` into `feature/branch`. I then executed a `subrepo pull` and `subrepo push`. **It worked**.

So, is it actually an important procedural point that once subrepo commands have been executed in a branch, you must merge into that branch?

**Comment by grimmySwe** [comment]
Strange, I can't really say whats happened there. The fetch seems to work, otherwise it would have stopped there. What happens if you run these steps manually?
```
>>> git fetch --quiet lansagit@gitsrv:/home/git-repo/vl_samples.git trunk
>>> git rev-parse FETCH_HEAD^0
```

Note: you can add a -v flag to subrepo as well for even more output, --debug will output the git commands but -v will output internal information as well.

**Comment by grimmySwe** [comment]
@robe070 closing this as there are no more information to work with. Please reopen if you have something new.
