### ISSUE TITLE
Can't find a common ancestor after switching branches in subrepo

### ISSUE THREAD

**Issue by robe070** [ingydotnet/git-subrepo#155]
I'm using this commit 9f2ab8779
Here is an image of the final state of the branches in the subrepo and an annotation where the branch `origin/feature/gitignore` was before moving it to the same commit as `trunk`:
![screenclip](https://cloud.githubusercontent.com/assets/4089160/13484265/5d4b4788-e150-11e5-99a9-4d53cf7e718d.png)
The full bash session is here: https://gist.github.com/robe070/6332bc749a267c3c5a57
The first command was to pull from the `trunk` branch and update .gitsubrepo to use that branch.
`git subrepo pull LANSA/Imports/DeveloperPack -b trunk -u`
but it failed with `can't find a common ancestor`.
So I tried the current subrepo branch `feature/gitignore` (in the original location) and it reported it was up to date, as expected:
` git subrepo pull LANSA/Imports/DeveloperPack`
I then moved the branch to the same commit as `trunk` (current state in image), and it also failed with `can't find a common ancestor`.

Why can't it find the common ancestor?

**Comment by robe070** [comment]
Does this message get displayed when there is a conflict?

**Comment by grimmySwe** [comment]
Even though you have written a good report and supplied a lot of information it's really hard to determine why it can't find an ancestor without access to the repo.

You can though try out the pull steps for yourself and see whats happening. If you start with performing a ```subrepo fetch -b trunk <subdir>``` and then a ```subrepo branch <subdir>``` you will have the to states that pull creates. Then you can run ```subrepo merge-base subrepo/<subdir>/fetch subrepo/<subdir> --all``` to get some better output of the actual commits involved.

Current implementation have a problem when a tree has occurs multiple times on  branch, then it can't decide which one to use and ignores it. So it might be something like that that triggers this.

**Comment by grimmySwe** [comment]
I am here ready to help you.

**Comment by robe070** [comment]
Well, case is correct. And no enlightenment from merge-base:
```
robert@RobertPC /c/dev/Trunk/work trunk $ time git subrepo merge-base subrepo/LANSA/Imports/Developerpack/fetch subrepo/LANSA/Imports/Developerpack --all --debug --verbose
>>> git rev-parse --verify HEAD
* source1 side: 36 commits
* target1 side: 1 commits
Multiple on subrepo/LANSA/Imports/Developerpack/fetch: a0269a0539d940ad5ee3bbd5b0c581d94e373f18_4b1f0b34ca32dbdd87f849b4c3950b6c16a1f415
Multiple on subrepo/LANSA/Imports/Developerpack/fetch: a0269a0539d940ad5ee3bbd5b0c581d94e373f18_4b1f0b34ca32dbdd87f849b4c3950b6c16a1f415
Multiple on subrepo/LANSA/Imports/Developerpack/fetch: 45bffeafc019482a8bb196d336d67c2d6729a3e3_ff611bca602381020b87d9d62a6032aa21532a06
Multiple on subrepo/LANSA/Imports/Developerpack/fetch: c0e9a4fba91baa7ac12826642982dbc1a842bac3_c3a51f62c21b564df756d472f4197acb5a024a98
Multiple on subrepo/LANSA/Imports/Developerpack/fetch: 45bffeafc019482a8bb196d336d67c2d6729a3e3_ff611bca602381020b87d9d62a6032aa21532a06
Multiple on subrepo/LANSA/Imports/Developerpack/fetch: c0e9a4fba91baa7ac12826642982dbc1a842bac3_c3a51f62c21b564df756d472f4197acb5a024a98
* No ancestor found
```

**Comment by grimmySwe** [comment]
what if you do ```git log subrepo/LANSA/Imports/Developerpack --oneline``` Is that the clone commit?

**Comment by robe070** [comment]
Correct. (I'd already done that)

**Comment by robe070** [comment]
```
robert@RobertPC /c/dev/Trunk/work trunk $ git log subrepo/LANSA/Imports/DeveloperPack --oneline
dc015b3 git subrepo clone --branch=feature/gitignore lansagit@gitsrv:/home/git-repo/vl_demodev.git LANSA/Imports/DeveloperPack
```

**Comment by grimmySwe** [comment]
In the .gitrepo file there should be reference called commit. Does that hash exist in the subrepo/.../fetch?

**Comment by robe070** [comment]
yes it does exist:
```
robert@RobertPC /c/dev/Trunk/work trunk $ cat LANSA/Imports/DeveloperPack/.gitrepo
[subrepo]
        remote = lansagit@gitsrv:/home/git-repo/vl_demodev.git
        branch = feature/gitignore
        commit = 4b1f0b34ca32dbdd87f849b4c3950b6c16a1f415
        parent = 73a9de94154b768c5a3c048904cdc2dbf5b861fd
        cmdver = 0.3.0
robert@RobertPC /c/dev/Trunk/work trunk $ git log subrepo/LANSA/Imports/DeveloperPack/fetch --oneline
a0269a0 Merge branch 'feature/gitignore' into trunk
8682b3d include executables in all demo directories
4b1f0b3 Just include the directories in vl_demo repo

```

**Comment by grimmySwe** [comment]
From the merge-base output above it looks like the tree hashes of 
a0269a0539d940ad5ee3bbd5b0c581d94e373f18_4b1f0b34ca32dbdd87f849b4c3950b6c16a1f415
are the same.
So then git-subrepo can't decide which one to use.

**Comment by grimmySwe** [comment]
I guess that the content merged in a0269a0 was actually something that didn't change the actual tree.

**Comment by grimmySwe** [comment]
What is ```git diff 8682b3d a0269a0```

**Comment by robe070** [comment]
`git diff 4b1f0b3 a0269a0` yields no differences. So thats the issue. No change so it declares no common ancestor. Rather confusing

**Comment by grimmySwe** [comment]
I agree with you, it's not that obvious. And that's one of the reasons that I looked into another design to avoid these strange cases.

I will close this issue as it works as expected (although confusing)
