### ISSUE TITLE
Simple subrepo push and pull between two parent repos fails with can't find a common ancestor

### ISSUE THREAD

**Issue by robe070** [ingydotnet/git-subrepo#156]
9f2ab87
MINGW64_NT-6.3 RobertPC 2.4.0(0.292/5/3) 2016-01-07 19:39 x86_64 Msys
git version 2.7.2.windows.1

Parent Repo A with subrepo C. 

1. Commit file a.txt to sub-directory C. 
2. subrepo push C

Parent Repo B with subrepo C
1. Commit file b.txt to sub-directory C. 
2. subrepo pull C - error - `can't find a common ancestor`

And whilst I was writing that I tried the same process but with file b.txt left out!
Still got `can't find common ancestor`!

**Comment by robe070** [comment]
And before `subrepo push C` from A, I tried `subrepo pull C` from B and it duly noted that subrepo is up to date

**Comment by grimmySwe** [comment]
Can you perform the same operation here as in https://github.com/ingydotnet/git-subrepo/issues/155#issuecomment-191647724 ? It's really hard to say anything without the actual output from subrepo merge-base.

**Comment by robe070** [comment]
It's late evening here. I'd like to make progress tomorrow. Have you tried these simple steps on Windows?

Warm regards

Rob Goodridge

On 3 Mar 2016, at 7:30 PM, Magnus Karlsson <notifications@github.com> wrote:

Can you perform the same operation here as in #155 (comment) ? It's really hard to say anything without the actual output from subrepo merge-base.

**Comment by grimmySwe** [comment]
During the last days I have done a lot of development/testing on Windows for #142 and I have not experienced anything like that. And the unittests actually performs operations like this and they seem to succeed.

I don't have access to Windows right now, but I tested some cases on my linux machine and there it works as expected.

I will test this at home tonight (In like 10 hours from now) and see if there is a difference.

**Comment by robe070** [comment]
Bare repo issue? I notice there is a push --force. The  Subrepo is setup to reject forced push though I see no report of a failure by subrepo push at that point in the process. 

I'll put these repos up on GitHub tomorrow. They are small and already publicly available elsewhere.  

Warm regards

Rob Goodridge

On 3 Mar 2016, at 8:48 PM, Magnus Karlsson <notifications@github.com> wrote:

During the last days I have done a lot of development/testing on Windows for #142 and I have not experienced anything like that. And the unittests actually performs operations like this and they seem to succeed.

I don't have access to Windows right now, but I tested some cases on my linux machine and there it works as expected.

I will test this at home tonight (In like 10 hours from now) and see if there is a difference.

**Comment by robe070** [comment]
The two repos are now up on github:
git@github.com:robe070/vl_demoapp.git - the subrepo
git@github.com:robe070/vl_test.git - the parent

Still get the same error when I `subrepo pull` from vl_demoapp.git on github.

@grimmySwe  I'll try the #155 directions you gave me.

**Comment by robe070** [comment]
Running subrepo plumbing commands...
Well there is more info - there are multiple matches. What do I do now?

```
robert@RobertPC /c/dev/Git/vl_test master $ git subrepo merge-base subrepo/demoapp/fetch subrepo/demoapp --all --debug --verbose
>>> git rev-parse --verify HEAD
* source1 side: 34 commits
* target1 side: 4 commits
Multiple on subrepo/demoapp/fetch: 0c9ed7e6d80479b7a3dfa7a17a831d05c250c176_03a35c3deb8e1cb7061fcac5b05c68defcdce641
Multiple on subrepo/demoapp/fetch: 0c9ed7e6d80479b7a3dfa7a17a831d05c250c176_03a35c3deb8e1cb7061fcac5b05c68defcdce641
Multiple on subrepo/demoapp/fetch: f03ff5639ae0ade99cef4662e8c83b996fe62f4c_9252d5098c7a621f399c3ac74d2eb24fd3be628f
Multiple on subrepo/demoapp/fetch: f03ff5639ae0ade99cef4662e8c83b996fe62f4c_9252d5098c7a621f399c3ac74d2eb24fd3be628f
* No ancestor found
```

**Comment by ingydotnet** [comment]
@robe070 I was able to:

```
$ git clone git@github.com:robe070/vl_test.git
$ git subrepo pull Demoapp
Subrepo 'Demoapp' pulled from 'git@github.com:robe070/vl_demoapp.git' (trunk).
```

Pulling Demoapp2 fails for me because the remote is private.

**Comment by grimmySwe** [comment]
Multiple is simply that same tree hash occurs several time on one side and
can't be used.

2016-03-03 22:49 GMT+01:00 Rob Goodridge <notifications@github.com>:

**Comment by robe070** [comment]
@ingydotnet I didn't put Demoapp2 on github. That Demoapp works for you is sufficient.

So works for you but not for me. At least it works somewhere!

The question is how do I troubleshoot why it doesn't work for me?

**Comment by robe070** [comment]
@ingydotnet What version of git are you using?

**Comment by grimmySwe** [comment]
So I did this:
```
$ git clone git@github.com:robe070/vl_test.git
$ cd vl_test/
$ git subrepo fetch Demoapp
$ git subrepo branch Demoapp

$ git subrepo merge-base subrepo/Demoapp/fetch subrepo/Demoapp --all
Valid: 4e3fec002b60d781401f775653fa7713cfd8e304 = 82e33c183e4b7ba6ab9f488c52be2285b9b9d5a7
Multiple on subrepo/Demoapp/fetch: 0c9ed7e6d80479b7a3dfa7a17a831d05c250c176_03a35c3deb8e1cb7061fcac5b05c68defcdce641
Multiple on subrepo/Demoapp/fetch: 0c9ed7e6d80479b7a3dfa7a17a831d05c250c176_03a35c3deb8e1cb7061fcac5b05c68defcdce641
Multiple on subrepo/Demoapp/fetch: f03ff5639ae0ade99cef4662e8c83b996fe62f4c_9252d5098c7a621f399c3ac74d2eb24fd3be628f
Multiple on subrepo/Demoapp/fetch: f03ff5639ae0ade99cef4662e8c83b996fe62f4c_9252d5098c7a621f399c3ac74d2eb24fd3be628f

$ git subrepo merge-base subrepo/Demoapp/fetch subrepo/Demoapp
Found common ancestor between these commits:
  'subrepo/Demoapp/fetch': '4e3fec002b60d781401f775653fa7713cfd8e304'
  'subrepo/Demoapp':HEAD '82e33c183e4b7ba6ab9f488c52be2285b9b9d5a7'

$ git subrepo merge-base subrepo/Demoapp/fetch subrepo/Demoapp --all -vd
>>> git rev-parse --verify HEAD
* source1 side: 34 commits
* target1 side: 1 commits
* Found ancestor: 4e3fec002b60d781401f775653fa7713cfd8e304,82e33c183e4b7ba6ab9f488c52be2285b9b9d5a7
* Steps from HEAD: 1
Valid: 4e3fec002b60d781401f775653fa7713cfd8e304 = 82e33c183e4b7ba6ab9f488c52be2285b9b9d5a7
Multiple on subrepo/Demoapp/fetch: 0c9ed7e6d80479b7a3dfa7a17a831d05c250c176_03a35c3deb8e1cb7061fcac5b05c68defcdce641
Multiple on subrepo/Demoapp/fetch: 0c9ed7e6d80479b7a3dfa7a17a831d05c250c176_03a35c3deb8e1cb7061fcac5b05c68defcdce641
Multiple on subrepo/Demoapp/fetch: f03ff5639ae0ade99cef4662e8c83b996fe62f4c_9252d5098c7a621f399c3ac74d2eb24fd3be628f
Multiple on subrepo/Demoapp/fetch: f03ff5639ae0ade99cef4662e8c83b996fe62f4c_9252d5098c7a621f399c3ac74d2eb24fd3be628f
* No ancestor found   <<<<==== You always get this when running --all -vd
```

I am using 
```
$ git --version
git version 2.7.0.windows.1
$ uname
MINGW64_NT-6.1
```

**Comment by grimmySwe** [comment]
Wait a minute...
Your merge-base list that there is 4 commits on the target side, I only have one:
```
$ git log subrepo/Demoapp --oneline
82e33c1 git subrepo clone --branch=trunk lansagit@gitsrv:/home/git-repo/vl_demoapp.git Demoapp
```

**Comment by robe070** [comment]
I've just cloned vl_test back to my machine - to be exactly like you - and still same issue - 4 commits on target side.

**Comment by robe070** [comment]
```
$ git log subrepo/Demoapp --oneline
0cde6b9 move subrepo to github
2c159ff git subrepo clone --branch=trunk lansagit@gitsrv:/home/git-repo/vl_demoapp.git Demoapp2
57aacc9 git subrepo clone --branch=trunk lansagit@gitsrv:/home/git-repo/vl_demoapp.git Demoapp
e438c67 first commit
```

**Comment by ingydotnet** [comment]
```
> uname
Darwin
> git --version
git version 2.7.2
> bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by grimmySwe** [comment]
There seems to be something fishy, I get those commits when I log the regular parent repo
```
$ git log --oneline -n 5
0cde6b9 move subrepo to github
2c159ff git subrepo clone --branch=trunk lansagit@gitsrv:/home/git-repo/vl_demoapp.git Demoapp2
57aacc9 git subrepo clone --branch=trunk lansagit@gitsrv:/home/git-repo/vl_demoapp.git Demoapp
e438c67 first commit

```

**Comment by robe070** [comment]
Fixed! Case sensitivity! I was referring to the subdir as `demoapp` not `Demoapp`!

**Comment by grimmySwe** [comment]
Halleluja! I love problems with easy fixes :-)

**Comment by robe070** [comment]
thank you for your precious time :smile: 
Now back to #155

**Comment by grimmySwe** [comment]
But it seems to be a bug then that you don't get an error message when you refer to something that doesn't exist? because the result is totally screwed up.
```
$ git subrepo branch demoapp --force
Created branch 'subrepo/demoapp'.

$ git log --oneline -n 5 subrepo/demoapp
0cde6b9 move subrepo to github
2c159ff git subrepo clone --branch=trunk lansagit@gitsrv:/home/git-repo/vl_demoapp.git Demoapp2
57aacc9 git subrepo clone --branch=trunk lansagit@gitsrv:/home/git-repo/vl_demoapp.git Demoapp
e438c67 first commit
```

I'll keep this open for a little while longer.

**Comment by robe070** [comment]
yes I agree. Good to address some time.

**Comment by ingydotnet** [comment]
Closing this. Moved real issue to #157.
