### ISSUE TITLE
Update clean.t test for --ALL and --all

### ISSUE THREAD

**Issue by stsquared99** [ingydotnet/git-subrepo#167]
Issue for reference, currently working on it.

**Comment by stsquared99** [comment]
@ingydotnet 
One thing I noticed, when I run "clean --all --force", it will remove everything under .git/refs/subrepo/, including those of nested subrepos, even though --ALL isn't specified. Is that fine as is, or should we make the clean --force smarter?

**Comment by ingydotnet** [comment]
I'm OK with making it smarter, by which I assume you mean just removing the
files under the specific directory.

One thing I want though is that `clean --force --ALL` removes
`.git/refs/subrepo/` entirely. The reason for this is that there times when
working on different mainline branches, that you end up with artifacts for
subrepos that don't exist on other branches. So `git subrepo clean -fA` should
nuke all refs, heads, remotes etc that contain 'subrepo' in them.

**Comment by grimmySwe** [comment]
It should probably remove things in .git/refs/heads/subrepo/* as well.

**Comment by stsquared99** [comment]
> It should probably remove things in .git/refs/heads/subrepo/* as well.

Added to #168 
Thanks
