### ISSUE TITLE
subrepo init - What should it do?

### ISSUE THREAD

**Issue by grimmySwe** [ingydotnet/git-subrepo#169]
In current 0.3.0 the `subrepo init` will create a local version of the sub directory by using filter-branch --subdirectory-filter. It wil then create a .gitrepo file with the .commit and .parents in place.

Question is whether it needs to do the filter-branch if it doesn't push anything anyway? OR on the other hand, should init actually push things into a remote.

By pushing it would make the repo fully operational and end up in a similar state as when you do a clone.

This might also depend on the direction of #142, where the first push more special.

**Comment by stsquared99** [comment]
I have a real use case where my team is trying to split a large single repo into a bunch of smaller subrepos. Being able to init just locally is incredibly useful in playing around with how we want to organize the subrepos, before we actually create/push to the finalized subrepos. It feels akin to commit things locally, but only pushing to remotes when I am ready to.

**Comment by grimmySwe** [comment]
Good input! Then we know that there is an interest in having local subrepos. Then the question is if it needs to do that much.

What do you do with the subrepos when they are in the init state?

**Comment by stsquared99** [comment]
For my use case at least, I init a bunch of subrepos, and then sometimes undo all of those and init them a different way as I decide which subfolders should/shouldn't be subrepos. It would be quite bothersome if it was actually pushing to a remote each time. It wouldn't cause me any trouble if there was a flag to not push.

Thinking more generalized, though, I could theoretically make commits and changes indefinitely after I init a subrepo, before finally pushing the subrepo when I wanted to publish it. Just like when I init a regular git repo. It doesn't need to be tied to a remote until I want it to.

I do see your point though. A subrepo does seem kind of pointless without being tied to a remote.
