### ISSUE TITLE
Can't push to subrepo if last commit is a merge commit

### ISSUE THREAD

**Issue by perlpunk** [ingydotnet/git-subrepo#181]
I tried to clone a subrepo, do some local changes and push, but got the error message
`git-subrepo: Can't find a common ancestor between refs/subrepo/ext/shared/fetch and subrepo-push/ext/shared [...]`

First I couldn't reproduce it with simple example repos, but I found out when it happens now.
The last commit of the subrepo has to be merge commit.
Here's a script that will reproduce the error:

```
#!/usr/bin/env bash

# shared repo, master
git init --bare shared.git
git clone shared.git shared
cd shared
echo README > README
git add README
git commit -m "init"
git push

# shared repo, creating merge commit
git checkout -b branch1
echo foo > foo.txt
git add foo.txt
git commit -m "foo.txt"
git checkout master
git merge --no-ff branch1 -m "merge --no-ff branch1"
git branch -d branch1
git push

cd ..

# main repo
git init --bare project.git
git clone project.git project
cd project
echo README > README
git add README
git commit -m "init"
git push

# cloning subrepo
git subrepo clone ../shared.git ext/shared
echo "local" > ext/shared/local.txt
git add ext/shared/local.txt
git commit -m "added local.txt in git-subrepo"

git subrepo push ext/shared
# git-subrepo: Can't find a common ancestor between
# refs/subrepo/ext/shared/fetch and subrepo-push/ext/shared. [...]
```

**Comment by LovesTha** [comment]
I'm getting the same error and the head of where the subrepo is trying to push to isn't a merge commit (it was previously, but I've ensured it isn't now)

Simply doing:
git subrepo clone <repo> <dir>
git subrepo push <dir>
gives me:
git-subrepo: Can't find a common ancestor between refs/subrepo/<dir>/fetch and subrepo-push/<dir>. This might be the case if someone used push --force on the subrepo. You need to find out why and possibly reclone the subrepo.

Should I be putting this as a separate issue?

**Comment by grimmySwe** [comment]
@LovesTha If you have the time to create a simple use case to reproduce your error it would always be good to actually verify that it solves your case. If you think it differs from this issue so yes, please add it as another issue.

The tree hash common ancestor logic has some drawbacks. I have some ideas on how to solve that in #142 but unfortunately there are a lot of other stuff going on right now so I haven't got the time to finish that solution at the moment. The issue/142 branch is though in an acceptable state with all tests working, the main todo:s are generating good commit messages. So if you have the time please test it out and see if it works in this case.

**Comment by perlpunk** [comment]
@grimmySwe oh thanks, didn't know that there is already a branch that addresses this issue.
Tested my script with issue/142 and it works.
I'll try it out tomorrow with the real repositories.

**Comment by LovesTha** [comment]
@grimmySwe Thanks for all that.
In the end I've tried out the issue/142 branch and it works. Thus my interest has waned. But I'm excited for the 142 branch.

**Comment by grimmySwe** [comment]
Fix for this has reached master.
