### ISSUE TITLE
Subrepos need to be top level

### ISSUE THREAD

**Issue by evilWicked** [ingydotnet/git-subrepo#182]
#I am having problems with the situation where I have a broader dependency project containing a source folder containing a collection of third party dependencies
```
third-party-deps
   -.git
   -build
   -include
   -bin
   -src
        -repo1
           -.git
        -repo2
           -.git
        -repo3
           -.git

etc.
```
When I move into src and try to init a subrepo 
```
cd src
$ git subrepo init repo1
```

I get a 
```
$ git subrepo init repo1
git-subrepo: Need to run subrepo command from top level directory of the repo.
```

If I move to the top level and try to add it via a path
```
$ git subrepo init src/repo1
git-subrepo: The subdir 'src/repo1' is not part of this repo.
```
Does this mean that sub repos must be at the top level?

**Comment by grimmySwe** [comment]
`git subrepo init` needs that git has knowledge of the files. So if you want to use init you need to add/commit repoX first.

If the repos already exist elsewhere you can use `git subrepo clone repoX` to clone in the external repos.

**Comment by evilWicked** [comment]
The files were in git.  I had added an empty directory from them - perhaps the keyword here is empty...  

In fact I had tried several approaches - in this case I had created the directory tree, created the top level repo including the sub directory as a placeholder and then tried adding that as a sub-repo.  

In any case let me test it.   Git may simply have ignored it because it was empty.

**Comment by evilWicked** [comment]
OK that was different. It still needs to be run from the top level but at least it created it this time

```

xxx@xxxx MINGW64 ~/Documents/audio-development/audio-git-tp/third-party-deps/src (master)
$ git ls-files
.gitignore
test/placeholder.txt

xxx@xxxx  MINGW64 ~/Documents/audio-development/audio-git-tp/third-party-deps/src (master)
$ git subrepo init test
git-subrepo: Need to run subrepo command from top level directory of the repo.

xxx@xxxx MINGW64 ~/Documents/audio-development/audio-git-tp/third-party-deps/src (master)
$ cd ..

xxx@xxxx MINGW64 ~/Documents/audio-development/audio-git-tp/third-party-deps (master)
$ git subrepo init src/test
Subrepo created from 'src/test' (with no remote).

xxx@xxxx  MINGW64 ~/Documents/audio-development/audio-git-tp/third-party-deps (master)
$
```
