### ISSUE TITLE
push fails on up-to-date subrepo

### ISSUE THREAD

**Issue by rbellamy** [ingydotnet/git-subrepo#186]
Last commit is **not** a merge commit.
1. I test to make sure I have the latest history from the subrepo - it "is up to date."
2. I try to push to the subrepo, and get `Command failed: get rebase --onto...` error.

``` zsh
2016-05-13 11:27:14
rbellamy@eanna i ~/Development/Terradatum/ansible/ansible-metrics master % git subrepo pull roles/httpd 
Subrepo 'roles/httpd' is up to date.
2016-05-13 11:28:51
rbellamy@eanna i ~/Development/Terradatum/ansible/ansible-metrics master % git subrepo push roles/httpd          
git-subrepo: Command failed: 'git rebase --onto 9b5e6b893220b351baece30175aa90c61261e02d 8336401263724b6f871322bec23b30e3e29472dc subrepo-push/roles/httpd'.
zsh: exit 1     hub subrepo push roles/httpd
2016-05-13 11:29:06
rbellamy@eanna i ~/Development/Terradatum/ansible/ansible-metrics subrepo-push/roles/httpd rebase % 
```

**Comment by rbellamy** [comment]
Looks like the problem is that the subrepo merge is failing. However, it really shouldn't be trying to merge from subrepo to parent, as we've already determined that the parent has the correct history?

```diff
diff --cc tasks/main.yml
index 31d6ea7,ef7b808..0000000
--- a/tasks/main.yml
+++ b/tasks/main.yml
@@@ -15,6 -15,4 +15,10 @@@
  
  - include: mod_cluster.yml
    when: mod_cluster_installed.stdout is not defined or not mod_cluster_installed.stdout
++<<<<<<< 337375f077b5448cdcea73fb918fbb5455dd58cb
 +  
 +- name: 'Start and enable httpd'
 +  service: name=httpd state=restarted enabled=true
++=======
+ 
++>>>>>>> Refactor to serve static content via Apache
```

The content that `git-subrepo` is attempting to merge into the parent was removed and is already part of the history of the parent.

In other words:
1. `git subrepo clone roles/httpd git@github.com:terradatum/roles-httpd`
2. hack on `roles/httpd/tasks/main.yml`
3. `git subrepo push roles/httpd`
4. `git-subrepo` attempts to merge `git@github.com:terradatum/rolse-httpd` into `roles/httpd` even though that history already exists in the parent.

I'm completely confused here...

**Comment by rbellamy** [comment]
2016-07-21 18:24:28
rbellamy@eanna i ~/Development/Terradatum/ansible/ansible-metrics master % git subrepo push --debug roles/httpd  
>>> git rev-parse --verify HEAD
>>> git fetch --quiet git@github.com:terradatum/role-httpd master
>>> git rev-parse FETCH_HEAD
>>> git filter-branch -f --subdirectory-filter roles/httpd HEAD
>>> git filter-branch -f --tree-filter rm -f .gitrepo
>>> git branch subrepo-push/roles/httpd
>>> git reset --hard cd818e1ad66e794251dc5abcb85e10defb5113ae
>>> git rebase --onto 9b5e6b893220b351baece30175aa90c61261e02d 8336401263724b6f871322bec23b30e3e29472dc subrepo-push/roles/httpd
git-subrepo: Command failed: 'git rebase --onto 9b5e6b893220b351baece30175aa90c61261e02d 8336401263724b6f871322bec23b30e3e29472dc subrepo-push/roles/httpd'.
zsh: exit 1     hub subrepo push --debug roles/httpd

**Comment by torinaki** [comment]
Same problem for me.

**Comment by torinaki** [comment]
I'm using subrepo fot push-only, so I need to just synchonize remote repository and I do not commit anything into remote repository directly. After investigation I have figure out that it fails to rebase  commit that follows merge commit that solves merge conflict. So need to solve this conflict again.

**Comment by grimmySwe** [comment]
Current implementation (0.3) has a lot of troubles with duplicate tree hashes so that might be one cause of it. There is a subrepo command called merge-base that actually simulates what it's trying to do behind the scene.

Something like this should give you a hint:
```
# git subrepo clean roles/httpd           (Clean up old branches)
# git subrepo fetch roles/httpd            (Update the local subrepo structure)
# git subrepo branch roles/httpd         (Create a local branch of the current state in the subrepo)
# git subrepo merge-base --all subrepo/roles/httpd/fetch subrepo/roles/httpd       (try to find common ancestor)
```

I am currently working on a new version #142 that should handles this in another better way.

**Comment by torinaki** [comment]
@grimmySwe thanks you for quick response. I will try to fix this issues as you have suggested. I also was tried another tool that do same thing: https://github.com/splitsh/lite . It written on Go and is incredibly fast! It originally written for large repos to automate splitting it into many subrepos and used by such project like https://github.com/symfony/symfony. I'm suggesting to take a look. May be some ideas will be useful for you.
I'm really like your approach with .gitrepo, so hope this issue will be fixed in near future.

**Comment by grimmySwe** [comment]
@torinaki @rbellamy There is a issue/216 branch that works a lot better now if you are interested to try it out.

**Comment by grimmySwe** [comment]
Fix for this has reached master.
