### ISSUE TITLE
Fish shell integration

### ISSUE THREAD

**Issue by therealmarv** [ingydotnet/git-subrepo#187]
I will try to look into this. It seems here is only bash and zsh integration.

**Comment by ingydotnet** [comment]
I would like to see this done using a file called `.rc.fish`. Look at `.rc`. Just need to set the PATH, MANPATH and take care of completion.

**Comment by therealmarv** [comment]
It should not be that complicated, you're right. I hope I have enough spare time to finish it :)

It should be straight forward:
1. Convert the env variables to fish: https://github.com/ingydotnet/git-subrepo/blob/master/.rc
2. Getting the completion syntax from bash/zsh https://github.com/ingydotnet/git-subrepo/blob/master/share/zsh-completion/_git-subrepo to fish completion syntax.
3. Sourcing is not very common in fish (or it seems it is bad practice). Better convert 1) to an [autoloading function](http://fishshell.com/docs/current/tutorial.html#tut_autoload) which is called once at the beginning of config.fish (<- this is the bash.rc in fish). How to do it by example looking at rvm: https://rvm.io/integration/fish#setup

Will work on 1) and 3) and then I will see how to get 2) working.

**Comment by grimmySwe** [comment]
@therealmarv Any progress on this?

**Comment by therealmarv** [comment]
Hi @grimmySwe sorry, no. I also do not do a lot with git submodules nowadays. Basically I cannot find time to work on side (open source) projects nowadays (the fulltime opensource projects I work for need all my time). I really like concept on git-subrepo but in the near future I don't need it. I hope somebody else with more fish shell intelligence than me can pick up on this. The step I mentioned should be a good pointer.

**Comment by grimmySwe** [comment]
@therealmarv I fully understand your situation. You know where to find us if you find large holes in your schedule :-)

**Comment by ErikBjare** [comment]
I started working on this: https://github.com/ingydotnet/git-subrepo/issues/284

Very minor stuff, but it works.
