### ISSUE TITLE
git subrepo push -a gives error: Local branch is not updated, perform pull

### ISSUE THREAD

**Issue by georgegrigorita** [ingydotnet/git-subrepo#191]
This is my setup: 
- main repo
  -- subrepo1
  -- subrepo2 

I'm working on a local branch in main-repo. I've added subrepo1 and subrepo2 both tracking the remote master branch of their repository. 
The issue is this: each time I modify or add files to subrepo1 or subrepo2 and I do a `git subrepo push -a` I get an "Local branch is not updated, perform pull or use '--force' to always trust local branch in conflicts". The same happens even after I do an `git subrepo pull -a`. 
However, if I go one by one it works fine: 
- `git subrepo pull subrepo1`
- `git subrepo push subrepo1` 

This way I don't get any errors but it's not practical, I have 10 subrepos.

**Comment by grimmySwe** [comment]
What version of git-subrepo are you using?

There was a bug with --all #120, #115.

**Comment by georgegrigorita** [comment]
I think it was 0.3.0, since then I moved to git submodules.
