### ISSUE TITLE
Workflow for Third Party Code?

### ISSUE THREAD

**Issue by adeluccar** [ingydotnet/git-subrepo#200]
Hey everyone,

I can't seem to grok the git-subrepo model entirely to replicate my workflow.
### What I want to use git-subrepo for

I want to use git-subrepo to maintain several third party libraries (including git-subrepo itself) in my dotfiles where each subrepo has an origin remote pointing to my fork and an upstream remote pointing to their master for updating purposes.
### Find Code Workflow
1. Find a cool library.
2. Fork their repo. # my (**origin**)
3. `git clone my-account@repo` # my local repo
4. `git remote add upstream 3rd-party@repo` # their repo (**upstream**)
### Update Workflow
1. `git checkout master` # Checkout master
2. `git fetch upstream` # Fetch updates from 3rd-party
3. `git rebase upstream/master` # Merge updates from 3rd-party 
4. `git push origin` # Push the new changes to my origin repo

**How can I replicate these workflows with git-subrepo?**
Thank you for your help.

**Comment by grimmySwe** [comment]
I don't really get your question here, could you please try and give an overview of what repos are involved in your operations?

Do you mean that you have a main repo including several subrepos, each of the subrepos pointing to a fork of the original or?

**Comment by adeluccar** [comment]
Yes, what I would like to do is keep forks of software I like as subrepos but pointing to my fork and not the original repo. In my case, origin would point to adeluccar/rails and upstream points to rails/rails. In my machine, when not using subrepos I keep them updated by using the update workflow above. I would like to know if this is possible with git subrepos.

**Comment by grimmySwe** [comment]
I would say that you can use the exact same workflow. 

You find a cool library A, you create a fork of A called fork_A. Whenever you want to use it inside another project B you clone it in with git-subrepo. So when you work in B you will work against fork_A. When you need to push changes to A or get new feature you go directly to your fork_A and merge in the latest and push your changes. Then you pull in these changes to your projects like B.

I don't have so much experience with this workflow so I might have misunderstood something.

**Comment by grimmySwe** [comment]
@adeluccar Please reopen and add more information.

**Comment by adeluccar** [comment]
I don't even understand what I was asking at the time. :smile:
