### ISSUE TITLE
Cannot seem to figure this out

### ISSUE THREAD

**Issue by mcblum** [ingydotnet/git-subrepo#201]
Need some help if anyone has a moment. First of all, thank you for putting this package together. I love it, although I can't figure it out.

Our main repo has a git subrepo called 'templates'. We'd like to be able to deploy and update templates to the server without touching the main repo. I successfully loaded the templates sub-repo, but I cannot figure out how to update it. Changes to the templates subdirectory are being checked in with the main repo, so I figured I'd just need to go git subrepo push templates and it would take the changes I'd make and update the subrepo, but I get:

git-subrepo: There is a previous push branch 'subrepo-push/templates'. Delete it first.

I don't understand at all! Thanks in advance for any guidance. I've read the docs 100 times and still don't quite get it.

**Comment by juddgaddie** [comment]
Why don't you delete the branch it's asking you to delete.

**Comment by grimmySwe** [comment]
You can use `git subrepo clean templates`, that will remove all temporary branches used by git-subrepo.

**Comment by mcblum** [comment]
@juddgaddie There's only one branch! 
@grimmySwe Going to try that right now.

Thanks to both of you, will report back either way in case anyone finds themselves in the same position I was in.

**Comment by mcblum** [comment]
`➜ git subrepo push templates  
git-subrepo: Command failed: 'git rebase --onto 31e30ad9720276939767ea15e5f3a7ccc967069d b8b269ac12737599dd3cbe6bb811e9816cd7d8e5_b7bbfa1475c43c34c606c477b9708e757055cccf_4f8551a5a797deae7b65425b88edf9b096157b77 subrepo-push/templates'.
`

**Comment by grimmySwe** [comment]
There are verbose and debug flags that can give us useful output:
`git subrepo push -v -d push templates`

You can also perform these steps get an overview of what we could expect:
```
git subrepo clean templates    # cleanup temporary branches
git subrepo fetch templates     # Fetch the subrepo and create a reference refs/templates/fetch
git subrepo branch templates   # Create local branch with your templates related changes
git subrepo merge-base --all refs/templates/fetch subrepo/templates    # List ancestry
```
There are some known issues with the current implementation in the way it handles similar commits so there might be some here.

**Comment by grimmySwe** [comment]
@mcblum please reopen and add some more information.
