### ISSUE TITLE
Support staged installs via the DESTDIR variable

### ISSUE THREAD

**Issue by jamesan** [ingydotnet/git-subrepo#203]
The `DESTDIR` variable is a common pattern supported only in install\* and uninstall\* targets of a Makefile often used in package creation or other fakeroot installation situations. The specifics of the `DESTDIR` variable can be found in the [GNU Make Manual](https://www.gnu.org/software/make/manual/html_node/DESTDIR).

`DESTDIR` should never be defined in the Makefile, but, when specified as an absolute path by the user when invoking the make command, its value should be prepended to each install target file. For example, if the invocation, `make install`, would normally install the target files: `/usr/local/bin/foo` and `/usr/local/share/man/man1/foo.1`, executing `make DESTDIR=/tmp/stage install` should likewise install these corresponding target files: `/tmp/stage/usr/local/bin/foo` and `/tmp/stage/usr/local/share/man/man1/foo.1`.

**Comment by jamesan** [comment]
I'm going to fork and submit a pull request resolving this issue. It should be relatively painless to do (I hope).

**Comment by juddgaddie** [comment]
Why not submit a pull request?

**Comment by juddgaddie** [comment]
Sorry, I now see your additional message.
