### ISSUE TITLE
Unable install git-subrepo

### ISSUE THREAD

**Issue by chungonn** [ingydotnet/git-subrepo#21]
I did  a - make install, and I got a cannot stat ‘doc/git-subrepo.1’: No such file or directory error message. 

I am on ubuntu 14.04 Linux #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 GNU/Linux

Here's the output after a make install 
~GIT_SUBREPO_HOME (master ✔) ᐅ sudo make install
[sudo] password for chungonn: 
install -C -m 0755 /home/chungonn/development/git/git-subrepo/lib/git-subrepo /usr/lib/git-core/
install -C -d -m 0755 /usr/lib/git-core/git-subrepo.d/
install -C -m 0755  /home/chungonn/development/git/git-subrepo/lib/git-subrepo.d/bash+.bash /usr/lib/git-core/git-subrepo.d/
install -C -d -m 0755 /usr/local/share/man/man1
install -C -m 0644 doc/git-subrepo.1 /usr/local/share/man/man1
install: cannot stat ‘doc/git-subrepo.1’: No such file or directory
make: *** [install-doc] Error 1

**Comment by ingydotnet** [comment]
Fixed. Apologies for the delay.

Try the `remix` branch for the totally redone version. Should be on master in
the next day or 2.
