### ISSUE TITLE
git-subrepo clone doesn't work with email as part of url for authentication

### ISSUE THREAD

**Issue by gcstang** [ingydotnet/git-subrepo#211]
git-subrepo clone ssh://user.name%40domain.com@git.mydomain.com:3333/subreposub1.git subreposub1
Returns
git-subrepo: Command failed: 'git ls-remote ssh://user.name domain.com@git.mydomain.com:3333/subreposub1.git'.

**Comment by perlpunk** [comment]
Right, the percent sign is interpreted by printf.
Can you try out if pull request #212 works for you?

**Comment by gcstang** [comment]
That worked!

Thank you

**Comment by grimmySwe** [comment]
This issue is solved and available on master.
