### ISSUE TITLE
Question: How do I diff the local subrepo'd directory with the remote repo?

### ISSUE THREAD

**Issue by boardmanus** [ingydotnet/git-subrepo#213]
I want to see what changes I will be pushing to a subrepo directories upstream repository, but can't work out how to perform such a feat.

I saw an issue to add a subrepo diff command was rejected in favor of documenting how to diff the subrepo, but the wiki doesn't appear to be updated with such information.  The issue implies that a command such as `git diff refs/subrepo/ext/bashplus/fetch subrepo/ext/bashplus` could be used, but this doesn't do the trick for me.

Given a structure like:
<pre>
# my_repo, that subrepo's remote_a
my_repo
+-- remote_a
     +-- file_a

# Remote repo incorporated into my_repo
remote_a
+-- file_a
</pre>

I then update `file_a` from my_repo:
<pre>
echo junk >> remote_a/file_a
git add .
git commit -m "Added some junk"
</pre>

Now I want to push, but before I do, want to remind myself of what I did. I thought something like `git diff refs/subrepo/remote_a/fetch remote_a` would do the trick, but it does not.  Instead it shows all the files as new files.

<pre>
$ git diff refs/subrepo/remote_a/commit remote_a
diff --git a/remote_a/.gitrepo b/remote_a/.gitrepo
new file mode 100644
index 0000000..865b2ca
--- /dev/null
+++ b/remote_a/.gitrepo
@@ -0,0 +1,11 @@
+; DO NOT EDIT (unless you know what you are doing)
+;
+; This subdirectory is a git "subrepo", and this file is maintained by the
+; git-subrepo command. See https://github.com/git-commands/git-subrepo#readme
+;
+[subrepo]
+       remote = ../remote_a
+       branch = master
+       commit = 145ad1ebb219f5a7feb5f65c7518944333c132b1
+       parent = none
+       cmdver = 0.3.0
diff --git a/remote_a/file_a b/remote_a/file_a
new file mode 100644
index 0000000..54259ab
--- /dev/null
+++ b/remote_a/file_a
@@ -0,0 +1,2 @@
+original-content-in-file
+junk
</pre>

I expected to see this: (ok, and perhaps the new .gitrepo file)
<pre>
$ git diff HEAD^ remote_a/file_a
diff --git a/remote_a/file_a b/remote_a/file_a
index 696fb6b..54259ab 100644
--- a/remote_a/file_a
+++ b/remote_a/file_a
@@ -1 +1,2 @@
 original-content-in-file
+junk
</pre>

Could someone please let me know what I am doing wrong?  That wiki entry would be mighty handy right now ;)

**Comment by grimmySwe** [comment]
To diff correctly you need to create the local version of the subrepo that you intend to push. To accomplish this you use the `git subrepo branch` command. It will go through your repo and reconstruct a local version of the subrepo and put that in subrepo/<SUBREPO> branch.

```
# git subrepo branch remote_a
# git diff subrepo/remote_a/fetch subrepo/remote_a
```

I hope that works for you!

**Comment by boardmanus** [comment]
Thanks, that did the trick.
