### ISSUE TITLE
Updating subrepo failure: git-subrepo: Command failed: git rebase --onto

### ISSUE THREAD

**Issue by micah** [ingydotnet/git-subrepo#215]
i'm having trouble updating a subrepo, i did this:

```
$ git subrepo pull puppet/modules/tor
git-subrepo: Command failed: 'git rebase --onto dcb6e748864e7dfd3c14f4f2aba4c9120f12b78a 429cb2d55be683e540960ddd3ad175dc97ec03a0_b37ab7ad1bb2de098791f557355358fe24177f49_7a1872d32c698406bdb3566cfa768419dd447cdc subrepo/puppet/modules/tor'
```

if I run with debug to see the commands:

```
$ git subrepo -d pull puppet/modules/tor
>>> git rev-parse --verify HEAD
>>> git fetch --quiet https://leap.se/git/puppet_tor master
>>> git rev-parse FETCH_HEAD^0
>>> git branch -D subrepo/puppet/modules/tor
>>> git filter-branch -f --subdirectory-filter puppet/modules/tor HEAD
>>> git filter-branch -f --prune-empty --tree-filter rm -f .gitrepo
>>> git branch subrepo/puppet/modules/tor
>>> git reset --hard b928a8f29b40df545ac6a72ead6cb9ed6a36fbda
>>> git rebase --onto dcb6e748864e7dfd3c14f4f2aba4c9120f12b78a 429cb2d55be683e540960ddd3ad175dc97ec03a0_b37ab7ad1bb2de098791f557355358fe24177f49_7a1872d32c698406bdb3566cfa768419dd447cdc subrepo/puppet/modules/tor
git-subrepo: Command failed: 'git rebase --onto dcb6e748864e7dfd3c14f4f2aba4c9120f12b78a 429cb2d55be683e540960ddd3ad175dc97ec03a0_b37ab7ad1bb2de098791f557355358fe24177f49_7a1872d32c698406bdb3566cfa768419dd447cdc subrepo/puppet/modules/tor'.
$ 
```

If I run the commands one by one, when I get to the rebase one at the end, I'm told:

```
fatal: Needed a single revision
invalid upstream 429cb2d55be683e540960ddd3ad175dc97ec03a0_b37ab7ad1bb2de098791f557355358fe24177f49_7a1872d32c698406bdb3566cfa768419dd447cdc
```

Any ideas?

**Comment by ingydotnet** [comment]
@grimmySwe what's with that invalid rebase sha with underscores in it?

@micah if you `git checkout issue/142` in the `$GIT_SUBREPO_ROOT` directory your `pull` works.

issue/142 fixes many many issues but still needs to get merged to master. @grimmySwe I have an open weekend coming up. You?

Still I think this is a bug in master...

**Comment by grimmySwe** [comment]
@ingydotnet I will have some time this weekend. The _ in sha is a leftover from the by bash array indexing, as you say there is probably a bug in there somewhere.

@micah To find the bug I would need to reproduce this case, I see that you use https://leap.se/git/puppet_tor, could you add some more example, where didi you clone and what did you do before you tried to pull in updates?

**Comment by micah** [comment]
@ingydotnet yes, if I checkout the branch issue/142, source the .rc, then it works.

@grimmySwe it seems like the bug is fixed in that branch, but if you want to see for yourself, you can do:
```
git clone https://leap.se/git/leap_platform
git checkout develop
git subrepo pull puppet/modules/tor
```

**Comment by grimmySwe** [comment]
So I found the bug, as a novice bash programmer I used > instead of -gt inside my [[ ]].

Here is a patch that will solve the problem.
```
diff --git a/lib/git-subrepo b/lib/git-subrepo
index 3c6f575..7fd977b 100755
--- a/lib/git-subrepo
+++ b/lib/git-subrepo
@@ -809,7 +809,7 @@ subrepo:merge-base() {
   for entry in ${merge_base_order[@]}; do
     local source_key="${source}_$entry"
     local source_value="${!source_key}"
-    if [[ ${#source_value} > 40 ]]; then
+    if [[ ${#source_value} -gt 40 ]]; then
       if $list_all; then
         say "Multiple on $1: $source_value"
       fi
@@ -820,7 +820,7 @@ subrepo:merge-base() {
         :
       else
         local target_value=${!target_key};
-        if [[ ${#target_value} > 40 ]]; then
+        if [[ ${#target_value} -gt 40 ]]; then
           if $list_all; then
             say "Multiple on $2: $target_value"
           fi
```

@ingydotnet Should we include this on current master while we wait for #142? It will not be present in #142 as the merge base has been replaced.

@micah Applying the patch above will get rid of your problem BUT another will appear, it will not find a common ancestor :-(

**Comment by micah** [comment]
@grimmySwe thanks for the response, but now I'm just a little bit confused. When I checked out branch issue/142, the problem was resolved... but you seem to be saying that you have a patch that is different, and introduces another error. 

If I use branch issue/142, will that introduce the other error, or is that not going to be there?

Also - forcing a reclone will fix this issue, but does that cause any other unintended side-effects I should know about?

thanks!

**Comment by grimmySwe** [comment]
@micah Sorry for the confusion. I'll try to explain:
1. Current master 0.3.0, has the bug explained above.
2. #142 does not have the problem
3. We are about to merge in #142 to master so that this problem will be solved but the question was when, if we should apply this patch for now.

Regarding reclone there are no side effects except that you will ignore any local changes. cloning will take the exact state from the subrepo.

**Comment by grimmySwe** [comment]
Created issue/215 branch for this and applied the patch.

**Comment by ingydotnet** [comment]
Applied. Pushed. Thanks.

@grimmySwe, I'm planning to spend the week on getting subrepo into a solid
state. For now I'm just applying or commenting on the open PRs. Applying this
wasn't necessary but also does no harm and is good to have in case I am delayed
along the way.
