### ISSUE TITLE
Wiki Basics: Command failed: 'git push ...'

### ISSUE THREAD

**Issue by kraftwer1** [ingydotnet/git-subrepo#217]
I followed the [Wikis Basics tutorial](https://github.com/ingydotnet/git-subrepo/wiki/Basics) and everything worked great until this step:

    $ git subrepo push shared

...which fails without telling me exactly why:

    git-subrepo: Command failed: 'git push --force /project/shared subrepo-push/shared:master'.

...and leaves a branch behind called `subrepo-push/shared`.

I'm using `git version 2.7.4 (Apple Git-66)`.

Any idea?

**Comment by ingydotnet** [comment]
Try running again with the `-v -d` flags. This should show you exactly what failed.

**Comment by kraftwer1** [comment]
Thanks, I've tried, can you see an obvious error? Did I miss something?

    $ git subrepo push -v -d shared
    >>> git rev-parse --verify HEAD
    * Fetch the upstream: ../shared (master).
      * Fetch '../shared' (master).
    >>> git fetch --quiet ../shared master
      * Get the upstream subrepo HEAD commit.
    >>> git rev-parse FETCH_HEAD^0
      * Create ref 'refs/subrepo/shared/fetch'.
    * Check upstream head against .gitrepo commit.
    * Create subrepo branch 'subrepo-push/shared'.
      * Check if the 'subrepo-push/shared' branch already exists.
      * Get commits specific to the subdir.
    >>> git filter-branch -f --subdirectory-filter shared HEAD
      * Remove the .gitrepo file from the history.
    >>> git filter-branch -f --prune-empty --tree-filter rm -f .gitrepo
      * Create branch 'subrepo-push/shared' for this new commit set.
    >>> git branch subrepo-push/shared
      * Reset to the 'master' branch.
    >>> git reset --hard 90e45d6c78f76995f5170b9872878cb38c2d590d
    * Find ancestor with same treehash.
    * source1 side: 3 commits
    * target1 side: 2 commits
    * Found ancestor: fe6479991d214f4d95ac2ae959d7252a866e01a3,28d34ad50f71b77eaa552524b7b24c2240bcc522
    * Steps from HEAD: 0
    * We have found a common ancestor with refs/subrepo/shared/fetch:HEAD
    * Set a common ancestor.
    >>> git rebase --onto fe6479991d214f4d95ac2ae959d7252a866e01a3 28d34ad50f71b77eaa552524b7b24c2240bcc522 subrepo-push/shared
    * Run 'git rebase -X theirs refs/subrepo/shared/fetch subrepo-push/shared'.
    >>> git rebase -X theirs refs/subrepo/shared/fetch subrepo-push/shared
    >>> git checkout master
    * Make sure that 'subrepo-push/shared' exists.
    * Make sure 'subrepo-push/shared' contains the 'refs/subrepo/shared/fetch' HEAD.
    * Push branch 'subrepo-push/shared' to '../shared' (master).
    >>> git push --force ../shared subrepo-push/shared:master
    git-subrepo: Command failed: 'git push --force ../shared subrepo-push/shared:master'.

**Comment by grimmySwe** [comment]
If you are using a local repo (a) as subrepo, you can't push to (a) unless you you have switched branch in (a). Otherwise you will try to move the branch reference currently referenced.

There is an important line hidden in the basic example:
```
$ git checkout -b other       # We need to step away from master if we want others to push changes here
Switched to a new branch 'other'
```
So if you go to shared and do the above you should be able to push.

**Comment by kraftwer1** [comment]
So if I clone from a remote repo, it will work even without `git checkout -b other`?

**Comment by ingydotnet** [comment]
I didn't even know that you could clone a local working directory. I would have cloned `../shared/.git`. Then you would't need to do any branch switching.

**Comment by grimmySwe** [comment]
Yes, if you have a remote repo as subrepo there will be no problem.

As long as no one has active references in there. I think that you can say
that if you have bare repos as subrepos there will be no problem.

tisdag 30 augusti 2016 skrev kraftwer1 <notifications@github.com>:

**Comment by ingydotnet** [comment]
I meant that (I assume) `../shared` is not a git repo; it is a working directory whose repo is in `../shared/.git`.

**Comment by grimmySwe** [comment]
As far as I know there is no difference between the working dir and the
.git dir inside it. You still need to switch branch unless you add some
setting in the repo that allows you to change references underneath your
feet.

Just tested to use .git and it still complains.

tisdag 30 augusti 2016 skrev Ingy döt Net <notifications@github.com>:

**Comment by kraftwer1** [comment]
Yes, it indeed works with a remote. Thanks for the amazing work.

**Comment by ingydotnet** [comment]
@grimmySwe, what am I missing in this reproduction: https://gist.github.com/7d11d142efb1c64963f427f43def424c

**Comment by grimmySwe** [comment]
You push with -b flag and that will create new references. If you try
without -b it will fail in both cases because you try to move the master
reference that is currently in use.

I think there is some configuration property that will allow you to do it,
I can't remember the name now though.

onsdag 31 augusti 2016 skrev Ingy döt Net <notifications@github.com>:

**Comment by grimmySwe** [comment]
Found out that if you remove -b you will also run in to other problems :-) First of all you end up in a strange dependency to itself resulting in `git-subrepo: Local branch is not updated, perform pull or use '--force' to always trust local branch in conflicts`

If I use a separate repo as subrepo I will need to change something otherwise I will get `Subrepo 'xxx' has no new commits to push.`
