### ISSUE TITLE
Cannot find common ancestror after fork

### ISSUE THREAD

**Issue by alexfouche** [ingydotnet/git-subrepo#221]
Hi,
I have for example this project https://github.com/alexfouche/puppet-redis which i forked and subrepo cloned, then i cannot push. Even after i added a commit independently, and then remove and subrepo clone again, i still cannot push due to no common ancestror.
Let me recap:
1. On Github, i fork https://github.com/arioch/puppet-redis
2. on my workstation, i `git subrepo clone https://github.com/arioch/puppet-redis modules/redis`. Note that i may have had some stashed changes to ensure a clean repo
3. i make some changes, and create a commit.
4. i try `git subrepo push modules/redis`
   1. boom! no common ancestror
5. i try a `git subrepo clean --ALL --force`, then the push again, but still failing

Then i deleted completely modules/redis, apply and push the commit independently from a normal clone elsewhere
1. I go back to my main directory, and do a `git subrepo clone https://github.com/alexfouche/puppet-redis modules/redis`. The last commit of this repo is not the forked one but the one i pushed just before
2. i try `git subrepo push modules/redis`
   1. boom! no common ancestror

**Comment by grimmySwe** [comment]
Current (0.3.0) implementation has some big flaws, we do know this and in #142 we are designing a new version. You can test the same use case with issue/142 branch and see if it solves your problem.

Reason is that it works on tree hashes and that they can be duplicates.

**Comment by alexfouche** [comment]
branch #142 seems to work fine and solved my problems
