### ISSUE TITLE
Repos with underscore (_) in name can't be added

### ISSUE THREAD

**Issue by csteinlehner** [ingydotnet/git-subrepo#224]
Hi,

I just tried to add a sub-repo with an underscore in the name like this
`git subrepo clone https://someurl.com/test/test_test.git` and I get following error `git-subrepo: Can't determine subdir from 'https://someurl.com/test/test_test.git'.` 

I tried that with several Repos with an underscore in the name and its always the same.

**Comment by grimmySwe** [comment]
Yes it seems to be a bug... Solved this in branchissue/224.

**Comment by csteinlehner** [comment]
will this be merged in the near future?

**Comment by grimmySwe** [comment]
Solved by #224, closing
