### ISSUE TITLE
Cannot `git subrepo clone` a repository with a .gitignore that ignores dotfiles

### ISSUE THREAD

**Issue by moritz** [ingydotnet/git-subrepo#225]
A

```
git subrepo clone -f git@github.com/p6-css/perl6-CSS-Grammar.git somepath
```

Fails with

```
git-subrepo: Command failed: 'git add p6-css/perl6-CSS-Grammar/.gitrepo'.
```

The reason appears to be the .gitingore file in the repo I'm trying to clone, which has the rule `.*` to ignore all dot files -- including the .gitrepo file.

Expected behavior: being able to clone arbitrary repos as subrepos :-)

**Comment by grimmySwe** [comment]
There might be a solution to this in #160, but that's not on master yet.

**Comment by moritz** [comment]
Is anybody working on this? Unfortunately, this makes git-subrepo unusable for me right now, since I have no control over the repos I want to use as subrepos.

**Comment by grimmySwe** [comment]
Hi, sorry for not responding sooner.

First, your command at the top doesn't work, you need to replace one of the slashes with a colon:
```
git subrepo clone -f git@github.com:p6-css/perl6-CSS-Grammar.git somepath
```

Can you test using the `issue/216-B` branch? I tested it locally and there I can perform the clone just fine.

**Comment by moritz** [comment]
Hi @grimmySwe,

it works for me with the issue/216-B branch. Thank you very kindly.

Cheers,
Moritz

**Comment by moritz** [comment]
Uhm, has the branch been merged? It looks like #216 is still open...

**Comment by grimmySwe** [comment]
True, I was a little quick on the trigger. Reopening. Will leave it open until. it hits master.

**Comment by grimmySwe** [comment]
Fix for this has reached master.
