### ISSUE TITLE
subrepo clone and pull works, but show subrepo says "local out of date"

### ISSUE THREAD

**Issue by farazhussain** [ingydotnet/git-subrepo#228]
Hi,

[Using Ubuntu 16.04, git 2.7.4, git subrepo 0.3.0.]

I successfully cloned a remote into a local subdirectory as a subrepo and am easily able to pull from the remote whenever there are changes to it. 

However, I have problems when I inspecting the remote (emphasis mine). 

$ git remote show subrepo/subdirname 
*remote subrepo/subdirname
  Fetch URL: git@bitbucket.org:myusername/myremoterepo.git
  Push  URL: git@bitbucket.org:myusername/myremoterepo.git
  HEAD branch: master
  Remote branch:
    master new (next fetch will store in remotes/subrepo/subdirname)
  Local ref configured for 'git push':
    master pushes to master **(local out of date)**

Why is it saying that the local is out of date?  I checked using git log (in this repo and the remote) that its not out of date. Also, the following interaction verifies that everything is up-to-date.

$ git subrepo pull subdirname
Subrepo 'subdirname' is up to date.

Thanks.

**Comment by grimmySwe** [comment]
'git remote' is not aware of git subrepo so it has no chance of determining if the subrepo is up to date.

**Comment by farazhussain** [comment]
Ah, thank you!   

'git subrepo status --fetch' seems gives me what I need -- the upstream ref and the pulled commit.

**Comment by grimmySwe** [comment]
Good, closing this.
