### ISSUE TITLE
File change during subrepo push causes problem

### ISSUE THREAD

**Issue by jpadvo** [ingydotnet/git-subrepo#23]
Hey @ingydotnet, I'm still around, just starting to use this day-to-day. :)

I'm using this to manage custom packages in a meteor app. When the app is running, if I attempt a `git subrepo push`, after the `subrepo/prefix` branch is created, meteor writes some temp files, which causes the `git checkout master` to fail. So then it becomes stranded on the `subrepo/prefix` branch.

Not data corruption or anything, but also could fail more gracefully.

**Comment by ingydotnet** [comment]
@jpadvo Greetings!

I just did a major rewrite on the `remix` branch. I'd be very appreciative if
you could try the same tasks using the new code. I want to get it to master in
the next day or so.

Read the docs. Things have changed quite a bit, and for the simpler. See
issue #30 for info.

**Comment by grimmySwe** [comment]
Closing this issue due to age, if you disagree please reopen and test this with latest master.
