### ISSUE TITLE
`git subrepo clone <repository> .<subdir>` (subrepo clone in dot subdirectory) fails

### ISSUE THREAD

**Issue by MunifTanjim** [ingydotnet/git-subrepo#232]
If _https://github.com/example/remote_ is the remote repository and we want to add it in _.remote_ subdirectory as subrepo:

`git subrepo clone https://github.com/example/remote .remote`

It throws the following error:

`git-subrepo: Command failed: 'git remote add subrepo/.remote https://github.com/example/remote'.`

**Comment by gzm55** [comment]
see pr #231 or issue #147

**Comment by grimmySwe** [comment]
Should be solved with #231, @MunifTanjim please let us know otherwise!
