### ISSUE TITLE
Incomplete instructions for manual installation

### ISSUE THREAD

**Issue by thomaslevesque** [ingydotnet/git-subrepo#236]
Because I'm on Windows and using [posh-git](https://github.com/dahlbyk/posh-git), I had to use the manual installation instructions, but I kept getting an error about "bash+.bash". Following the same instructions in bash (still on Windows) gave the same result. Apparently it's not enough to set the PATH environment variable, GIT_SUBREPO_ROOT has to be set as well.

**Comment by ingydotnet** [comment]
Applied #237 which fixes this. Closed. Thanks!
