### ISSUE TITLE
when git-subrepo'ing a github fork, how to keep the fork in sync with its upstream?

### ISSUE THREAD

**Issue by vchudnov-g** [ingydotnet/git-subrepo#240]
Suppose there's a github repo `knife` which I forked into a github repo `knife-fork`

In my own local repo, I set up a subrepo of `knife-fork`. I make a change `A` and I `git subrepo push` it to github's `knife-fork`. I create a pull request which is then accepted and merged into `knife`. However, at this point github's `knife-fork` still thinks it is not in the same state as `knife`. How can I use git subrepo to sync `knife-fork` with its upstream `knife`? The [standard way to do it](https://help.github.com/articles/syncing-a-fork/) would have me git clone `knife-fork` into a new local directory and fetch and merge the upstream from there, but that defeats the purpose of using git-subrepo.

The reason this is a problem is that if I want to make a subsequent change `B` to `knife-fork`, the pull request I generate includes both `A` (which is already merged) and `B`.

**Comment by grimmySwe** [comment]
git-subrepo doesn't handle the internals for working within a fork and it's origin. On the same level that you perform the pull-request from knife-fork you will need to perform the syncing of your fork there as well.

I don't really see how this could be possible, but please come with workflow suggestions if you have any!
