### ISSUE TITLE
git subrepo pull --all fails the rebase --onto

### ISSUE THREAD

**Issue by johan-smits** [ingydotnet/git-subrepo#241]
I use git flow for the releases. When I'm on the development branch (working branch) and I do the pull I get this error:
```
$ git subrepo pull --all
$ git-subrepo: Command failed: 'git rebase --onto f8dba7b3dec9f57e364f68fd2bc1beb7cbd267a0_7b34ae1950a6b99008f91f110eaf6fe1ddf509af_2e8f1140bb617ec84404070b610104e091b5f5c6 6555f12c329655dc015feda008a1e391fe367f66 subrepo/engines/generic_app'.
```

I have to do a force clone somehow.  What information do you need to do a check?

**Comment by grimmySwe** [comment]
@johan-smits what version are you using? Adding -vd to the subrepo command would increase the output.

You can try out branch `issue/216-B` of git-subrepo and see if it solves your problems. It's the base for our next 0.4.0 release.

**Comment by johan-smits** [comment]
Yes this works for me. When will the 0.4.0 release will be available?

**Comment by grimmySwe** [comment]
I will have to forward that question to @ingydotnet who is currently working on getting it ready for release.

**Comment by schiorean** [comment]
This happened to us too... When is the official release supposed to be out?

**Comment by grimmySwe** [comment]
Fix for this has reached master.
