### ISSUE TITLE
OS X ./share/enable-completion.sh: No such file or directory

### ISSUE THREAD

**Issue by Olgagr** [ingydotnet/git-subrepo#245]
I cloned the git-subrepo, I added ```source "$HOME/Projects/git-subrepo/.rc"``` to my .bash_profile but when I restart the bash I get:

```
-bash: /Users/apple/Projects/git-subrepo
Saving session...
...copying shared history...
...saving history...
...completed./share/enable-completion.sh: No such file or directory
```
and of course:

```git subrepo``` commands are not recognizable. 

OS version: 10.11.6

**Comment by Olgagr** [comment]
Problem solved. subrepo command was after rvm loading and this causes problems. Basically, in my .bash_profile I had:

```
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
source "$HOME/Projects/git-subrepo/.rc"
``` 

Reverting the order of these two lines resolved problem.

**Comment by faeb187** [comment]
@Olgagr Unfortunately I have the same problem, and for me the order of the entries doesn't change anything.
