### ISSUE TITLE
git subrepo push fails with unstaged/uncommited changes in other subrepos

### ISSUE THREAD

**Issue by dkebler** [ingydotnet/git-subrepo#247]
before I moan need to say, this project is great. So much potential

One thing about workflow is that subrepo is not allowing me to commit and push changes to files/folder in some subrepo if there are any unstaged, or working tree changes anywhere else in the repo.  This is forcing me to stage/commit things in progress only because I need to push a particular subrepo.  

I need to get a particular subrepo's commits pushed because it's a dependency for other subrepos in the same main repo.

I don't know if this is some constraint of git or the way subrepos are organized but it's a significant detriment to keeping some kind of rational number of relevant commits, beside being irritating to commit unrelated changes just to have my dependency up to date.

```
git-subrepo: Can't push subrepo. Unstaged changes.
git-subrepo: Can't push subrepo. Working tree has changes.
```

**Comment by grimmySwe** [comment]
@dkebler thanks for your praise!

When you perform git-subrepo operations it will use the current repo as playground, checking out the subrepo and performing operations. We don't want to lose things so that's why we require a clean tree before you perform the subrepo operations.

In #150 there has been some discussions on using a temporary directory for the subrepo operations. We haven't put a lot of work there yet as we still work on getting the basics in place.

**Comment by dkebler** [comment]
Any more progress this direction?   Despite it's drawback submodule doesn't have this issue.  What is it about submodules and they way they are managed that doesn't create this issue.  For a few other new projects I've resorted sadly back to submodules on this issue alone.

**Comment by grimmySwe** [comment]
@dkebler We now have an implementation of #150 in tests, I haven't looked into this particular angle yet but I am going to.

**Comment by FrankReh** [comment]
An old issue by now but if someone runs into it like I did and somehow is as naive about git stash as I was. I found a reasonable workaround for my workflow when my goal was to clone a new repo using _git subrepo clone_ while I had uncommitted work in my tree.

I git stashed (_git stash_). Then ran the subrepo command, and then unstashed (_git stash pop --index_).

**Comment by dbux** [comment]
I encountered this error almost immediately and have no idea how to clear it. I have no unstaged changes and the command still fails after running `git stash`

**Comment by admorgan** [comment]
Any possibility of packaging up your repo so I can investigate?

**Comment by dbux** [comment]
I'm afraid I've already purged / refreshed the repo and it's no longer a problem, but if it crops up again I'd be happy to help
