### ISSUE TITLE
Add warning when combining arguments --branch and --all in subrepo pull

### ISSUE THREAD

**Issue by TinyTheBrontosaurus** [ingydotnet/git-subrepo#253]
I have three subrepos (I'm calling them zords) I am tracking from a main repo (calling megazord). All the zords have the same branch names (`master` and `foo`). In my scenario, I want to change the tracking branches all the zords on megazord to `foo`. I tried to following command  

    git subrepo pull --branch=foo --all

which gave this output

    Subrepo 'the_zords/zord1' pulled from '../zord1' (master).
    Subrepo 'the_zords/zord2' pulled from '../zord2' (master).
    Subrepo 'the_zords/zord3' pulled from '../zord3' (master).

However, when I run these three commands separately, it does what I want.

    git subrepo pull --branch=foo the_zords/zord1
    Subrepo 'the_zords/zord1' pulled from '../zord1' (foo).

    git subrepo pull --branch=foo the_zords/zord2
    Subrepo 'the_zords/zord1' pulled from '../zord2' (foo).

    git subrepo pull --branch=foo the_zords/zord3
    Subrepo 'the_zords/zord1' pulled from '../zord3' (foo).

I assume the problem with the combining `--branch` and `--all` is that `--all` overrides it. That's fine behavior for my case; I don't mind doing all three commands as it's probably safer anyways. All I think is missing is that there should be a warning saying something along the lines of `Argument --branch is being ignored`

**Comment by hever** [comment]
It is be illegal to use `--all` and `--branch` together? Or it is a bug and this should work? (Now it's not work - only with master branch).

**Comment by admorgan** [comment]
I am going to declare that it is illegal to use --all and --branch together. The odds of you doing it on purpose are very low, and the utility is also low. I will add an error message and just return.

**Comment by hever** [comment]
I think it could be legal. But maybe I'm looking to that in a bad way.

Our situation... We have project divided into subrepo. I want to work on some feature, so I will switch to new branch (on master project).

`git checkout -b new-feature`

My work will do the changes in some subrepos. Now I would like to push my changes to branches on subrepos.

`git subrepo push --all -b new feature` (imposible)

My colleague would like to see what I'm work on

```
git checkout -b new-feature
git subrepo push --all -b new feature  # imposible
```

Now I need to study on which subrepos I was doing changes and do the push for every subrepo. And my coleague needs to inspect every of suprepos if i do some changes here. Can please you tell me where is my workflow wrong?

**Comment by admorgan** [comment]
Not wrong, just infrequent. My though process is which is more likely, every repo (I have 100s in my projects) have the same branch name, or that you fequently use --all and added a branch for one repo. Mass changing the following repo seems like a low probability event. This is especially true for hubs that lock down branch creation to a limited group of people.

As the existing code did not support this feature, I felt the obvious path was to at least error out instead of silently doing the wrong thing.

I can be convinced that this is a hit feature that should be implemented. The hard part is how to handle errors that occur since none of the actions are atomic.

**Comment by hever** [comment]
I'll do patch to work --branch together with --all https://github.com/hever/git-subrepo/commits/hever-patch-1 ant tested it by myself for couple months. 

I'm not sure to which branch I have make the push request to.
