### ISSUE TITLE
`git fetch --all` scrumble repositories

### ISSUE THREAD

**Issue by Djabx** [ingydotnet/git-subrepo#257]
I've got a repositories with many remotes, but if I do:

    git fetch --all

To synchronize all my remotes, it also fetch my subrepo tags, witch is really not why I want.
How may I handle this properly (appart from using `git fetch --all`) ?

**Comment by grimmySwe** [comment]
Yes, this is not really what you want.
You can run `git subrepo clean --all`first to remove the remotes.

I will look into if we really need to create this remote in the first case.
Somewhat connected to #258

**Comment by grimmySwe** [comment]
Hi again @ingydotnet, a lot of activity today :-)

I tested a little with removing the `git remote add` inside git-subrepo and it seemed to work ok. Are there something that I don't understand here that they are used for?

**Comment by ingydotnet** [comment]
I think having the remote is important to do things by hand. We could add a git config option (per repo or global) to not make the remotes.

**Comment by grimmySwe** [comment]
I understand that it's good to have when you work "manually", but is that really the preferred way? 

Don't you think that is more of an advanced use and people can then do 'git remote add' by themselves and understand the consequences. So that when you do 'git fetch --all' you never get something unexpected.

**Comment by grimmySwe** [comment]
@ingydotnet Or we add a utility command `git subrepo remote` that helps you add/remove a remote.

But as said, my vote is on not creating the remotes by default as they are not needed for the regular workflow if everything just works (tm).

**Comment by grimmySwe** [comment]
Released in 0.4.0
