### ISSUE TITLE
Cannot clone repo without making at least one commit

### ISSUE THREAD

**Issue by saada** [ingydotnet/git-subrepo#26]
```
$ mkdir x
$ cd x
$ git init
$ git subrepo clone <url> -v
>>> git rev-parse --short HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Error: command failed: git rev-parse --abbrev-ref HEAD
```

If I touch a file and commit it, the clone works just fine. There shouldn't be a requirement of a first commit to use this plugin

**Comment by ingydotnet** [comment]
@saada, Try the new "rewrite" on the 'remix' branch. It's awesome and likely
represents close to how this command will stay.

It doesn't fix this issue, but I'm still interested in doing that once I get
this new major version to master.
