### ISSUE TITLE
Can I configure multiple subrepos in a config file?

### ISSUE THREAD

**Issue by dbolser** [ingydotnet/git-subrepo#260]
Or would this effectively be a bash script?

(Sorry, noob).

**Comment by grimmySwe** [comment]
Could you please give a little more information on this question and maybe an example?

You can add as many subrepos as you want in a "main" repo. Each subrepo will have it's own configuration stored in .gitrepo file.

**Comment by dbolser** [comment]
I'm looking for a simpler replacement for this:
https://github.com/Ensembl/ensembl-git-tools

which pulls in a bunch of repos (each set with a specific tag), and sets them all to a common branch.

**Comment by grimmySwe** [comment]
If I understand correctly you would simply create a main repo and then for each repo in the "bunch of repos" you create a subrepo in the main repo. Then you can handle them efficiently and there are tools to change branch and update all of the repos with _-all_.

Was that an answer to your question?

**Comment by dbolser** [comment]
Thanks, yes, I think it was.
