### ISSUE TITLE
git subrepo pull always creates commit

### ISSUE THREAD

**Issue by Wagner59** [ingydotnet/git-subrepo#263]
I have simple setup as shown in tutorial and when I do 'git subrepo pull <subrepo_name>' it always says 'Subrepo ... pulled from ...' and creates new commit even though no new commit in the subrepo was created.
In your code I have found 
`if [[ $upstream_head_commit == $subrepo_commit ]] &&
     [[ -z $subrepo_branch ]]; then
    OK=false; CODE=-1; return
  fi`
so not sure when the second part of the condition is true.

Is it a bug or feature?

**Comment by grimmySwe** [comment]
Yes, it's a bug. Its solved in https://github.com/ingydotnet/git-subrepo/commit/e37942ccf36dd3101fc78094881701be9f374a33

What version are you using?

**Comment by Wagner59** [comment]
I am on master with revision a7ee886e0260e847dea6240eaa6278fb2f23be8a. Seems like the most recent one

**Comment by grimmySwe** [comment]
@Wagner59 We are working on it, unfortunately life puts other task in the way sometimes.

You can test and use branch issue/216 were this fix is included.

**Comment by marco-m** [comment]
Hello, thanks for git-subrepo, I like it! :-) any news on merging issue/216 ?

**Comment by farazhussain** [comment]
I had noticed this too months ago and finally would have created an issue about it today.  Glad to see it was already identified  & fixed.

**Comment by Fonata** [comment]
I started playing with `git subrepo` today and found the behavior described above still to be present in today's master (which is commit `a7ee886`): calling `git subrepo pull` several times without anything happening to any repository creates one new commit for each call. 

I expected it to say `Already up-to-date.`

**Comment by grimmySwe** [comment]
@Fonata Hi, there has been some delays with actually getting the latest stuff to master, so please check out release/0.4.0 branch and see if it works as you expect?

**Comment by grimmySwe** [comment]
Fix for this has reached master.
