### ISSUE TITLE
Can't find a common ancestor between refs

### ISSUE THREAD

**Issue by Chren** [ingydotnet/git-subrepo#266]
Hi, when run git subrepo pull , an error occurs:

`Can't find a common ancestor between refs/subrepo/lollypop-client-ios/git-subrepo/common/control/lollypop-client-ios-business-social/fetch and subrepo/lollypop-client-ios/git-subrepo/common/control/lollypop-client-ios-business-social. This might be the case if someone used push --force on the subrepo. You need to find out why and possibly reclone the subrepo`

I even remove this subrepo and run git subrepo clear, then reclone it, but when run git subrepo, the error remains, any solution?

**Comment by Chren** [comment]
Never mind, switch to tag 216-1 just fix my issue,  so I guess it is a bug in 0.3.1?

**Comment by grimmySwe** [comment]
@Chren yes, there are some known issues with 0.3.1.

**Comment by nmaludy** [comment]
I'm having this same issue, but when i try using `tags/216-1` i get the following error:

```
git-subrepo: Command failed: 'git rebase --onto 98f14ca8dcb9458fc3558ab6626c75faff7b074b e00812b01e3c73d6b0439763dcc1eef9188d0d17_09b4bde34b35eac65ada978555e24e89c3e903db_afe078c7e2160747f7725e984b447146da09cebc subrepo-push/lib/py-menandmice'.
```

**Comment by grimmySwe** [comment]
@nmaludy Are you sure about the version you are running tags/216-1, the output looks like the old one for 0.3.1 functionality. Could you please double check?

**Comment by grimmySwe** [comment]
Fix for this has reached master.
