### ISSUE TITLE
How to force pull to overwrite merge conflicts?

### ISSUE THREAD

**Issue by Henry-E** [ingydotnet/git-subrepo#276]
The recommended approach to this on [stackoverflow](https://stackoverflow.com/a/8888015/4507677) is

>  ` git fetch --all`
> Then, you have two options:
> 
> `git reset --hard origin/master`
> OR If you are on some other branch:
> 
> `git reset --hard origin/<branch_name>
`

I can `git subrepo fetch --all` but I don't really know how to do git subrepo reset? There's too many merge conflicts to edit by hand even though the conflicts don't appear to caused by my own changes to the repo.

**Comment by grimmySwe** [comment]
If you by force pull means that you want the exact state of the remote subrepo, you can always do a reclone. `git subrepo clone -f <subdir>`, that would overwrite the <subdir> with current state of the subrepo.

**Comment by Henry-E** [comment]
No I'd like to be lazy and overwrite all the merge conflicts automatically. I have my own changes inside the repo which I'd like to keep. Up until now they've not caused any merge conflicts. These merge conflicts appear to be caused by the repo maintainer's own changes.

**Comment by grimmySwe** [comment]
What version of git-subrepo are you using?

If you run issue/216 based the regular merge should be able to cope with this and when you get conflicts you can do a 
```
git checkout --ours .
git add .
git commit
```
And after that you should be able to 
```
git subrepo commit <subdir>
```

**Comment by Henry-E** [comment]
I'm using version 0.3.1. Unfortunately that particular set of commands didn't seem to work. After running 
```
git checkout --ours . 
git add .
```
 It seems to remove all the unmerged paths and bunch of other things go missing.

**Comment by grimmySwe** [comment]
0.3.1 uses rebase by default and that is a little different.
When you get the conflict you can do this:
```
git checkout --theirs .
git add .
git rebase --continue
```

Rebase uses ours/theirs the opposite way. And you will have to do this for each rebase "conflict".

Would that work?

**Comment by Henry-E** [comment]
Yep that worked perfectly. I'll have to look into what `ours` and `theirs` are doing. Git is an unwieldy master I have yet to get my head around. Thanks very much for your help.
