### ISSUE TITLE
Reconcile/merge relevant commits from `issue/216`.

### ISSUE THREAD

**Issue by ingydotnet** [ingydotnet/git-subrepo#281]
Same process as #279.

**Comment by grimmySwe** [comment]
Found nothing new from this branch.

**Comment by marco-m** [comment]
Hello, any news ?

**Comment by ingydotnet** [comment]
@grimmySwe taking a little time now to catch up. Looks like I can close this one.

**Comment by marco-m** [comment]
Thanks! git-subrepo is keeping our sanity with a reasonable history (as opposed to git subtrees) ❤️
