### ISSUE TITLE
Reconcile/merge relevant commits from `master`

### ISSUE THREAD

**Issue by ingydotnet** [ingydotnet/git-subrepo#282]
Same process as #279.

@grimmySwe, you should probably do #281 first, but up to you.

**Comment by grimmySwe** [comment]
@ingydotnet I have created a new branch release/0.4.0_rebased_to_master from release/0.4.0 and rebased it with master. I think it worked out ok. There was some minor encoding issues that I had to solve but now everything should pass all the tests.

I didn't want to move the release/0.4.0 to it without your blessing :-)

**Comment by ingydotnet** [comment]
I'll review soon and get back to you with next steps.

**Comment by grimmySwe** [comment]
@ingydotnet Any progress? I'll have this week as well, then I am on vacation and it might be a little less progress from my part.

**Comment by ingydotnet** [comment]
@grimmySwe the changes look right. Are you saying that the  `release/0.4.0_rebased_to_master ` should be force pushed to `release/0.4.0`?

If so, you have my blessing. GO ahead and do that, then close this issue and move the task to Done in https://github.com/ingydotnet/git-subrepo/projects/1

Do you think any of the remaining Tasks (besides my review) need to be done before we do the 0.4.0 release? If so, just do them. Let me know what you think, either way.

Cheers!

**Comment by grimmySwe** [comment]
I have now forced pushed release/0.4.0 including release/0.4.0_rebased_to_master and also the issue/150_to_master.

**Comment by ingydotnet** [comment]
@grimmySwe I'm getting test failures on these 2:
```
prove -v test/branch.t test/pull-ours.t
```

**Comment by grimmySwe** [comment]
@ingydotnet Travis CI works with the tests and I got nothing locally, I will check if I can reproduce at work tomorrow.

**Comment by ingydotnet** [comment]
https://gist.github.com/anonymous/b4ceadaf5eba7bdf70e99bdde7e4c433

Might be specific to my mac. Will investigate.

**Comment by ingydotnet** [comment]
Yeah. Works fine on Linux. Will try to fix the Mac bugs.

**Comment by ingydotnet** [comment]
Fixed mac bug. The `stat` command output looks like this on OS X:
```
16777220 12627255 -rw-r--r-- 1 ingy staff 0 1209 "Aug 16 21:42:11 2017" "Aug 16 21:42:11 2017" "Aug 16 21:42:11 2017" "Aug 16 21:42:11 2017" 4096 8 0 Changes
```

See 204d4aa
