### ISSUE TITLE
Subrepo push gone wild

### ISSUE THREAD

**Issue by brunoleos** [ingydotnet/git-subrepo#288]
I've just gone through a bad subrepo push.

The history was (I guarantee no upstream changes happened):
$ git subrepo clone repo_shared subdir -b feature_branch
$ git commit ...
$ git subrepo status
Git subrepo 'subdir':
  Remote Name:     subrepo/subdir
  Remote URL:      git@...
  Upstream Ref:    7331db4
  Tracking Branch: feature_branch
  Pulled Commit:   7331db4
  Pull Parent:     a3a4d0a
$ git subrepo push repo_shared
git-subrepo: Command failed: 'git reset --hard fabdbafebdb2a273281701ef4865c98b863fecc7'.

And then I got a fully messed branch, and other temp subrepo branches, which was rebased in a much older ref than expected. 

As I thought it was because I was pushing with no -b, I've reset my working copy to before the subrepo push and did it again with -b feature_branch.

That went OK.

I got afraid, as it was a single mistake and a scary result. Was that the expected behaviour or a bug? Should the push go by default to the branch from where I cloned, for safety?

**Comment by grimmySwe** [comment]
As stated with git subrepo status:
Tracking Branch: feature_branch

You should not need -b for the push operation, it should work against the correct branch.

What verison of subrepo are you using?

**Comment by brunoleos** [comment]
The version is:
$ git subrepo --version
0.3.1

**Comment by grimmySwe** [comment]
You can use -vb flags to push for more verbose output. There are unfortunately some problems with 0.3.X version, we are working on solving them but it's not on master yet.

**Comment by grimmySwe** [comment]
0.4.0 reached master.
