### ISSUE TITLE
In the FAQ, what is the difference between the first two approaches?

### ISSUE THREAD

**Issue by sqrt** [ingydotnet/git-subrepo#292]
I tried to follow the advice in the first FAQ, but I don't see a difference between the two approaches:

    $ cd <old-project>
    $ git subrepo init <subdir1> -r <remote> [-b <branch>]
    $ git subrepo push <subdir1>
    $ git branch
    * master
      subrepo/<subdir>

Which is exactly the same as in the second approach (except for the remote):

    $ cd <old-project>
    $ git subrepo init <subdir2>
    $ git subrepo branch <subdir2>
    git-subrepo: Branch 'subrepo/subdir2' already exists. Use '--force' to override.
    $ git branch
    * master
      subrepo/<subdir1>
      subrepo/<subdir2>

 Both approaches create a branch. Is that what's supposed to happen? What's the difference between these two?

**Comment by grimmySwe** [comment]
@sqrt I think the main difference is that in the first case you have the subrepo in a separate repository, in the second case you use the subrepo in the old-project repository and then clone from there.

I haven't written anything in the FAQ so we should check with @AndrewSmart .

Personally I would say that the second approach might be fragile as the temporary branches in the old-project is just temporary.

**Comment by AndrewSmart** [comment]
> @sqrt I think the main difference is that in the first case you have the subrepo in a separate repository, in the second case you use the subrepo in the old-project repository and then clone from there.
Correct. There are no other differences.

I'll mark bold #1 & #2 in that FAQ entry.
