### ISSUE TITLE
git subrepo deinit/rm/delete/remove ?

### ISSUE THREAD

**Issue by mwithheld** [ingydotnet/git-subrepo#294]
How do I remove a subrepo that's already pushed to the parent?  

Should there be a 
git subrepo deinit/rm/delete/remove
command?

**Comment by grimmySwe** [comment]
@mwithheld The only thing that connects the subrepo with the parent is the .gitrepo file in the subrepo. And it's you that decide when you sync it, so if you want to get rid of the entire directory, just remove it in the parent repo, if you just want to disconnect it, remove the .gitrepo file.

**Comment by mwithheld** [comment]
Super - thanks!

**Comment by varac** [comment]
Well, removing the subrepo directory is *not* everything you need to do - since subrepo configures a git remote and you need to remove this as well.
I'd love if complete removal could be covered by a dedicated command.
