### ISSUE TITLE
Not documented/obvious how to migrate from git subtree

### ISSUE THREAD

**Issue by kentfredric** [ingydotnet/git-subrepo#3]
In cases you have existing projects with `git subtree`, its not plainly obvious how to migrate to `git subrepo`.

```bash
$ git subrepo clone https://github.com/kentfredric/travis-scripts.git maint-travis-ci/
# Error: subdir 'maint-travis-ci/' exists and is not empty
```

**Comment by ingydotnet** [comment]
With the latest code we can:

    git clone -f $url $subdir

I haven't tested that but I will.

We should write a migration doc and maybe a `migrate` subcommand. Especially
from submodule.

**Comment by erlandsona** [comment]
Please please please :+1:

**Comment by ingydotnet** [comment]
Closing this. Covered in #60
