### ISSUE TITLE
Reimplement `pull` in terms of other new subrepo commands

### ISSUE THREAD

**Issue by ingydotnet** [ingydotnet/git-subrepo#30]
In my experience, pull is too fragile and confusing.

I'd like to reimplement it made out of these:

    git subrepo checkout <subdir>
    git subrepo merge
    git subrepo commit

And when the merge fails, tell the user to:

    git subrepo checkout <subdir>
    # hand merge/rebase/cherrypick/whatever and commit
    git subrepo commit

The `checkout` command will:

* `git subrepo fetch <subdir>` # Fetch the subrepo's upstream
* Create `refs/subrepo/remote/<subdir>` → FETCH_HEAD
* `filter-branch` the subdir commits
* Create a branch `subrepo/<subdir>` → subdir history
* `git checkout subrepo/<subdir>`

The `merge` command can try simple merges of the subrepo branch and the
upstream head, but it should reset on failure, and tell the user to hand
merge.

The `commit` command is new. it takes the tree object of the successfully
merged subrepo branch, creates a new commit with no parents, appends on the
`.gitrepo` file, and attaches itself to the top of the mainline branch.

So when you are all done you just have a single new non-merge commit that
represents the pulled subrepo content.

I think we can ditch the `--continue` option. I really like the idea of having
more simple git-like subcommands that just do specific things.

Since a `subrepo push` should really just be a `subrepo pull` and a normal
`push` to the subrepo's remote, I think this should be everything.

@AndrewSmart, @kentfredric: Please review and comment. Also discuss on
irc.freenode.net#git-commands.

Other related changes I'd like:

* `git subrepo status` within a subrepo branch
* `git subrepo log <subdir>` show real commit log for subrepo
* `git subrepo reset` reset and checkout mainline branch

I'll start doing the new work on the `push-commands` branch. Feel free to
test, contribute and complain.

**Comment by ingydotnet** [comment]
I started by rewriting the doc the way I think it should work. More or less.

Please review @AndrewSmart.

**Comment by ingydotnet** [comment]
Forgot the new doc url:

https://github.com/ingydotnet/git-subrepo/blob/push-commands/ReadMe.pod

**Comment by AndrewSmart** [comment]
Agreed the current pull is fragile when things conflict.

I do like the design change of "having a single new non-merge commit that
represents the pulled subrepo content." It simplifies the graph, and I hope it works!

I am concerned on how later resolution (during later pulls/pushes) will work. Things should be done in such a way that the author won't have to repetitively resolve things they had already resolved.

Other thoughts on the first bit:
```
git subrepo checkout <subdir>
git subrepo merge #or hand merge/rebase/cherrypick/whatever and commit
git subrepo commit
```

The **`git subrepo commit`**, can be written with calls to git-mktree and git-commit-tree. I have the algorithm in my head:
  1. git-mktree on the resultant `subrepo/<subdir>` branch with the .gitrepo file added to the output of git-ls-tree. i.e. `echo "'git-ls-tree subrepo/<subdir>'\n100644 blob <hash-of-.gitrepo>\t.gitrepo" | git-mktree`
    * This way we're adding both the merge result and the .gitrepo file into one commit on $original_head_branch.
  2. Recursively git-mktree git-ls-tree from `<subdir>` up to the root, propagating the modified <subdir>'s effect on the hashes.
  3. Call `git-commit-tree -p "$original_head_branch" <result>`.

**Comment by ingydotnet** [comment]
@AndrewSmart, I have finished the near complete refactoring.

It is all on the `remix` branch. I will leave it there until you have a chance
to test and review.

Some highlights:

* Added `branch` and `commit` commands
* Removed `checkout` commands
* Pull is now just a set of 5 commands you can do by hand
  * Works well for manual rebase when there are conflicts
* Removed all the merge strategy junk. No needed.
* clone and push are single commit. No merge.
* Everything is simpler over all.
* Lots more tests
  * All passing
* `--verbose` lists out steps on most commands
  * indentation for subcommands
* `--debug` shows actual Git commands used
* Removed grafting silliness
* Doc is all up to date

I'm really excited about how it turned out. Along the way I took out the
heuristic routines you added, because I'm not sure if they are needed now. If
they are we can add them back (with tests).

Find me on IRC tomorrow. I'll be up early.

Look forward to get this out to the masses!

**Comment by AndrewSmart** [comment]
Woot! K I'm on now.  I'll try to break it :-)

Noticed you used a different way of implementing `git subrepo commit` with less lines of code. Might be interesting to look at any resource consumption difference between the two techniques with a 1K file subrepo. Your technique is easier to read/comprehend so I won't worry for now.

I'm on IRC now. I'll have more comments once I look through things.

Yes the routines I added won't be useful in this context. They were useful before due to involvement of the .gitrepo file in one branch of a merge (the porcelain commands would be unable to find a good candidate ancestor: http://git-scm.com/docs/git-merge-base). With your new technique neither branch has the .gitrepo during a merge, so the porcelain commands work appropriately.

At first glance the `git rebase refs/subrepo/share/upstream subrepo/share` syntax looks a bit more complex than I expected.

**Comment by ingydotnet** [comment]
* `git subrepo branch` makes the `subrepo/share` branch.
* `git subrepo fetch` makes a `refs/subrepo/share/upstream` ref. this ref can also be addressed as 'subrepo/share/upstream` in commands.

The branch thing is the set of subrepo commits teased out of master since the last pull (or clone).

If there are none, the branch has to fail (I think). Can you have a branch with no commits? I doubt that. In that case I do pull a little differently.

A git rebase wants exactly these 2 things. The upstrem head, and the new commits. I studied the rebase manpage very carefully finally. It happends to fit subrepo perfectly (well at least the way I've done it).

Your `test/failing/test.t` has already exposed some weaknesses, but I have solutions to talk about.

**Comment by ingydotnet** [comment]
* Make `git subrepo push` require an explicit branch *or* create a it creates new branch
  * `git subrepo push <subdir>`
    * create a temporary branch like `subrepo-push/<subdir>`
    * fetch upstream
    * rebase & commit
    * push
    * remove temp branch and fetch head
  * `git subrepo push <subdir> <branch>`
    * Assume branch is ready to push
    * push it
  * If rebase fails in first form, tell user to do these:
    * Fix conflicts
    * `git subrepo push <subdir> `subrepo-push/<subdir>`
    * `git branch -D `subrepo-push/<subdir>`
      * Or `git subrepo clean <subdir>`
* Let a pull/rebase fail just leave things in conflict
  * ie Don't roll back, just exit with help message
* Add back `subrepo reset` (helper command) to get out of rebase cleanly
* `git subrepo clean` should print removed things by default
* Add --all back into push and pull

**Comment by ingydotnet** [comment]
@AndrewSmart, I'm all done with the commits that I feel are essential for the
remix branch to get back to master. I still would like your OK.

I have over a dozen notes for things I want to change. I'll make each of those
into an issue so that we can discuss them individually.

I'll be online same time tomorrow morning. Cheers.

**Comment by ingydotnet** [comment]
All tests passing on OSX now. There were a couple weirdnesses, but I fixed
them.

I'm ready to 'master' this remix. I'm going to use it on a few of my real repos
with subrepos. If all goes well, I'll pull the trigger.

@AndrewSmart, did you find anything out in testing?

**Comment by AndrewSmart** [comment]
@ingydotnet Everything looks great so far, you have my OK
I made a new pull request to fix an issue; maybe pull that beforehand.
I'll look over the issues you mentioned.

**Comment by ingydotnet** [comment]
93 commits later, the remix branch is back in master.
