### ISSUE TITLE
push --dry-run actually pushes

### ISSUE THREAD

**Issue by bryanlarsen** [ingydotnet/git-subrepo#300]
We're using f4b2c2fd7e5b35909eac99315421f6b8f924c3d8, currently release/0.4.0

I did a `git subrepo push -v --all --dry-run`, but it seems to have ignored my --dry-run flag because it actually pushed.

**Comment by grimmySwe** [comment]
@bryanlarsen Sorry about that, I think that we added the flag during design stage but never got to implement the functionality behind it.

I will look into it and see if I can fix that.

**Comment by bryanlarsen** [comment]
At least for me, I don't necessarily need a dry-run, I was planning on using it as a more intelligent status command, to tell me which subrepos are out of date.   I don't really care how I get that info.   Thanks!

**Comment by grimmySwe** [comment]
Ok, removed the --dry-run flag for now. It is a little bit tricky to implement so we save it for later. (#274)

**Comment by grimmySwe** [comment]
@ingydotnet Disabled this for now, doing only partial operation can be tricky as the subrepo push actually pushes remote, updates .gitrepo and commits it locally.

**Comment by grimmySwe** [comment]
Released in 0.4.0
