### ISSUE TITLE
init gives "Failed to get subrepo content from 'my/dir'" error

### ISSUE THREAD

**Issue by matthewtoast** [ingydotnet/git-subrepo#302]
I have a project with several directories that I want to convert to subrepos. I ran `git-subrepo init` on all of them, and it worked like a charm -- except on one. For that one, `git-subrepo init` failed, giving me the following error:

```
git-subrepo: Failed to get subrepo content from 'my/dir'.
```

I don't see anything obviously unusual happening in 'my/dir'. Is there something I can do to gain more insight into why this command might be failing, or how I could resolve this?

git version 2.4.6
git subrepo version 0.3.1
maOS Sierra

**Comment by matthewtoast** [comment]
Digging into the source a bit, I can see that the failure occurs here:

```
git filter-branch -f --subdirectory-filter "my/dir" HEAD
```

The underlying error message being:

```
Rewrite abc123 (5/343)def456
fatal: failed to unpack tree object abc123
Could not initialize the index
```

**Comment by matthewtoast** [comment]
As a possible workaround, I found that I was able to go into `/path/to/git-subrepo/lib/git-subrepo` and edit L474:

```
--subdirectory-filter "$subdir" \ # <~~ original line
--subdirectory-filter "$subdir/" \ # <~~ my change; note the trailing forward slash
```

After that, I was able to run `git-subrepo init my/dir` successfully. I am not certain why this was necessary strictly for `'my/dir'` and not `'my/other-dir'` and `'my/other-dir2'` etc.

In researching similar problems others have had running filter-branch, it became apparent that adding a trailing slash was often a solution -- but I have no idea why that's the case. (To those trying this workaround, remember to change L474 back afterward.)

Note: I now see an error on my first attempt to run `git-subrepo pull my/dir`, but I'm unsure if that's related, so I'll leave it off of this issue for now.

**Comment by grimmySwe** [comment]
Is "my/dir" actually what you have tested? or is it just a cover for your real names? If so I think it would be useful if you could at least reveal the name that fails and possibly also names that work.

Will look into this and see if I can find anything

Note: Could you test release_0.4.0 branch of git subrepo and see if the error is there as well?

**Comment by matthewtoast** [comment]
Actual directory names that I have run this against:

```
packages/haiku-bytecode // works
packages/haiku-glass // works
packages/haiku-timeline // <~~ This is the only one that causes the error
```

My repo has a long and storied history, including a stint with submodules and a stint with subtrees. My gut tells me something got corrupted in the git objects which is possibly outside of the purview of git-subrepo to handle.

Although, for some good news: I tested these same actions against the `release_0.4.0` branch (after upgrading Git to `2.14.2`), and that seemed to work flawlessly.

**Comment by grimmySwe** [comment]
@matthewtoast Would you be ok with running release_0.4.0?

**Comment by matthewtoast** [comment]
Yes, I'll plan to use release_0.4.0. Thank you for your help.

**Comment by grimmySwe** [comment]
0.4.0 reached master
