### ISSUE TITLE
Question: difference between Upstream Ref and Pulled Commit?

### ISSUE THREAD

**Issue by farazhussain** [ingydotnet/git-subrepo#303]
Hi, here is the output for 'git subrepo status' inside one of my repositores:

Git subrepo 'ext':
  Subrepo Branch:  subrepo/ext
  Remote Name:     subrepo/ext
  Remote URL:      git@bitbucket.org:username/somerepo.git
  **Upstream Ref:    7a1b7d8**
  Tracking Branch: master
  **Pulled Commit:   8d5c9b3**
  Pull Parent:     ed11838

(emphasis mine)

Now, inside somerepo.git, these are the last five commits: 

$> git log -5 --oneline
507c0d6 mnr
1c708cc more
**8d5c9b3 mnr**
0470d18 basic bio
**7a1b7d8 org**

(emphasis mine)

What is the difference between Upstream Ref and Pulled Commit? In this particular case, what is the meaning that they point to two different commits in the subrepo, neither of which is the latest commit?

**Comment by grimmySwe** [comment]
Hi @farazhussain, I think that the original idea is to have the Upstream Ref show the latest fetched commit available, Pulled commit is the latest commit actually pulled into you repo.

But from you output it looks a little strange as you should always have fetched at least the latest pulled commit.

Will look into this and see if I can understand more what is happening.

**Comment by farazhussain** [comment]
Thank you @grimmySwe, that is very helpful.   After 'git subrepo pull ext', here is what I get:

Inside the main repository:

$> git subrepo status:
Git subrepo 'ext':
  Subrepo Branch:  subrepo/ext
  Remote Name:     subrepo/ext
  Remote URL:      git@bitbucket.org:farazhussain/somerepo.git
  Upstream Ref:    507c0d6
  Tracking Branch: master
  Pulled Commit:   507c0d6
  Pull Parent:     c4952d5

From subrepo.git:

$> git log -2 --oneline
507c0d6 mnr
1c708cc more

So now the both the upstream ref and pulled commit point to the latest commit in subrepo. This is as I expected.

**Comment by grimmySwe** [comment]
I can't reproduce the strange behavior with a upstream ref that is behind the pulled commit.
Please let me know if you experience this and now how to reproduce it!
