### ISSUE TITLE
I have a fit version at 2.14.1 and it says I need 2.5 or higher.....

### ISSUE THREAD

**Issue by chrisfair** [ingydotnet/git-subrepo#307]
git-subrepo: Requires git version 2.5 or higher; you have 'git version 2.14.1'.

**Comment by chrisfair** [comment]
The bug is present in commit
d1a3f56711729d72e84e3644a1054a992e624ffe

But not present in
e35b848e74063126e949c816b6fe3231da570643

**Comment by grimmySwe** [comment]
Strange, the actual check is not for version, it's if worktree command is available.

```
if ! git worktree list &> /dev/null; then
    error "Requires git version 2.5 or higher; you have '$git_version'."
fi
```
And that has not changed between the commits.
Could you supply the output adding the -vd flags in both cases?

**Comment by plach79** [comment]
I have the same issue with branch `release/0.4.0`: according to the [manual](https://git-scm.com/docs/git-worktree/2.5.0), the `list` subcommand is not available until version `2.7.0`. So maybe we should change the check to something different?

**Comment by plach79** [comment]
In fact upgrading to git 2.15.0 fixed the issue for me.

**Comment by grimmySwe** [comment]
`git worktree list` is used so I guess I need to bump the requirement to 2.7.0

**Comment by plach79** [comment]
+1 on that, thanks!

However @chrisfair's issue was probably different as he was already on 2.14. Should we keep this open until we hear back from him?

**Comment by ingydotnet** [comment]
I used `git subrepo` from my home directory (which is not a git repo) expecting
to see the help page and I got:
```
git-subrepo: Requires git version 2.7 or higher; you have 'git version 2.7.2'.
```

Running the worktree command to check the version is clever, but wrong since:
```
~ $ git worktree list
fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by grimmySwe** [comment]
Changed to a "regular" version check. I hope this one is clever but right ;-)

**Comment by ingydotnet** [comment]
I just fixed some bugs in this fix. See e0241a9.

This is on the @release/0.4.0 branch and should get back to master this week.

**Comment by grimmySwe** [comment]
Hi @ingydotnet , good to have you back! Your way was even more right.
