### ISSUE TITLE
which branch or tag to use?

### ISSUE THREAD

**Issue by nandbert** [ingydotnet/git-subrepo#320]
Hi guys, which version would you currently recommend to use in a new project? 

0.3.1 ?
release/0.4.0 ?
master ?
some 216 derivate ?

Thx

**Comment by ingydotnet** [comment]
Hi @nandbert,

I'm working on the 0.4.0 release right now and hope to have it out this week.
Hopefully in the next 1-4 days.

It is going to be based off of the release/0.4.0 branch, so using that now
should probably be just fine.

**Comment by kohlhase** [comment]
any news on the release?

**Comment by ingydotnet** [comment]
The `release/0.4.0` branch is now on `master`. Use `master` or the latest release tag.

**Comment by nandbert** [comment]
Thank you Sir!
