### ISSUE TITLE
Multiple subrepos with common base directory

### ISSUE THREAD

**Issue by mklepaczewski** [ingydotnet/git-subrepo#327]
Let's say that I have several libraries all grouped under common namespace and directory:
My_Company/Database/{database related library}
My_Company/Collections/{collections library}
My_Company/Concurrency/{concurrency library}

All libraries have common base directory/directories "My_Company". All libraries are independent from each other and I don't want to couple them. Still, I would like to add some subset of them as subrepositories in my project. What are my options? Of course I could create one additional level of directories for them (so the paths would be similar to libs/db/My_Company/Database/[...], libs/collections/My_Company/Collections/[...]) but it's ugly and makes some things harder (for example class autoloading).

**Comment by grimmySwe** [comment]
If I understand you correctly you can "reuse" the same name several times on different places.
So if you have a Database library in a repo called My_Company/Database, you can put it in libs/db/My_Company, another Collection library in a repo called My_Company/Collections you can have that in libs/collections/My_Company.

When you perform the subrepo operations you will use libs/db/My_Company as the key.

Something like this to clone it:
`git subrepo clone My_Company/Database libs/db/My_Company`

Was that answer to your question?

**Comment by mklepaczewski** [comment]
I guess I should refine my question: is it possible to checkout multiple subrepositories to the same directory? I assume the answer is "no". In that case - would it be feasible to add this feature in future release?

Regarding the solution you suggested: unless I miss something that's exactly the solution I mentioned. While it does solve the problem it has its share of drawbacks:

- it means that (to some extent) location of libraries in project is not dictated by me or the framework I use but by git subrepo,
- some features that assume certain directory structure might not work. Take PHP autoloading for example, it's common to use base "libraries"/"vendor" directory, namespace and class name to construct path to a file to be loaded. If I add additional directory to the path autoloading might break.

Another solution would be to clone subrepositories as suggested and use symlinks + .gitignore to create the desired directory structure. However, the application might break if symlinks are used, software like web server might be configured to ignore symlinks for security reasons, IDEs might be confused when faced with symlinks etc. Hardlinks don't work with directories on Linux and Windows. Junction points and mount --bind might do the trick but require root level privileges. This workaround would also require setting up additional hook after clone/checkout to make things portable between machines.

**Comment by grimmySwe** [comment]
@mklepaczewski you are right that subrepo does not support multiple repos in the same directory. Reasons for that are:
1. We use a .gitrepo file stored in the directory.
2. If both repos have files with the same name it will not work.

For the autoloading I don't see that you shouldn't be able to handle intermediate directories? I have extremely little php experience so I might be completely off but can't the autoload find the correct file with dots in it? So if you have your class db.My_Company.Database.CoolDbClass it will find it in libs/db/My_Company/Database/CoolDbClass.php 

Another option would be to introduce a build step where you collect the necessary files and put them into the right place.

**Comment by mklepaczewski** [comment]
Sure, I can rewrite class autoloader, but it would be inconvenient thing to do (class autoloader might become different for each project, even when using the same framework). Furthermore this is only one example where piece of software depends on certain directory structure.

Build step - that would work too, but it has its own drawbacks (debugging issues, file duplication, going from simple "git pull" deployment to something that's much more complex).

I understand that this might be too complex feature to implement, especially since there are workarounds.

**Comment by dhuantes** [comment]
Hmmm.....

Maybe I'm not undertanding the question but we have a number of independent standalone repositories for libraries, as indicated, and we include them in other projects.  Our directory structure looks like:

`-Main_Project
-externals/
              -lib1/
              -lib2/
              -lib3/
 -src/
-CMakeLists.txt`

The root of the main repository has a .git/ folder and each of subrepos (e.g. lib1, lib2, and and lib3) have .gitrepo files in them.  The externals subdirectory has nothing but subfolders in it and this works fine with subrepo.  Hope that helps.

**Comment by dhuantes** [comment]
My markdown skills are lacking....maybe the attached pic will help show the directory structure I was referring to.
![multiple_subrepos](https://user-images.githubusercontent.com/2591512/34115477-62374c44-e3db-11e7-8190-0c9729883a64.png)

**Comment by grimmySwe** [comment]
@mklepaczewski Sorry to say Matt but I can't really see any viable solution of having multiple repos inside the same directory. If you have any possible solution suggestions I would be happy to look at them!

One of the problematic use cases would be on how to handle adding of files. Say that I actually have a directory with two different subrepos. Adding a new foo-file inside that directory is easy in the main repo. But what should happen when I push the changes to my subrepos? I would need to somehow mark it so it only goes to one of the repos, or maybe not even one of them.

A lot of structure in git is based on directory level, things like .gitignore will have a hard time determine where files should be located.

For the autoloader issue, shouldn't it be possible to make the autoloader generic and replace dots with directories? The actual class inside the file will always be named MyFavoriteHelperClass, depending on the project you might reference it differently.

**Comment by mklepaczewski** [comment]
@grimmySwe As I wrote rewriting autoloader is possible, but it's rather a piece of code I would prefer not to change on per project basis. It follows well-established convention and I prefer to wrestle with symlinks than to change it.
