### ISSUE TITLE
"git subrepo pull" takes very long? am I doing it wrong?

### ISSUE THREAD

**Issue by ewnjtgouierg** [ingydotnet/git-subrepo#331]
every time I do `git subrepo pull`, it takes as much time as when subrepo was cloned, as if it was getting fully cloned all over again (actually, even somewhat more), even when only one small file has changed / one commit since the previous pull

i have a very simple setup: repo with a single subrepo in it (added with git subrepo clone), and just tried it again and again on a blank repo; not sure what am I doing wrong. repository that I added as a subrepo has a tiny overall history (~50 commits), but that probably shouldn't even matter, b/c it's not initial pull, but updates?

**Comment by grimmySwe** [comment]
@ewnjtgouierg What version of subrepo are you using? Version 0.3.X had some internal mechanics that could drag out. If possible please test release/0.4.0 branch and see if that solves your problem.

**Comment by ewnjtgouierg** [comment]
yes, I am on 0.3
I will try 0.4.0 and share how it goes

**Comment by grimmySwe** [comment]
@ewnjtgouierg Sounds good!

**Comment by ewnjtgouierg** [comment]
yes, 0.4.0 is much faster
it still takes several seconds (: comparing to regular git pull of the same repository, but that is relatively bearable + probably unavoidable with the all that subrepo pull does
repo is a typical source code (lots of small text files), but may be relatively big in sense that it has 2590 directories and 4617 files
