### ISSUE TITLE
Pull a sub-repo in a sub-folder will delete all sub-folder content

### ISSUE THREAD

**Issue by jccaulfield** [ingydotnet/git-subrepo#333]
I have a (Unity3D on Windows 10) project with the following structure

* MyProject/
  * .git/...
  * Assets/
    * ASubRepo/...
     * MyProjectStuff/...

the folder ASubRepo is a sub repo. When I run the command:

> git subrepo pull Assets/ASubRepo -b dev/myproject

All of the contents of the local Assets folder will be deleted, and then recovered. No data is lost, but this is nasty behaviour, especially if you have Unity open at the time. I would expect that sub-repo operations would have no effect on non sub-repo folders.

Is this expected, or possibly a bug? Or am I doing something wrong?

Thanks!

**Comment by jccaulfield** [comment]
I also have the same thing happening when I do

> git subrepo push Assets/ASubRepo

**Comment by grimmySwe** [comment]
@jccaulfield We have tried to solve this in the upcoming 0.4.0 release, please check release/0.4.0 branch and see if that works better for you.

In subrepo priori to 0.4.0 we actually worked in place with all the operations, causing the directory to be recreated. In 0.4.0 we use `git worktree` and perform the operations in a temporary worktree instead.

**Comment by jccaulfield** [comment]
Great - just tried that release and push/pull worked without deleting and restoring any folders. That'll make working with Unity much nicer (esp if you forget to to close the editor before using subrepo). Good stuff - thanks!

**Comment by kams2160** [comment]
Version 0.4.0 also has better performance :) it's working so much faster

**Comment by grimmySwe** [comment]
0.4.0 reached master.
