### ISSUE TITLE
Pull just when necessary

### ISSUE THREAD

**Issue by bilougit** [ingydotnet/git-subrepo#334]
Hi, `git subrepo pull path-to-subrepo` creates a commit everytime I run it. In other words, I think `subrepo` cannot figure out if something has changed on the remote side or not.

Is this the expected behavior? If so, how do I update only if the remote branch has evolved? 

`version:  "0.3.1"`

**Comment by grimmySwe** [comment]
@bilougit Hi, please check branch release/0.4.0 and see if that works better for you.

**Comment by bilougit** [comment]
Exactly the same as https://github.com/ingydotnet/git-subrepo/issues/205. I'm closing this.
