### ISSUE TITLE
advertise recommended branch

### ISSUE THREAD

**Issue by mx1up** [ingydotnet/git-subrepo#335]
Hello,

I have been using subrepo for almost 2 years now and quite like it, thank you guys! However, from time to time I stumble upon a bug which later turns out to be fixed in some other branch. I see other people struggling with the same problem. So my suggestion is: maybe you can advertise the recommended branch to use on the front page somewhere? 

cheers

**Comment by ingydotnet** [comment]
Thank you for using subrepo, and for the kind words. The failure to get the best code back to master and released is entirely my fault.

I'm afraid that advertising a branch would do more harm than good.

There is now a goal to get the 0.4.0 release out by the end of the month. I'll close this issue for now. If we don't get this out by the end of the month, feel free to reopen it.

**Comment by mx1up** [comment]
fair enough :) It's nice to share this goal but if it isn't met I probably won't be pushing you because I don't like taxing other people's precious free time ;) anyway, keep up the good work :+1:

**Comment by ingydotnet** [comment]
Well to be honest, if I fail this month, we probably *should* be advertising a branch. :)
