### ISSUE TITLE
Question: Relationship with git-commands/git-subrepo?

### ISSUE THREAD

**Issue by trustin** [ingydotnet/git-subrepo#340]
Which is the upstream?

The `.gitrepo` file refers to `https://github.com/git-commands/git-subrepo#readme` in the auto-generated comment, but it seems like git-commands/git-subrepo is unmaintained.

If this repository is the upstream, how about updating the comment generation code?

**Comment by grimmySwe** [comment]
@ingydotnet Is this an old left-over?

**Comment by ingydotnet** [comment]
Hmm. Looks like I also created an org called 'git-subrepo'. Maybe we can move the project to that after the release.

Thoughts?

**Comment by olfway** [comment]
Unfortunately there is still outdated url in .gitrepo file:
```
; This subdirectory is a git "subrepo", and this file is maintained by the
; git-subrepo command. See https://github.com/git-commands/git-subrepo#readme
```

```
git-subrepo Version: 0.4.3
Copyright 2013-2020 Ingy döt Net
https://github.com/ingydotnet/git-subrepo
```

**Comment by trustin** [comment]
Yeah, whichever option he chooses, it'd be nice if he cleans up and disambiguates.

**Comment by admorgan** [comment]
I will the links to point to this repo.
