### ISSUE TITLE
git subrepo push stopped working

### ISSUE THREAD

**Issue by jccaulfield** [ingydotnet/git-subrepo#341]
git subrepo push just stopped working from me on my project. Here's what I see:

    $ git subrepo push Assets/DzCore
    Subrepo 'Assets/DzCore' has no new commits to push.

When I look in the .gitrepo file it looks correct: it contains the most recent remote commit in "Pulled Commit" and the associated host repo commit in "Pull Parent". However, I have other local commits that change files in the subrepo folder, but for some reason it thinks there's nothing to push.

Any ideas what might be going on here or what I can do to get it working again?

Thanks!

**Comment by grimmySwe** [comment]
@jccaulfield What version of subrepo are you running?

You can test to run:
```
$ git subrepo clean Assets/DzCore
$ git subrepo branch Assets/DzCore
```
Then you should you can check out the subrepo/Assets/DzCore branch and see what subrepo thinks is the difference between your local version and the remote.

**Comment by jccaulfield** [comment]
Thanks grimmySwe. I'm using version 0.4.0.

I ran those commands, and the branch it created did contain all my changes and differed from what was in my subreo remote. And then I ran "git subrepo push" again to see what would happen and it worked...

So, I'm not sure what was wrong, but its all good again now. Thanks for the help!

**Comment by grimmySwe** [comment]
Subrepo moves in mysterious ways :-) Please let us know if you find any problems!
