### ISSUE TITLE
Any news on 0.4.0 release?

### ISSUE THREAD

**Issue by barrettc** [ingydotnet/git-subrepo#343]
Is there a timeline on the 0.4.0 release being official? I've been using the release branch and it has solved some of the issues my team has encountered. I'm eager for it to become an official release and homebrew package updated - just curious on the timeline.

**Comment by grimmySwe** [comment]
@ingydotnet What do you say, any spare time in your busy schedule?

**Comment by ingydotnet** [comment]
@grimmySwe I spent some time on Saturday, and will spend some time each day this week. Will keep you up to date. Thanks!

**Comment by FanchTheSystem** [comment]
@ingydotnet  So what's up with 0.4.0 release  ?

**Comment by ingydotnet** [comment]
@FanchTheSystem I'm thinking that I should probably go ahead and make release/0.4.0 branch be master, and then fix the things I don't like later. But I should probably at least review to see what I'm setting myself up for...

**Comment by bohansen** [comment]
If one is starting with subrepos from scratch which version is recommended until 0.4.0 is out?

**Comment by grimmySwe** [comment]
@bohansen I might be biased but I would recommend the "release/0.4.0" branch, anything prior to that would most likely get you some issues.

We are using 0.4.0 in production and I there are no major known issues.

**Comment by bohansen** [comment]
Thanks, I'll give 0.4.0-branch a spin. There was a few tests not passing when running "make test", but that's maybe expected currently? I like the thorough test setup :+1:

**Comment by ingydotnet** [comment]
Hi all,

Apologies for the MIA. I am preparing for a couple big conference talks next week. I plan have time to work on the subrepo release between June 10-16.

Feel free to bug me then!

**Comment by FanchTheSystem** [comment]
@ingydotnet: Hope your conference talks was a success :) Maybe now you have some time for the next subrepo release ;)

**Comment by ingydotnet** [comment]
@FanchTheSystem Thanks. They were a great success. I also have another conference next Sunday, but I'm giving one of the same talks. I find myself in a position with not quite as much time as I had hoped. Also because I promised to coordinate a pyyaml release this week. :\

That said, I am going to focus on at least getting the subrepo release process figured out. ie Figuring out what *must* happen to do a release. I'll try to start a planning ticket today.

Anyone who wants to join #gitcommands on irc.freenode.net to help out, is welcome.

**Comment by ingydotnet** [comment]
Greetings all,

A couple points of good news. First I am done with all my conference work for this month. Next one is in August in Glasgow. :)

Second, more importantly, I have 2 projects that I'm very actively working on that have a big need for git-subrepo. I plan to be using subrepo a lot this week and will be using that as an excuse to dive in and get this long overdue release done.

I'll say it again... I don't know how many people here use IRC, but I'm always on IRC and it's the best way to get me to work on something specific. So as in my last comment: "Anyone who wants to join #gitcommands on irc.freenode.net to help out, is welcome." (Even if "helping out" is just nudging me along...)

**Comment by ingydotnet** [comment]
Hi guys,

I'm fire-fighting putting out the next PyYAML release, which is critical because it currently doesn't work with latest Python version.

But I'm still keen on this release. Hopefully I'll start by the end of this week or the start of next week.

Thanks for your patience.

**Comment by tobse80** [comment]
Hi all,

Are there any updates on releasing 0.4.0? The branch seems to work pretty well, but it's still not on master...

Thanks!

**Comment by ingydotnet** [comment]
Apologies for the delays. Hoping to review it this week. I know, I know...

**Comment by talios** [comment]
Any updates on the 0.4.0 release?

**Comment by ingydotnet** [comment]
@talios My life is finally calming down just a bit. I'm going to try to take a look at things this week.

I would like to just mush the release branch to master and fix anything I don't like later. I'd just like to know if I'm painting myself into any corners that I can't get out of later.

**Comment by tobse80** [comment]
Hi there,

any news on releasing 0.4.0 as master?

My experiences so far: release/0.4.0 solves issues for the standard ```subrepo clone/push/pull``` workflow, making it smoother and less error-prone. So why not moving forward?

Cheers!

**Comment by ingydotnet** [comment]
Hoping to look at it this week.

**Comment by juddgaddie** [comment]
How did it go ?

**Comment by kohlhase** [comment]
We are still waiting for a release on master,  any  release, ...

**Comment by juddgaddie** [comment]
@grimmySwe since you are supporting 0.4.0 for your own purposes are you perhaps interested in maintaing a release of it?

**Comment by ingydotnet** [comment]
@grimmySwe I'll be in your timezone from for a few weeks starting next week. I'll contact you about figuring out a release plan.

**Comment by grimmySwe** [comment]
@Ingy dot Net <ingy@ingy.net> That sounds good, I'll be in Essen most of
next week visiting the Spiel board game fair so that will be hectic.

Den ons 17 okt. 2018 kl 07:14 skrev Ingy döt Net <notifications@github.com>:

**Comment by ingydotnet** [comment]
Done and Done!

I had a brief call with @grimmySwe today and we agreed that making the 0.4.0
branch be master as-is was the best approach at this time. Any problems that
arise can surely be fixed.

Apologies to all for dragging this on for so long. Thanks to all for your
patience!

I have created https://github.com/ingydotnet/git-subrepo/projects/2 to plan the
next 0.4.1 release.
