### ISSUE TITLE
fatal: Not a valid object name: ''.

### ISSUE THREAD

**Issue by brianjmurrell** [ingydotnet/git-subrepo#348]
So, per #345 and #346 I'm trying some pretty simple workflows with [release/0.4.0](https://github.com/ingydotnet/git-subrepo/tree/release/0.4.0) and still seem to still be running into some problems.

I did a `git subrep clone` with 0.4.0 and then subsequently the subrepo I cloned got a new commit pushed to it so I thought it would be simple to get that new code into my subrepo:

```
$ git subrepo -v pull include
* Assert that working copy is clean: /home/brian/iml/python-django
* Check for worktree with branch subrepo/include
  * Fetch the upstream: git@github.com:intel-hpdd/module-tools.git (master).
  * Get the upstream subrepo HEAD commit.
  * Create ref 'refs/subrepo/include/fetch'.
* Deleting old 'subrepo/include' branch.
* Remove worktree: 
* Create subrepo branch 'subrepo/include'.
  * Check if the 'subrepo/include' branch already exists.
  * Subrepo parent: d9025bcbee964fa14385a69d83f3986e29964105
  * Create new commits with parents into the subrepo fetch
  * Create branch 'subrepo/include' for this new commit set .
git-subrepo: Command failed: 'git branch subrepo/include '.
fatal: Not a valid object name: ''.
```

But as you can see, not so much.  What am I doing wrong?

**Comment by grimmySwe** [comment]
From the log it looks like you don't get any commits to work on. Most probable cause is that the ```git rev-list --reverse --ancestry-path "$subrepo_parent..HEAD"``` command returns an empty list.

Can you try to ```git rev-list --reverse --ancestry-path d9025bcbee964fa14385a69d83f3986e29964105..HEAD``` in your main repo for the current branch? 

It can be a fact that you have done some rebase that the d9025bcbee964fa14385a69d83f3986e29964105 is no longer part of your current history.

If that is the case, you might need to reclone the subrepo if you have no local changes.

I have a work in progress branch where there is a "-s" squash flag for this case, then you ignore previous history and only care about the last parent.

**Comment by brianjmurrell** [comment]
Ahh.  So to be clear, I cannot rebase (i.e. and reorder patches) once I have done the `git subrepo clone` such that the hash of the subrepo commit changes.

Of course that makes total sense now that I say it out loud.

I'll keep this in mind in the future and just make I do my `subrepo clone` operation where I need it in the order of commits.

**Comment by grimmySwe** [comment]
In the .gitrepo file we store the previous parent hash, if that hash doesn't exist we don't have anything to work with.

As you say, you need to pay a little attention to this when/if you rebase.

**Comment by vjpr** [comment]
@grimmySwe Should add a check after `git rev-list --reverse --ancestry-path` to let the user know about possible fixes. I just ran into this.

**Comment by dperetti** [comment]
I just fixed the problem like this:

1. Use`git reflog` to find the most recent "rebase commit".
2. Set the `parent` in `.gitrepo`to that commit.

**Comment by amurgZainar** [comment]
Hello,

Can someone help me understand what is the meaning of `Pulled commit` and who is `Pull Parrent`?
```
Git subrepo 'my_subrepo':
  Remote URL:      https://gitlab.com/my_subrepo.git
  Upstream Ref:    f3c0a838
  Tracking Branch: main
  Pulled Commit:   394d5f2a
  Pull Parent:     0344fc5f
  ```
  
  I'm facing the same issue on this topic when trying to update `my_subrepo` from the upstream from within the main repo:
  
  ```
  amurg@pc:~/dev/repos/$ git subrepo pull my_subrepo -vv
* Assert that working copy is clean: ~/dir
* Check for worktree with branch subrepo/my_subrepo
  * Fetch the upstream: https://gitlab.com/my_subrepo.git (main).
  * Get the upstream subrepo HEAD commit.
  * Create ref 'refs/subrepo/my_subrepo/fetch'.
* Deleting old 'subrepo/my_subrepo' branch.
* Remove worktree: 
* Create subrepo branch 'subrepo/my_branch'.
  * Check if the 'subrepo/my_branch' branch already exists.
  * Subrepo parent: 0344fc5f7c00f70590a10a79043531f8ef0fd924
  * Create new commits with parents into the subrepo fetch
  * Create branch 'subrepo/my_branch' for this new commit set .
git-subrepo: Command failed: 'git branch subrepo/my_branch '.
fatal: Not a valid object name: ''.
  ```
  
  Running `git rev-list --reverse --ancestry-path 0344fc5f7c00f70590a10a79043531f8ef0fd924..HEAD` issues the following error:
`fatal: Invalid revision range 0344fc5f7c00f70590a10a79043531f8ef0fd924..HEAD`
  
  I don't know how I got into this situation again. First time I though I did something wrong and I decided to just `git rm -r my_subrepo` and reclone `my_subrepo` from within the main repository, but now I got into this situation again after pushing something to the `main` branch of `my_subrepo`. I doubt that the only way to fix this is to remove the subrepo and reclone it every time.

**Comment by harry-jubb-cresset** [comment]
> This is essentially the same doing a new git subrepo clone -f to put everything back in sync.

Just to say thanks for this, doing a `-f` clone ended up being the simplest way to resolve this when hashes had been altered elsewhere.
