### ISSUE TITLE
fatal: Not a valid object name: ''.

### ISSUE THREAD

**Issue by Sharcoux** [ingydotnet/git-subrepo#350]
Hi,

I am trying git subrepo for the first time, so maybe I just missed something in the doc.

I have a super project including 3 subrepos. I successfully created the subrepos. Now, I made some changes on my super project including some files from the subrepos. I want to push back thoses changes to the subrepos git projects.

I commited my changes at the super project level, and now, if I understood correctly, I should `git subrepo branch mySubRepo`, but I get:

```
git-subrepo: Command failed: 'git branch subrepo/client '.
fatal: Not a valid object name: ''.
```

I am using the release 0.4.0 on MacOS.

**Comment by grimmySwe** [comment]
If there are no problems, you shouldn't need to run the `git subrepo branch mySubRepo` command. If nothing has happened in the subrepos `git subrepo push mySubRepo` should be enough. If something has happened it will complain and you need to run `git subrepo pull mySubRepo`first.

**Comment by grimmySwe** [comment]
In further error reports, `-vd` is valuable flags that will give extra information in the debug process.

**Comment by Sharcoux** [comment]
git subrepo pull client
Subrepo 'client' is up to date.

git subrepo push client
git-subrepo: Command failed: 'git branch subrepo/client '.
fatal: Not a valid object name: ''.

**Comment by Sharcoux** [comment]
git subrepo push client -vd
>>> git rev-parse --verify HEAD
* Assert that working copy is clean: /.../
* Check for worktree with branch subrepo/client
  * Fetch the upstream: git@gitlab.com:... (master).
>>> git fetch --no-tags --quiet git@gitlab.com:... master
  * Get the upstream subrepo HEAD commit.
>>> git rev-parse FETCH_HEAD^0
  * Create ref 'refs/subrepo/client/fetch'.
>>> git update-ref refs/subrepo/client/fetch ...
* Check upstream head against .gitrepo commit.
* Deleting old 'subrepo/client' branch.
* Remove worktree:
>>> git branch -D subrepo/client
* Create subrepo branch 'subrepo/client'.
  * Check if the 'subrepo/client' branch already exists.
  * Subrepo parent: ...
  * Create new commits with parents into the subrepo fetch
>>> git rev-list --reverse --ancestry-path ...HEAD
  * Create branch 'subrepo/client' for this new commit set .
>>> git branch subrepo/client
git-subrepo: Command failed: 'git branch subrepo/client '.
fatal: Not a valid object name: ''.

**Comment by Sharcoux** [comment]
Maybe I have an idea...

**Comment by grimmySwe** [comment]
Have you done any rebasing lately? Check that the # referenced in mySubRepo/.gitrepo:parent is actually in the current history.

**Comment by Sharcoux** [comment]
Yes actually I did do something not very clean, but I think I fixed it correctly (apparently not).

This is the log of my client project
```
 *  (HEAD -> master, origin/master) f16e535 update package.json (5 days ago) <François Billioud>
 *  390d336 Rename common module (5 days ago) <François Billioud>
 *  3ac9595 first commit on new sub repo (5 days ago) <François Billioud>
```

This is my current client/.gitrepo

```
[subrepo]
        remote = git@gitlab.com:yumii/webrtc-client.git
        branch = master
        commit = f16e53596542b3b0d31afbb93eacbc6326b412fb
        parent = 390d3364ea819fa3a6efa173887f5d50bf37910f
        cmdver = 0.3.1
```
I had to change the remote so I edited the file manually because I didn't see a better way to do it.

(great many thanks for your help by the way)

**Comment by grimmySwe** [comment]
Did you solve it? 

Problem seems to be that `git rev-list --reverse --ancestry-path ...HEAD` has a bad first revision. Often this comes from a mismatch in the parent setting.

You can of course run this by hand to verify. `git rev-list --reverse --ancestry-path390d3364ea819fa3a6efa173887f5d50bf37910f...HEAD`

**Comment by Sharcoux** [comment]
To clarify, my project is module-webrtc, and my subrepo is webrtc-client. The log tree I published earlier was the tree of webrtc-client.

**Comment by Sharcoux** [comment]
hannnnnn ok !!!! =)
Sorry for that.

So I should set the parent to the # of my super-project where the state of my local subrepo matches the state of the remote one.

You're a genious! thanks for your time and this awesome project!
