### ISSUE TITLE
push several patches without sqaushing

### ISSUE THREAD

**Issue by brianjmurrell** [ingydotnet/git-subrepo#351]
So, I have done some work in a subrepo and have a number of different individual changes that I want to push back up (to individual branches for review), but I don't want to squash them into a single commit upstream.  I want them to remain individual and be distinct PRs.  They can be based on one another reflecting their ordering in my local subrepo.  Or not, if that's easier.

Is this possible?

**Comment by grimmySwe** [comment]
@brianjmurrell When you use Subrepo, pushing up upstream never squashes commits (unless you use a flag). Default behavior is that when you pull changes from upstream they will be squashed into a single commit.

Or did I misunderstand your question?
