### ISSUE TITLE
Branch's hash change if recreated

### ISSUE THREAD

**Issue by eduardobogoni** [ingydotnet/git-subrepo#357]
Steps:

1. Create a branch for a subrepo (1);
2. Wait some time;
3. Recreate a branch for the same subrepo (2).

No commits done or code changed in steps and, even so, the hashs got in (1) and (2) are different.
Like with git-subtree I expected the hashs to be the same.
I'm using release/0.4.0 version of git-subrepo (74339e8ed7f7719b3430fa507fbae507d4b94adf).

### Test

```
#!/bin/bash

set -u
set -e

git --version
echo "git-subrepo version $(git subrepo --version)"

# Helper to create and commit a file ($1: repository, $2: file's subpath)
function commit_file {
  touch "$1/$2"
  git -C "$1" add "$2"
  git -C "$1" commit -m "File \"$2\""
}

# Create branch for "mylib" subrepo in "app" repository"
function create_and_show_branch {
  git -C "$APP" subrepo branch mylib --force
  HASH="$(git -C "$APP" rev-parse subrepo/mylib)"
  echo "Branch hash: $HASH"  
}

ROOT="$(mktemp -d)"
MYLIB_REMOTE="$ROOT/mylib_remote"
MYLIB_LOCAL="$ROOT/mylib_local"
APP="$ROOT/app"

# Initialize "mylib" remote repository with some content
git init --bare "$MYLIB_REMOTE"
git init "$MYLIB_LOCAL"
commit_file "$MYLIB_LOCAL" foo
git -C "$MYLIB_LOCAL" push "$MYLIB_REMOTE" master

# Create main app and clone "mylib" with git-subrepo
git init "$APP"
commit_file "$APP" file2
git -C "$APP" subrepo clone "$MYLIB_REMOTE" "mylib"
commit_file "$APP" mylib/file3

# First branch creation
create_and_show_branch

# Waiting some time
sleep 2

# Second branch creation
create_and_show_branch
```

### Output

```
git version 2.7.4
git-subrepo version 0.4.0
# Repositories initialization, commits, etc
Created branch 'subrepo/mylib' and worktree '.git/tmp/subrepo/mylib'.
Branch hash: 77bb5ee2d1b6902f2c0917a1d8fe79b454d67282
Created branch 'subrepo/mylib' and worktree '.git/tmp/subrepo/mylib'.
Branch hash: 592e5d1a502935c44bd3df241db9b0d8f9b1e8d3
```

**Comment by grimmySwe** [comment]
In git-subrepo we do create new commits each time you run the branch command. And as a commit is always unique, I don't really see how we could get the same Hash each time.

If you look at the tree Hash then you should probably get the same (unless there is some time stamp that has changed somewhere.)

Is that an answer to your question?

**Comment by eduardobogoni** [comment]
@> In git-subrepo we do create new commits each time you run the branch command. And as a commit is always unique, I don't really see how we could get the same Hash each time.
> 
> If you look at the tree Hash then you should probably get the same (unless there is some time stamp that has changed somewhere.)
> 
> Is that an answer to your question?

I found this in subrepo:branch function's code:

> When we create new commits we leave the author information unchanged
> the committer will though be updated to the current user
> This should be analog how cherrypicking is handled allowing git
> to store both the original author but also the responsible committer
> that created the local version of the commit and pushed it.

I believe it makes sense, but I really need that, given a main repository revision, I have a unique subrepo history. So I do a fork keeping the commiter unchanged.

Thank you for answer my question, @grimmySwe.
