### ISSUE TITLE
how can I capture the Commit ID that triggered the build in Jenkins pushed out with Web-hook.

### ISSUE THREAD

**Issue by forpix** [ingydotnet/git-subrepo#365]
How can I capture the Commit ID in pipeline job that is triggered by with Web-hook.

**Comment by grimmySwe** [comment]
I am not really sure how this applies to git-subrepo?

Is this something like: https://jenkins.io/doc/pipeline/examples/ if you scroll down to Gitcommit?

**Comment by udeved** [comment]
@forpix 

Our artixlinux distro builds all packages in pipeline.
We have basically git super repos containing package subrepos.
The pipeline does a custom checkout, but it it will not get the head commit sha, but the previous one.
Assuming you have a subrepo push followed by a push in the superrepo, and the jenkinsfile is in the superrepo.

`String commit = sh(returnStdout: true, script: 'git rev-parse @~').trim()`

would accomplish it.
