### ISSUE TITLE
Use only subset of files from upstream subrepo

### ISSUE THREAD

**Issue by MattLichter** [ingydotnet/git-subrepo#368]
Apologies if this has already been asked, but I couldn't find a definitive answer in the docs.  I'm researching whether git-subrepo solves a particular problem for us.  We have an upstream repo with several independent libraries:

- Upstream
  - Lib1
  - Lib2
  - Lib3

We would like to pull only Lib3 into our downstream repository, e.g. like this

- Downstream
  - Foo
  - Bar
  - Lib3

Does git-subrepo provide an easy way to just grab a subdirectory of the upstream repo?  I realize that I could put Lib1, Lib2, and Lib3 into their own repositories or branches, but was wondering if git-subrepo already handles this use case directly.  (Also, we don't always control the upstream repo.)

Thanks!

**Comment by grimmySwe** [comment]
Hi Matt,

Git subrepo will unfortunately only work on repo level. From my somewhat limited git experience most of git operations are on a repo level.

I don't see any problems though with having a structure like this:

- Downstream
   - Foo
   - Bar
   - Subrepo
       - Lib1
       - Lib2
       - Lib3

You only have to use the parts that you need?

-- Magnus

**Comment by grimmySwe** [comment]
@MattLichter closing this issue now, if you need more help please let me know!
