### ISSUE TITLE
recommend a prodution version

### ISSUE THREAD

**Issue by kohlhase** [ingydotnet/git-subrepo#371]
I am a great fan of `git subrepo` and I have been using it for years now. 
There are some situations, where the system fails on me and I have to re-clone. 
So I am waiting for an improved version and I am looking at https://github.com/ingydotnet/git-subrepo/network and see that there is a lot of development going on, just not on the master branch which has been dormant for more than 18 months. 

I cannot find any documentation which branch I should try/use. 
Could you please update the readme with a recommendation (or multiple depending on the situation)?

Much obliged.

**Comment by juddgaddie** [comment]
Try use remotes/origin/release/0.4.0

**Comment by ingydotnet** [comment]
The `release/0.4.0` branch is now merged to `master`. Use `master` or the latest release tag for production use.
