### ISSUE TITLE
Feature Request -  flag to perform (git subrepo push my/subrepo && git push)

### ISSUE THREAD

**Issue by juddgaddie** [ingydotnet/git-subrepo#372]

**Comment by admorgan** [comment]
subrepo should not push the .gitrepo upstream. What problem are you experiencing that you believe would be addressed by upstream knowing it was a subrepo of another repo?

**Comment by juddgaddie** [comment]
Should probably state, I'm referring to the 0.4.0 branch

**Comment by juddgaddie** [comment]
@grimmySwe 
```git subrepo push my/subrepo 
subrepo updates my/subrepo/.gitrepo (I understand this is the new default in 0.4.0)
I then need to
``` git push

I am wondering if there is an argument to 
```git subrepo push my/subrepo 
that will auto do the git push of the modified my/subrepo/.gitrepo

It would be also interesting to know what the consequences of throwing away the update to my/subrepo/.gitrepo?

Thanks!

**Comment by grimmySwe** [comment]
@juddgaddie Ahh, then I understand :-) No there is currently no option for auto push to the parent repo. I will mark this as Enhancement.

Throwing away the .gitrepo changes will be very bad. It is the core of creating links between the two repos. It has a pointer to the last known commit in the subrepo and a pointer on where to start in the parent repo when recreating the structure.

**Comment by admorgan** [comment]
The problem with this enhancement is differentiating flags meant for the parent repo and the subrepo. I can't think of any that would make sense. If you have suggestions please reopen this issue.
