### ISSUE TITLE
Test on windows

### ISSUE THREAD

**Issue by ingydotnet** [ingydotnet/git-subrepo#38]
This stuff should all work on Cygwin.

There is a possibility it can run in `cmd` (DOS) shell as well, but need to
investigate. A friend told me that he can run any cygwin commands from `cmd` as
long as they are in the PATH.

**Comment by ukoethe** [comment]
Thanks for a very promising tool! However, on Windows the most important target which subrepo should support is https://msysgit.github.io/ (git's standard distribution on Windows). It comes with a fully functional bash shell, but uses a rather outdated version (bash 3.1.0, unless they have recently upgraded). Therefore, it chokes on some of the more modern bash commands like `=~`. I'm not a bash expert, but it looks like this shouldn't be too difficult to fix. I don't think it is necessary to support cygwin or `cmd` if the git-bash works.

**Comment by ingydotnet** [comment]
@ukoethe, thanks for this information. I will give it a try when I have a chance.

All my bash stuff targets Bash 3.2 which is what OSX is stuck on. It would be
wonderful if msysgit also used at least that.

There are only 13 lines in subrepo using =~ but the tet-more-bash framework
would also need to be changed.

**Comment by ukoethe** [comment]
The latest msysgit commit referring to bash was on 7. Jan 2015: `Update bash.exe to 3.1.23(6)`.

**Comment by Michael-DST** [comment]
First off... have to send my appreciation for this project.  I have been doing some investigation between submodules/subtree and it is not pretty out there. :P  This seems like the best solution and should be in git by default.

Secondly, I have tried the "source init" approach for installing this and as you probably suspect, it doesn't work. :)  Here is the output:
sh: /c/Users/.../git-subrepo/init: line 20: conditional binary operator expected
sh: /c/Users/.../git-subrepo/init: line 20: syntax error near `=~'
sh: /c/Users/.../git-subrepo/init: line 20: `if [[ "$GIT_SUBREPO_ROOT" =~ ^/ ]]; then'

Please let me know if I can be of any further assistance around this issue.  I am very much a Windows/MSFT developer so this is all new territory for me.  I will try to help where I can, however.

**Comment by Michael-DST** [comment]
I did manage to get the "by-hand" method somewhat working.  Here is my .bash_profile:

```
[ -f ~/.bashrc ] && . ~/.bashrc

export PATH="/c/.../git-subrepo/lib:$PATH"
export MANPATH="/c/.../git-subrepo/man:$MANPATH"

source ~/.../git-subrepo/share/git-completion.bash
source ~/.../git-subrepo/share/completion.bash
```

When running "git subrepo" I get the following message:

```
c:\...\git-subrepo\lib\git-subrepo: line 10: c:\...\git-subrepo\lib\git-subrepo/git-subrepo.d/bash+.bash: No such file or directory
```

Looking at this file there's a reference to BASH_SOURCE.  Looks like this isn't resolving as expected currently.

**Comment by Michael-DST** [comment]
Looking at this further, it's our good and familiar friends the slashes.
https://github.com/ingydotnet/git-subrepo/blob/master/lib/git-subrepo#L10

Changing this to:
source "${BASH_SOURCE%\\*}/git-subrepo.d/bash+.bash"

Loads the file.  Unfortunately it is not finding the ext/bashplus.  Looking into that now. :)

**Comment by Michael-DST** [comment]
Well, got the bashplus loaded (hard-coded the path :stuck_out_tongue:), but it does look like I am up against a 3.1 ([Git for Windows 1.9.5 Preview](git-scm.com/download/win)) vs. the required 3.2 for now.  This is silly as 1.9.5 ("current" version) is a preview and they are up to 2.3.2 in source currently.  Getting it would require pulling and installing and I just don't have the patience for that right now.  Guess I'll have to look into subtree/module after all.  Such a shame/disappointment! :(

**Comment by ingydotnet** [comment]
https://github.com/msysgit/git/issues/301

I don't see any tags beyond 1.9.5 for https://github.com/msysgit/git

Where do you see 2.3.2? More importantly, have they moved past Bash 3.1?

**Comment by Michael-DST** [comment]
Yes, if you visit this page:
http://git-scm.com/download/win

It mentions 2.3.3 (someone did some weekend work!):
> The current source code release is version 2.3.3. If you want the newer version, you can build it from the source code.

I might be totally misunderstanding this, however.

**Comment by ingydotnet** [comment]
It seems to me so far that msysgit/git is a fork of git/git. The former has a verison 1.9.5 and the latter (the version of git itself) is 2.3.3. It also appears (but not 100% verified by me) that Bash is pinned to 3.1.

I could probably find a way to use grep (or something else) instead of `=~` for regex matching on ancient bashes at some point in the future.

PRs definitely welcome.

**Comment by Michael-DST** [comment]
Yeah it's allllll foreign to me, unfortunately.  Otherwise I would totally try to assist!

**Comment by typingArtist** [comment]
Ingy, could you please update the Readme in the relevant section about the required minimum version of bash? Currently it just reads “Written in (very modern) Bash, with full test suite. Take a look.”Later there might be either a patch applied so git-subrepo works under bash-3.1, or all older distributions (like msysgit) requiring that old version have become extinct.

**Comment by rickbutton** [comment]
It looks like mysys git is not going to get a newer version of bash in our lifetime, but I have had success with using cygwin (specifically [babun](https://babun.github.io/)). git-subrepo works under babun without any configuration as far as I can tell.

**Comment by BO45** [comment]
Installed using babun and works perfectly. Plus the babun shell is real pretty :D

**Comment by mmalcolm** [comment]
The new git for windows 2.4.6 has an updated bash.
They've changed the name of the product and the websites, and it wasn't simple to find the new download location. It's no longer called "msysgit"
http://git-for-windows.github.io/

So looks like this is a go for normal windows. (still requires the "git bash" prompt though I think)

> $ sh --version
> GNU bash, version 4.3.39(3)-release (i686-pc-msys)
> Copyright (C) 2013 Free Software Foundation, Inc.

**Comment by ingydotnet** [comment]
This is great news. I'll have a look at it.

**Comment by ingydotnet** [comment]
I got a windows environment and started working on this last week. Things are
looking promising.

I'm currently stuck on the symlinks I use. Symlinks seem to be a bit
problematic even on newer windows. If anyone can help here, please speak up.

I'm considering having the tool just make copies of the symlinked files on
Windows.

**Comment by ingydotnet** [comment]
Closing. Moved to #119
