### ISSUE TITLE
git subrepo push does not work with [log] relative inside .gitconfig

### ISSUE THREAD

**Issue by cep21** [ingydotnet/git-subrepo#383]
This is inside my `~/.gitconfig`

```
# Show a log of '56 minutes ago' rather than 'November 12, 2008 12:34:53'
[log]
  date = relative
```
Then, if I run git subrepo push
```
> git subrepo push scripts2/mything
fatal: invalid date format: 21 minutes ago
fatal: invalid date format: 20 minutes ago
git-subrepo: Command failed: 'git branch subrepo/scripts2/mything '.
fatal: Not a valid object name: ''.
```

The push command works if I comment out the `date=relative`.  I think the `git log` command lets you overwrite the default.

**Comment by IPetrik** [comment]
+1 I have the same issue with `date = short`. Had a lot of hope for this program, too...

**Comment by devinrhode2** [comment]
seem to also had issues with `date = human`
