### ISSUE TITLE
My subrepo blew up

### ISSUE THREAD

**Issue by Yzrsah** [ingydotnet/git-subrepo#386]
Hi

When doing a `git remote -v`, I noticed that many of my subrepos had incorrect pathnames or locations or misspellings related to the very first clone. I had moved stuff around and done other organization afterwards.

The subrepo doc says _" Moving/renaming/deleting a subrepo subdir JustWorks™ "_

So I was trying to fix this problem and I did `git subrepo clean --all`, because I was annoyed by the remote listings being incorrect and I wanted to make it all perfect.

But I have not yet had enough time to get around to trying to fix it all, and I am worried that the subrepo will break again.

**Comment by admorgan** [comment]
@Yzrsah it has been a year. Have you tested to see if things are working correctly now? The values from your .gitrepo files are what will drive your remotes. I have made similar errors and not run into an issue. I would like to close this if you have come to a resolution.
