### ISSUE TITLE
Can't pull

### ISSUE THREAD

**Issue by kuchaguangjie** [ingydotnet/git-subrepo#391]
When I try to pull a sub repo via command: `git subrepo pull eric-tmp`, got error:

```
git-subrepo: There is already a worktree with branch subrepo/eric-tmp.
Use the --force flag to override this check or perform a subrepo clean
to remove the worktree.
```

Don't understand why this happen ? The subrepo version is `0.4.0`.

BTW, really can't find a simple & working tutorial for git-subrepo on internet.

**Comment by Venryx** [comment]
I get the same message, and don't understand why the subrepo needs "cleaning" before being able to run `pull`?

With normal git, as long as you have your index and working-tree committed/resolved, `git pull` works, correct? (at least that's been my experience as far as I've used it)

So what is the extra complication that occurs when using `git subrepo pull`?

@grimmySwe Is there a succinct way of explaining why the error message occurs, despite a committed/resolved index and working-tree? Or is it too complicated to explain without existing background knowledge?

**Comment by pauleckhardt** [comment]
Sorry, but I don't get the point. Isn't i the point of `subrepo pull` to pull into an already existing workdir?
Maybe I'm too stupid, but I just get this message sometimes and don't know why. Other times it works as I think it should...

The link to the wiki didn't help me, theres nothing mentioned about this.
Could anyone please explain?

**Comment by pauleckhardt** [comment]
Thanks for the explanation. I understand that there could be a need for cleanup if there is a consistency problem.
But I don't understand this simple case:

```
$ git branch
    issue_6
  * main

# all clean!

$ git subrepo push whatever/
Subrepo 'whatever' has no new commits to push.

$ git branch
    issue_6
  * main
  + subrepo/whatever

# why is subrepo/whatever here?

$ git subrepo pull whatever/
git-subrepo: There is already a worktree with branch subrepo/whatever.
Use the --force flag to override this check or perform a subrepo clean
to remove the worktree.
```

**Comment by admorgan** [comment]
Because whatever was created to figure out that there was nothing to do, although I agree that it should not get you in this state. What version are you using?

**Comment by pauleckhardt** [comment]
> Because whatever was created to figure out that there was nothing to do, although I agree that it should not get you in this state. What version are you using?

0.4.3

**Comment by pauleckhardt** [comment]
Still the same behaviour.

```
$ git subrepo --version
0.4.5
$ git branch
    issue_6
  * main
$ git subrepo push whatever
Subrepo 'whatever' has no new commits to push.
$ git branch
    issue_6
  * main
  + subrepo/whatever
```

But I'm already happy to understand when the problem occurs (after a subrepo push with no changes). So I can just perform a subrepo clean right away. So far the problem occurred on the next pull (often days afterwards) and I was not sure if I would destroy any changes with the clean run (clean sounded somehow dangerous, even more so when I did not know why I needed it). 
Thanks for the help!

**Comment by admorgan** [comment]
Lets open a new issue for this, and I will add update the tests to ensure this doesn't happen when it shouldn't.
