### ISSUE TITLE
subrepo push --squash comment

### ISSUE THREAD

**Issue by rmawatson** [ingydotnet/git-subrepo#397]
I've been trying out subrepo and I wanted to modify the comment when pushing subrepo changes upstream with squash. At the moment it seems to use the most recent commit message. Is it possible to provide a message or an option like when using squash with "rebase -i" to edit the the final commit message?

**Comment by grimmySwe** [comment]
Hi @rmawatson, sorry no, there is currently no way to change the actual commit message when you push.

The reason for this is that we want to keep the same commit hash, but as you say, it will use the latest one, so if you want to you can edit the last message locally before you push.

**Comment by admorgan** [comment]
@rmawatson I have done what you describe using the git subrepo branch command. This give you full control over what is submitted upstream. It is a lot more manual though.

**Comment by rmawatson** [comment]
great, thanks!
