### ISSUE TITLE
[Question] What's the right way to move subrepo into a new dir?

### ISSUE THREAD

**Issue by mity** [ingydotnet/git-subrepo#399]
I want to reorganize my growing repo and move all subrepos from the repo root into some new `3rd_party` subdir.

But I guess `git-subrepo` command is not compatible with `git mv` or `git rm`, because it supports all those `--al` and `--ALL` options, so I assume it has to keep some metadata under `.git` the vanilla commands are not aware of?

So, what's the recommended way how to do it?

**Comment by admorgan** [comment]
Actually mv and rm are the correct method. subrepo stores its metadata in the .gitrepo file in the subrepo directory, therefore it is completely safe to move them around.

**Comment by mity** [comment]
Thanks for the answer.

BTW it's so nice, when you encounter a tool which is smarter then you anticipate :)
