### ISSUE TITLE
git subrepo init --recursive

### ISSUE THREAD

**Issue by mrzv** [ingydotnet/git-subrepo#400]
Is it possible to add `--recursive` flag to `git subrepo init`? I'd like to add a subrepo that's using lots of submodules (ideally, to never have to think about them again), but I can't find a way to do this with `git subrepo`.

**Comment by grimmySwe** [comment]
@mrzv Subrepo and submodules doesn't really play that nicely together unfortunately.

**Comment by admorgan** [comment]
Would you want this to create a .gitrepo file for each of the submodules and add the files as they currently exist? Would the upstream project accept the patch with the .gitrepo file(s)?

**Comment by mrzv** [comment]
@admorgan I'm not sure if you are asking me or @grimmySwe, but I don't really understand your question. Can you elaborate?

**Comment by admorgan** [comment]
@mrzv Your request as I understood it was to have a git subrepo init --recursive that would convert a directory and any submodules linked to that directory to subrepos.

An example

repo/driver/lib1
                 /lib2
                 /lib3/encryption_engine

Where driver, driver/lib3, and driver/lib3/encryption_engine are all submodules.

If we had a git subrepo init --recursive then .gitrepo files would be created in:
repo/.gitrepo
repo/driver/.gitrepo
repo/driver/lib3/.gitrepo

If you were to make a modification to anything in repo/driver or repo/driver/lib3 and tried to do a git subrepo push it would include the .gitrepo file describing the previously recursive submodule. It seems unlikely that the subrepo project is going to accept those patches.

**Comment by mrzv** [comment]
@admorgan Ah, I understand. Thanks for explaining. I'm not actually concerned with the push part of this workflow (although I understand that it's a major component of gitrepo). I'm only interested in pull, where I'd like to incorporate an upstream library into my repository and to be able to pull updates to it (possibly merging them with any local changes).

If I want to contribute something back upstream, I don't mind manually pulling out those changes, or making them in a clean clone from the start.

**Comment by admorgan** [comment]
If you can describe a command that describes that, and doesn't confuse an already fraught command structure I can implement it for you.

**Comment by mrzv** [comment]
@admorgan I'm too novice of a git-subrepo user — which is to say, since I filed the issue, I found a much better solution, and haven't really used git-subrepo at all — to suggest anything that requires knowledge of the existing command structure. But thank you for the kind offer.

**Comment by admorgan** [comment]
I am curious what solution did you discover?

**Comment by mrzv** [comment]
I started using [Peru](https://github.com/buildinspace/peru). I'm using it a little differently from how it's described on their page. I setup a separate peru branch within the repo, which has nothing, but clean imports of various dependencies (modulo any changes applied through peru.yaml). This branch is then merged into master. I periodically update it (via peru) and re-merge into master. This takes advantage of the 3-way merge: if I make any changes on master to better integrate the dependencies, most of the time the changes are automatically applied during the merge.

Here are a couple of repos that follow this process: a very simple example in [diode](https://github.com/mrzv/diode) and a much more complicated setup in [VEFViewer](https://github.com/mrzv/VEFViewer). The [peru.yaml](https://github.com/mrzv/VEFViewer/blob/master/peru.yaml) in the latter shows off some of the neat features of this method.

There are some downsides. Lack of git integration means there is still a lot of manual work: especially when something is deleted, but overall I find it works great.

**Comment by admorgan** [comment]
I am glad you found something that works well for you. I am going to close this request. If you decide to reevaluate later feel free to reopen it.
