### ISSUE TITLE
Support for multiple subrepo remotes?

### ISSUE THREAD

**Issue by talios** [ingydotnet/git-subrepo#405]
The scenario I have is I've cloned a set of subrepos from our gitlab server

  git subrepo clone some-repo git@gitlab/some-repo

as normal, but now I wish I submit changes to our gerrit code review system. In a normal repo I'd setup a separate remote that points to the gerrit instance with a set of url/fetch/push URLs which makes pushing a review easier, such as:

```
[remote "for-review"]
  url = gerrit:some-repo
  fetch = +refs/heads/*:refs/remotes/for-review/*
  push = HEAD:refs/for/develop
```

Is it possible to setup a similar setup with subrepo? Maybe adding something into each `.gitrepo` file in the clones?

Note - I want to keep the original remote/branch settings so that I can still do a normal upstream push/pull.

**Comment by grimmySwe** [comment]
@talios You can clone the subrepo as a repo of it's own and make all the regular repo operations there.

There is no support for additional remotes in the .gitrepo file.

**Comment by talios** [comment]
> You can clone the subrepo as a repo of it's own and make all the regular repo operations there.

Doesn't that defeat the purpose of using subrepo then? Unless I'm mis-interpretting what you're saying...

Do you mean git clone'ing the repo, that contains my subrepos? If so, I don't think that'd work, as any "regular repo operations" won't be operating on the subrepo `./some-repo` was `/` in the original repo.

I suspect this may be similar to the PR issue elsewhere.

**Comment by grimmySwe** [comment]
@talios Yes, it might feel like an extra step, but the approach right now is that the subrepos should be transparent to the main repo. git has so many possibilities so it will be a huge amount of work to implement these options into subrepo.

So if you `git clone some-repo git@gitlab/some-repo` into your favorite location, you can work on it as a regular repo with full git functionality.

Or if you want to you can actually perform the reviews on the top repo level. Everything from the subrepos are "included" in the main repo. subrepo:s feature is that it can handle transactions between a directory in the repo and a subrepo.

**Comment by aya** [comment]
@talios are you looking for the --remote and --branch options of git subrepo ?
`git subrepo push some-repo -r gerrit:some-repo`

**Comment by talios** [comment]
@aya mmm possibly.  Essenstially, when pushing a review to gerrit one does `git push gerrit HEAD:refs/for/master`.

It's not a _branch_ per-sae, but a magic _ref_ that puts the code changes in a review queue for a branch, likewise, `git push gerrit HEAD:master` would push directly to that branch (and closing off any reviews placed in the queue).

I'll take a look at the `--remote` and `--branch` options.
