### ISSUE TITLE
Push to empty repository

### ISSUE THREAD

**Issue by cciocov** [ingydotnet/git-subrepo#410]
I've created a new (blank) repository on Github. Then running the below commands ends with an error.

```bash
mkdir project
cd project
git init
touch README.md
git add .
git commit -m "initial commit"
mkdir component
touch component/README.md
git add .
git commit -m "add component"
git subrepo init component --remote git@github.com:cciocov/test.git --branch v1
git subrepo push component
```

The last command errors with message:
`git-subrepo: Fetch for push failed: fatal: couldn't find remote ref v1`

I think this definitely used to work, but for some reason I can't get it to work now. Any thoughts?

**Comment by cciocov** [comment]
Found the issue! The latest version of GIT (2.21) changed the letter case in the error message (from `Couldn't find...` to `couldn't find...`) so as a result git-subrepo fails to identify pushes to empty repositories.

**Comment by grimmySwe** [comment]
Sounds like we need to make this case insensitive.
