### ISSUE TITLE
Now, how to convert subtree to subrepo. please !

### ISSUE THREAD

**Issue by inhere** [ingydotnet/git-subrepo#414]
Is this tool library no longer maintained?

**Comment by admorgan** [comment]
The easiest way to to make sure that the subtree is entirely updated upstream, remove it, then do git subrepo clone. It you need me to walk through a "dirty" subtree conversion to subrepo I can, but I don't really want to.

**Comment by grimmySwe** [comment]
@inhere as it's open source, the maintenance level is a "if I need it I will add it" and surely if there are huge bugs I believe we will fix them.

Regarding your question of converting subtree to subrepo, I need some more input to be able to give you any answer.

**Comment by inhere** [comment]
@admorgan  @grimmySwe  thank you.

Now I use forced push every time to prevent conflicts.

**Comment by nyanpasu64** [comment]
> [If] you need me to walk through a "dirty" subtree conversion to subrepo I can, but I don't really want to.

I have an ad-hoc subdirectory holding a vendored dependency with local edits (not `git subtree` with machine-readable upstream commit IDs), and figured out how to convert it to a `subrepo` myself.

I found two procedures. However, I suspect neither preserves your subtree's history. (See below for my guess as to how history reconstruction works.) As a result, this is not the best way to push your commits to upstream individually, though it works fine for pulling.

<details><summary>Via delete-clone (more difficult)</summary>

```sh
REMOTE_URL=https://github.com/...
REMOTE_BASE=0123deadbeef... # the commit you initially passed into `git subtree add`
SUBDIR=path/to/subtree

git rm -r $SUBDIR
git commit -m "doesn't matter"

git subrepo clone --branch=$REMOTE_BASE $REMOTE_URL $SUBDIR
git tag new
git reset --keep HEAD~2  # your initial commit before `git rm`

git checkout new $SUBDIR/.gitrepo
```

edit $SUBDIR/.gitrepo:

- `commit = $REMOTE_BASE`
- `parent = (git rev-parse HEAD)`

```
git commit -a -m "Convert $SUBDIR to subrepo"
```
</details>

## Via `subrepo init`

```sh
REMOTE_URL=https://github.com/...
REMOTE_BASE=0123deadbeef... # the commit you initially passed into `git subtree add`
SUBDIR=path/to/subtree

git subrepo init $SUBDIR -r $REMOTE_URL -b master
```

edit $SUBDIR/.gitrepo:
- `commit = $REMOTE_BASE`
- on the next line, add `parent =` value of `git rev-parse HEAD~`
    - if you don't add parent, subsequent `git subrepo pull ...` won't work

```
git commit -a --amend -m "Convert $SUBDIR to subrepo"
```

### How is the subrepo's history reconstructed?

If you perform a fresh clone of this repo and run `git subrepo pull $SUBDIR`, it's able to reconstruct a history consisting of `$REMOTE_BASE` followed by a a single commit named "Convert $SUBDIR to subrepo". I still don't fully understand how this is done. I think it uses `git log .../.gitrepo`. And the file's `parent` field is used to identify "Local commit from before previous clone/pull".

I'm still confused as to why `git subrepo init` produces a worktree with many commits (and no `parent` field), whereas my hackjob produces a worktree with a squashed commit.

## Merging in upstream changes

`git subrepo pull $SUBDIR`

or for debugging output,

`git subrepo -v pull $SUBDIR --force`

**Comment by admorgan** [comment]
@nyanpasu64 I suggest not reopening an issue in the future unless a bug was not correctly fixed.

In answer to your question the subrepo's history is reconstructed by using the information the .gitrepo file
The commit entry lets subrepo know the most recent code from the upstream repo that has been integrated into this repo.
The parent entry tells subrepo the last commit in this repo occurred before a repo change (if the repo hasn't been modified locally it will change with every pull).
The merge entry says how to play back changes when doing a pull or creating a subrepo branch.

git log and filter-branch using this information to recreate the history on a worktree.
