### ISSUE TITLE
git subrepo pull does not retain the original commit message

### ISSUE THREAD

**Issue by prrichard** [ingydotnet/git-subrepo#418]
Hi,

When using git subrepo pull command, we find that the commit message associated to the original commit that is being pulled from subrepo is no more available. It is getting overwritten with the tool generated commit message.

![image](https://user-images.githubusercontent.com/1207676/62848190-fc754a80-bcf7-11e9-8ce3-eb3d12d07714.png)

Regards,
PR

**Comment by prrichard** [comment]
Is it possible to retain the original commit message done in the subrepo?

Thanks

**Comment by grimmySwe** [comment]
Hi @prrichard 
There is currently no way of retaining the original message. There is though a --message option that allows you to manually set the message to something other then the pre generated one.

**Comment by admorgan** [comment]
@prrichard I can't figure out what you are talking about from the included screen shot. Which message are you trying to retain?

**Comment by admorgan** [comment]
If you would like to propose a new message option please open another issue and label it enhancement.
