### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by jonpas** [ingydotnet/git-subrepo#421]
I am aware this is not really the place to ask, but I am not finding any chat platform links or other places to ask this question.

What is the status of this project? I see there were no commits to any branches since November 2018. I am wondering if it's wise to use this project due to future support.

Thank you and apologies for using the issue tracker for this!

**Comment by grimmySwe** [comment]
@jonpas No need to apologize :-) 

I am keeping a little eye on the project, as we are using it in production. I don't know the status of @ingydotnet , he has a lot of other projects going I believe.

**Comment by bdklahn** [comment]
I was wondering the same thing, so I appreciate the question and the response. I worry a little about the mention of bugs in the README, and that some of the 121 Issues seem like they might be deal-breakers. But I really like the philosophy, concept, and thought that seems to have gone into this. And I often find that self-critical ("bugs") people often produce "beta" code that is much more stable than others' "release" code. @grimmySwe, has this been pretty stable/good for your production environment? Anyway, if this is a good, solid, useful tool, maybe someone can find a way to compensate/resource @ingydotnet for the maintenance/development.

**Comment by admorgan** [comment]
@bdklahn I am using this in production and it has been pretty stable. There are a few issues lately that I  have had to apply patches to a local fork that worry me (newer version of git breakage) that are taking way to long to implement. Honestly if @ingydotnet  doesn't have time to maintain this I would like a group be assigned rights such that patches can be accepted faster.

**Comment by bdklahn** [comment]
@admorgan, I suppose people could use [your GitHub fork](https://github.com/admorgan/git-subrepo) as more current/authoritative, too, if @ingydotnet doesn't want to (create a group to?) give you push rights. But that, I guess, won't transfer/preserve the Issue records, here, etc.

**Comment by grimmySwe** [comment]
@bdklahn We run this in production, although it's not used by everyone all the time, we have some components handled as subrepos and it works.

@ingydotnet What are your plans ahead? Any chance for a cycle or to to incorporate patches or do you want someone else to step in and drive it for a while?

**Comment by malarinv** [comment]
Ideally git developers should take inspiration from this project and just implement it. Hope they are aware of this project.

**Comment by devinrhode2** [comment]
Looks like there are at least 2 interesting forks/branches that I may chose to experiment with first, instead of the ingydotnet/master: https://github.com/ingydotnet/git-subrepo/network
1. ingydotnet/release-0.4.1: https://github.com/ingydotnet/git-subrepo/compare/release/0.4.1
2. Vikash-Kothary/master: https://github.com/ingydotnet/git-subrepo/compare/master...Vikash-Kothary:master

not sure

**Comment by devinrhode2** [comment]
Actually looks like current master (release 0.4.0) might be better to play with first.

**Comment by admorgan** [comment]
Option 1 is the branch that we plan to release in the near future. The only known issue is that on older versions of git we are seeing some refs not being cleaned and trying to figure out why. Git 2.21 and newer need the changes on 0.4.1.

**Comment by devinrhode2** [comment]
So... I've tried 0.4.1. I originally had sourced the script in my .zshrc, tried doing make install, but keep getting this error. I also tried `brew install make` and then also updated my path to use 
```
git-subrepo ➤ make install                                                                                                                                                         git:release/0.4.1
install -C -d -m 0755 /usr/local/Cellar/git/2.24.0_1/libexec/git-core/
install: the -d and -C options may not be specified together
install -C -m 0755 lib/git-subrepo /usr/local/Cellar/git/2.24.0_1/libexec/git-core/
install -C -d -m 0755 /usr/local/Cellar/git/2.24.0_1/libexec/git-core/git-subrepo.d/
install: the -d and -C options may not be specified together
install -C -m 0755 lib/git-subrepo.d/help-functions.bash lib/git-subrepo.d/bash+.bash /usr/local/Cellar/git/2.24.0_1/libexec/git-core/git-subrepo.d/
install -C -d -m 0755 /usr/local/share/man/man1/
install: the -d and -C options may not be specified together
install -C -m 0644 man/man1/git-subrepo.1 /usr/local/share/man/man1/
git-subrepo ➤ sudo make install                                                                                                                                                    git:release/0.4.1
Password:
install -C -d -m 0755 /usr/local/Cellar/git/2.24.0_1/libexec/git-core/
install: the -d and -C options may not be specified together
install -C -m 0755 lib/git-subrepo /usr/local/Cellar/git/2.24.0_1/libexec/git-core/
install -C -d -m 0755 /usr/local/Cellar/git/2.24.0_1/libexec/git-core/git-subrepo.d/
install: the -d and -C options may not be specified together
install -C -m 0755 lib/git-subrepo.d/help-functions.bash lib/git-subrepo.d/bash+.bash /usr/local/Cellar/git/2.24.0_1/libexec/git-core/git-subrepo.d/
install -C -d -m 0755 /usr/local/share/man/man1/
install: the -d and -C options may not be specified together
install -C -m 0644 man/man1/git-subrepo.1 /usr/local/share/man/man1/
git-subrepo ➤ make --version                                                                                                                                                       git:release/0.4.1
GNU Make 4.2.1
Built for x86_64-apple-darwin18.2.0
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
git-subrepo ➤
```

I also tried using my system's default `make`, but was getting what appeared to be an identical error. (tried normal make install and sudo make install)
```
make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by devinrhode2** [comment]
I can wait for feedback on why the make install isn't working, and will then test using many subrepos on windows with latest git (in git-bash or cygwin) - although I was able to run `git subrepo` and `git subrepo version` in git-bash. (with latest version of git (2.24.1) and windows 10 on "slow" insider track (version 10.0.19037.1)

**Comment by admorgan** [comment]
This is addressed in https://github.com/ingydotnet/git-subrepo/pull/412 which hasn't been applied but is on my list.

**Comment by devinrhode2** [comment]
ok so I can try testing out release/0.4.1

**Comment by devinrhode2** [comment]
ok so I can try testing out release/0.4.1+that patch.. are there any major issues with 0.4.1, such that you would recommend that I first try 0.4.0? maybe 0.4.0 is just more stable version I should use first, and then upgrade to 0.4.1 if I hit any major issues with 0.4.0?

**Comment by admorgan** [comment]
No, I would say that 0.4.1 is more stable than 0.4.0.

**Comment by devinrhode2** [comment]
and would you also recommend latest version of git? any known issues on windows/linux/mac?

**Comment by admorgan** [comment]
The only known issue is the wing love endings for the .gitrepo file my be used on Windows. 

On Dec 14, 2019, Devin Rhode <notifications@github.com> wrote:
>and would you also recommend latest version of git? any known issues on
>windows/linux/mac? 

-- Sent with K-@ Mail - the evolution of emailing.
