### ISSUE TITLE
pull creates .gitrepo files with the wrong line endings on Windows

### ISSUE THREAD

**Issue by PaulVittorino** [ingydotnet/git-subrepo#425]
When pulling a subrepo, the modified `.gitrepo` contains LF instead of CRLF on Windows. The automatically generated commit message is lost since Git errors out before the commit step. The volume on which this occurs is formatted NTFS.

Windows 10 Version 1803 (OS Build 17134.1130)
From Git Bash
```
$ git --version
git version 2.23.0.windows.1
$ git subrepo pull utilities/math
git-subrepo: Command failed: 'git add -f -- utilities/math/.gitrepo'.
fatal: LF would be replaced by CRLF in utilities/math/.gitrepo
```

The relevant section of my `.gitconfig` on Windows.
```
[core]
        whitespace = cr-at-eol,tab-in-indent
        autocrlf = true
        safecrlf = true
        longpaths = true
```
This issue does not occur on Linux. My `.gitconfig` on Linux 
```
[core]
        whitespace = cr-at-eol,tab-in-indent
```

**Comment by admorgan** [comment]
Determined this was a conflict between a .gitattributes file and the SafeCRLF configuration setting. subrepo just happened to trigger the symptom.
