### ISSUE TITLE
readme typo?

### ISSUE THREAD

**Issue by devinrhode2** [ingydotnet/git-subrepo#426]
See: https://github.com/ingydotnet/git-subrepo/commit/810aa75071fcde6f488acd41f896d21f2b48f727#r36389221

**Comment by devinrhode2** [comment]
First link was incorrect. I just edited it to be the correct link: https://github.com/ingydotnet/git-subrepo/commit/810aa75071fcde6f488acd41f896d21f2b48f727#r36389221

**Comment by admorgan** [comment]
Merged into master
