### ISSUE TITLE
Consider setting FILTER_BRANCH_SQUELCH_WARNING=1

### ISSUE THREAD

**Issue by mvz** [ingydotnet/git-subrepo#430]
On newer git versions, the filter-branch command emits a warning message that it's a dangerous operation and you shouldn't use it. It then waits 5 seconds or more for the user to press Ctrl-C and abort. This makes any operation of git-subrepo that uses filter_branch a lot slower.

Setting the environment variable FILTER_BRANCH_SQUELCH_WARNING to 1 makes this go away. With this variable set, tests run in 42 seconds on my machine. Without it, I don't have the patience to see how long it takes.

**Comment by mvz** [comment]
Note: My git version is 2.24.1.

**Comment by admorgan** [comment]
As opposed to setting FILTER_BRANCH_SQUELCH it seems like we should investigate if there is a less "dangerous" way to accomplish our goals.

**Comment by mvz** [comment]
Agreed, but I think that should be a next step.

**Comment by admorgan** [comment]
I investigated and we are using filter branch in a reasonable way. We will need to handle the warning in both the tests and git-subrepo library. This demonstrates how important it is we get a test system with multiple versions of git as soon as possible.
