### ISSUE TITLE
Is there a way to exclude commits from a subrepo push? 

### ISSUE THREAD

**Issue by Scarabytes** [ingydotnet/git-subrepo#432]
I'm looking for a way to add project-specific tweaks to the code in the subrepo, that are not mirrored back to the subrepos original remote. How would I do this? Is there an automated way or would I need to cherry-pick the commits for pushing manually each time?

**Comment by admorgan** [comment]
We have that, but the are only on repositories that do not get pushed back up to the respective repo. Changes from upstream are pulled, but we never push. If you wanted to push some changes up, but not others, you would need to subrepo branch and curate those changes manually.In that case I would also suggest using the rebase option for pulls. It will make it a lot easier.

**Comment by Scarabytes** [comment]
Thanks for the clarification! I got it to work now and will gladly use this instead of git submodules.
