### ISSUE TITLE
Ability to clone to a specific tag?

### ISSUE THREAD

**Issue by pip9ball** [ingydotnet/git-subrepo#439]
Is it possible to pin a subrepo to a specific tag versus a branch?

**Comment by admorgan** [comment]
you can pass a SHA to --branch, but then you will have to supply a different one the next time you want to pull up because you are "following" that SHA

**Comment by pip9ball** [comment]
Thanks for the information.  I wasn't aware --branch accepted SHAs.  If this is the case, I think this will work for what I need.

-Phil
