### ISSUE TITLE
Remote repo subdirectory

### ISSUE THREAD

**Issue by olfway** [ingydotnet/git-subrepo#447]
It seems that currently, it is not possible to add subdirectory of the remote repo as subrepo

Is it planned or possible to implement?
This will allow to add just one module from some big monorepo

**Comment by admorgan** [comment]
I am afraid I don't understand what you are trying to do. Can you post the command you attempted and their result?

**Comment by olfway** [comment]
Sorry, I'll try to explain with example

Let's say I have two repos:

```
RepoA:
  SubDirA1
  SubDirA2

RepoB:
  SubDirB1
```

I want this:
```
RepoB:
  SubDirA1
  SubDirB1
```

**Comment by admorgan** [comment]
I don't understand why this would be an issue. What error are you getting?

**Comment by olfway** [comment]
How can I do this?

I can do
```
cd RepoB
git subrepo clone RepoA
```
and then I guess I will have
```
RepoB:
  RepoA
    SubDirA1
    SubDirA2
  SubDirB1
```

and I need only one directory from RepoA

**Comment by admorgan** [comment]
Ok, I think I may be understanding what you are looking for. subrepo does not support partial repos like svn extern does.
