### ISSUE TITLE
git subrepo clean no longer working in 0.4.1

### ISSUE THREAD

**Issue by rdzman** [ingydotnet/git-subrepo#448]
I have two projects with their own repos (call them A and B), where B is a subrepo of A. I normally do all my commits for B in B's main repo, then from within A I do `git subrepo pull B`, followed by `git subrepo clean B`. The latter always got rid of the `subrepo/B` branch.

However, today I did the same thing after updating from git-subrepo 0.4.0 to 0.4.1 and the `subrepo/B` branch is still there.

Thinking it might be related to a0c967d, I tried `git show-ref` and it does not show any lines with `refs/subrepo/B`, but the directory `refs/subrepo/B` is still there.

Is this a bug?

**Comment by rdzman** [comment]
I should have mentioned that this is on macOS Catalina 10.15.3, with the default zsh as my shell and bash 5.0.6 installed in /opt/local/bin by MacPorts.

**Comment by admorgan** [comment]
This is a bug. Of course the real question is, is it a bug in subrepo or git. Now to find out why isn't the ref showing up in git show-ref.

**Comment by rdzman** [comment]
If you can't reproduce it, let me know if there's something you'd like me to try on my end to track it down.

**Comment by admorgan** [comment]
I probably won't be able to look at it till some time tomorrow. I will let you know what I discover. I know that we have a test in our CI to check for this, but I don't know what version of git our CI is using off the top of my head.

**Comment by rdzman** [comment]
Any news on this yet?

**Comment by rdzman** [comment]
This does seem to have been fixed by #455.
