### ISSUE TITLE
How do I push to a bare repo?

### ISSUE THREAD

**Issue by FunMiles** [ingydotnet/git-subrepo#453]
I've successfully used git subrepo to pull in an existing source code into a subdirectory.
I am now trying for the third time to initiate a git subrepo locally and push it to a bare repository.
Every time I've tried it, it has unfortunately failed.
Would it be possible to get a working example along the line of what I tried?

Here is what I tried the last time:

On the remote server:

    mkdir MyRepo
    cd MyRepo
    git init --bare

On the local:

    git subrepo init DirForMyRepo -r git@remote/MyRepo
    git subrepo branch  DirForMyRepo
    git subrepo push DirForMyRepo -b release/V1

The last command fails with:

> git-subrepo: Fetch for push failed: fatal: couldn't find remote ref release/V1
fatal: the remote end hung up unexpectedly

Could someone give me a cookbook recipe on how to successfully do that?

**Comment by admorgan** [comment]
I don't know what your remote provider is, but a lot of them don't really like creating a branch on an empty repo. I perform the same operations on my local box and everything works.

Why didn't you add the -b release/V1 to the init instead of the push?

**Comment by admorgan** [comment]
Sorry I missed something, why did you git subrepo branch? It is completely uncessary.

**Comment by FunMiles** [comment]
The server is a local machine. So no issue of permission or such.
I tried without the git subrepo branch as well. To no avail.

**Comment by admorgan** [comment]
I am sorry, like I said, I was able to successfully perform the described task. What system and version of git and subrepo are you using?

**Comment by FunMiles** [comment]
git version 2.24.0 on client and 2.24.1 on server.
subrepo version 0.4.0

Is there a way to get s verbose log of what goes on?

**Comment by admorgan** [comment]
-v (verbose command execution)
--debug (shows git commands under the hood)
--DEBUG (extremely noisy, but most verbose output)

**Comment by admorgan** [comment]
I would also use the release/0.4.2 branch

**Comment by FunMiles** [comment]
@admorgan actually, after I upgraded bash (to bash 5.0.15 using brew), it works.
Thanks, I do appreciate the help. If you hadn't asked for the version I would not have checked and try to upgrade.

**Comment by admorgan** [comment]
Great to hear it!
