### ISSUE TITLE
git-subrepo command requires that 'Bash 4+' 

### ISSUE THREAD

**Issue by warbieandyama** [ingydotnet/git-subrepo#463]
Hi there, can someone help to look into this issue? I am on mac OS Catalina 10.15.4
Tried to install through zsh but it didn't work. Therefore I reinstall it in bash but still seeing error messages as following:

> The git-subrepo command requires that 'Bash 4+' is installed.
It doesn't need to be your shell, but it must be in your PATH.
You appear to be on macOS.
Try: 'brew install bash'.
This will not change your user shell, it just installs 'Bash 5.x'.

I tried with the second method mentioned in the installation part by setting the paths via:

> export GIT_SUBREPO_ROOT="/path/to/git-subrepo"
export PATH="/path/to/git-subrepo/lib:$PATH"
export MANPATH="/path/to/git-subrepo/man:$MANPATH"

then I am seeing something like the following:
> /Library/Developer/CommandLineTools/usr/libexec/git-core/git-subrepo: line 25: /Library/Developer/CommandLineTools/usr/libexec/git-core/../ext/bashplus/lib/bash+.bash: No such file or directory

The error message persists after brew install bash. 
Please let me know what else information do I have to provide to help resolving this.

**Comment by mia-riezebos** [comment]
which part of your path wasn't specified? running into this issue even though bash is installed, and on my path...
