### ISSUE TITLE
Support for zsh instead of bash?

### ISSUE THREAD

**Issue by 1duo** [ingydotnet/git-subrepo#484]
Hi, got this error on macOS:

```
The git-subrepo command requires that 'Bash 4+' is installed.
It doesn't need to be your shell, but it must be in your PATH.
You appear to be on macOS.
Try: 'brew install bash'.
This will not change your user shell, it just installs 'Bash 5.x'.
```

Since macOS now running zsh by default, is there any plan to support for zsh?

**Comment by admorgan** [comment]
I don't use zsh, but I know that we have zsh completion. I was under the impression that it was already present. I also don't have access to a Mac so I have no way to work on this. I am happy to accept patches though.

**Comment by admorgan** [comment]
See https://github.com/ingydotnet/git-subrepo#in-zsh
