### ISSUE TITLE
Where I can find full list of subrepo internally stored data?

### ISSUE THREAD

**Issue by hex-profile** [ingydotnet/git-subrepo#486]
It's in .gitrepo file but also it keeps a lot of refs, right?

What can be deleted without breaking functionality?

May I combine subrepo commits with my own ones and edit a commit message without breaking operations in future? 

(For example, subtree stores important information in a commit message.)

I see it stores a hash in commit messages, is it safe to delete it?

**Comment by admorgan** [comment]
All subrepo internally stored data is in the .gitrepo file, no data is store anywhere else.

You can modify the commit message in any way you desire, subrepo supports the -m command internally.

While you can mix your own edits and subrepo commands it is not advised. Subrepo works by replaying commits on a worktree of the parent repo and it can get confusing when mixing things. I have successfully done it, just be aware of the difficulty it could create in the future when used without care.

**Comment by hex-profile** [comment]
Thank you very much!

I constantly break subrepo function, but it's probably because I tried to combine commits and new commit has a different hash, so probably subrepo just can't find right hash.

I see in .gitrepo:

> 	commit = 3a46004a238ca318594f9882eb49bc385dcad83a
> 	parent = bcfffecfeda2d2feefa2bb645319deed11d2da31

It looks like one is from the outer repo and the other is from the sub repo. Probably I shoudn't break these hashes.

**Comment by admorgan** [comment]
That is correct. It is the most fragile part of subrepo. I wish I knew of a way to integrate subrepo into rebase to handle this situation. I have a commit hook to verify that the hash is still valid in the history.
