### ISSUE TITLE
stale worktree prevents push of new commits

### ISSUE THREAD

**Issue by DanielBauten** [ingydotnet/git-subrepo#496]
# Problem

The command `git subrepo push <subrepo>` leads to an unexpected message

> Subrepo '\<subrepo\>' has no new commits to push.

if there are new commits present and there is also a stale, outdated worktree for the branch `subrepo/<subrepo>`.

See issues #326 and #352. The described condition can be caused e.g. as described in #347.

# Primary Cause

In case `git subrepo push <subrepo>` has indeed no new commits to push, the therefore created branch and worktree are not deleted by the subsequent [call of git:delete-branch](https://github.com/ingydotnet/git-subrepo/blob/a04d8c2e55c31931d66b5c92ef6d4fe4c59e3226/lib/git-subrepo#L666) since execution of `subrepo:push()` ends prematurely: https://github.com/ingydotnet/git-subrepo/blob/a04d8c2e55c31931d66b5c92ef6d4fe4c59e3226/lib/git-subrepo#L643

A subsequent call of `git subrepo push <subrepo>` then fails as described above.

# Secondary Cause

In `subrepo:push()`, a cleanup is already intended with a [call of git:delete-branch](https://github.com/ingydotnet/git-subrepo/blob/a04d8c2e55c31931d66b5c92ef6d4fe4c59e3226/lib/git-subrepo#L603). But since the global variable `worktree` is unset at this time, a stale worktree (caused by e.g. _Primary Cause_) is _not_ removed. Thus, the git command `git branch -D "subrepo/<subrepo>"` fails of course.

The subsequent call of `subrepo:branch` therefore returns without creating an updated history of the subrepo branch. As a result, the new commits are not included in this branch, so there are no known changes to the upstream repository.

# Solution

**Primary cause** would be fixed by a mandatory call of `git:delete-branch` before exiting `subrepo:push()` in every case. Note: This would also fix issue #347.

**Secondary cause** would be fixed by an early determination of the expected worktree path in `subrepo:push()`.

**Comment by Lucki** [comment]
I've stumbled across this issue after I had to perform a manual merge which left the worktree behind:

<details>
<summary>Details</summary>

https://github.com/ingydotnet/git-subrepo/blob/2f6859642ae9104a9699021218bf607598f5a0ea/lib/git-subrepo#L1697-L1756

</details>

I was able to fix this by running `git worktree remove /path/to/.git/tmp/subrepo/name` after which new commits were recognized and happily pushed to the subrepo.

**Comment by admorgan** [comment]
Fixed in release 0.4.6
