### ISSUE TITLE
Q: referring to a tag or refs (in general) when using git subrepo

### ISSUE THREAD

**Issue by ig0rsky** [ingydotnet/git-subrepo#507]
Hey 👋 , 

Just wanted to quickly ask a few questions about the usage of git subrepo, especially if there are any plans to change the behaviour of the -b flag so that one can use any ref with it?

I tried this and it seems to be working: 

git subrepo clone --method rebase <remote_repo> <dir> -b tags/<some_tag>-0.0.1

then I tried to pull like this: 

git subrepo pull --branch=tags/<some_tag>-0.0.2 <dir>

This also worked fine. The branch was updated and the commit digest was also correctly pointing to tag-0.0.2

Finally, I wanted to test if I could go back in repository history by force pulling the previous tag and then rebase my local commit on top of it.

git subrepo pull --branch=tags/<some_tag>-0.0.1 <dir>

I got the following error: 

git-subrepo: Local repository does not contain <digest of tag-0.0.2> . Try to 'git subrepo fetch <dir>' or add the '-F' flag to always fetch the latest content.

Does this mean that the reference to the remote of the subrepo must always go forward in git history? Could you explain the observed behaviour here a little bit? 

Thank you for maintaining git-subrepo. ❤️

**Comment by admorgan** [comment]
That error is unexpected unless <some_tag>-0.0.1 is not an ancestor of <some_tag>-0.0.2. I have rolled back before, but it can get pretty hairy. Usually if I have to go backward I prefer to use -f, but that will discard your local changes.

**Comment by ig0rsky** [comment]
@admorgan thank you for the insight, the 0.0.1 is an ancestor of 0.0.2. Just for reference, this is the repo I'm working with: https://github.com/mvisonneau/helm-charts. 

The scenario I imagined is this:
1- I pull from a tag from the upstream. I'm not managing the upstream repo myself.
2- Roll my commits on top of the tag I just pulled. This is usually necessary because helm repository will rarely work 'just fine' out of the box. Most of the time you'll have to tweak something.
3- Every once in a while, update the chart by pulling a newer tag. If for whatever reason this turns out to be a mistake, roll back to the previous tag and rebase my local commits on top again. 

Helm charts repositories are usually mono repos, and so is ours. We have about 50 charts in ours, with no easy way to maintain all of them. There's quite a few that are just copies of upstream charts from github. I tried submodules, they don't work because we don't have direct access to github from where these things are running, also don't really like how difficult they are to correctly operate. Then I tried subtrees; they're mostly okay, but they have their disadvantages as well, mainly not knowing what is a subtree and what isn't just by looking at the repo.

I guess this would be safer if I forked the upstream repo in step 1, and subrepo'ed my fork.

**Comment by jeff-hykin** [comment]
Encase this helps anyone else (took me forever to figure out) here's how I cloned a tag instead of just master

```shell
url="https://github.com/carla-simulator/carla"
tag="0.9.12"
path="./modules/carla"

git subrepo clone --method rebase "$url" "$path" -b tags/"$tag"
```

The other methods didn't work for me
```shell
# attempt 1 (and I cleared out the subrepo each time)
git subrepo clone https://github.com/carla-simulator/carla ./modules/carla
git subrepo pull --branch=tags/0.9.12 ./modules/carla

# attempt 2
git subrepo clone https://github.com/carla-simulator/carla ./modules/carla
git subrepo pull --branch=d23f3dc1340e47265eeea2b1b33b2d3a2d6d4f42 ./modules/carla

# attempt 3
git subrepo clone --method rebase https://github.com/carla-simulator/carla ./modules/carla
git subrepo pull --branch=tags/0.9.12 ./modules/carla
```

**Comment by admorgan** [comment]
That is correct, you can refer to a tag as a branch, but remember you will not be able to push as it is a static position. I use this a lot in projects where I do not expect to have to push upstream. When you pull you will have to specify another branch or tag you wish to move to as the tag will never change.
