### ISSUE TITLE
Readme says git version > 2.7 is needed, but `ls-remote --symref` needs > 2.8

### ISSUE THREAD

**Issue by kit1980** [ingydotnet/git-subrepo#513]
With git version 2.7.4 I get "Command failed: 'git ls-remote --symref ...' " error, because `git ls-remote` doesn't have `--symref`.

Is it possible to make it work with git 2.7? If not, maybe update the Readme?

**Comment by admorgan** [comment]
I will update the ReadMe.

**Comment by ronaldocpontes** [comment]
I am having the same problem with the latest git for windows version 2.30.0.

Is there a recommended git version for windows?

```
> git subrepo clone ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/...
git-subrepo: Problem finding remote default head branch.

>  git --version
git version 2.30.0.windows.1
```

**Comment by admorgan** [comment]
The git version for windows is the same as for all other system. If you are seeing this with 2.30.0.windows.1 then it is a bug on our side.

**Comment by ronaldocpontes** [comment]
Hi @admorgan 

This is strange since all subrepo commands apart from "clone" are working fine on windows. As a workaround I could successfully clone the subrepos on my Mac and pull them from Windows.

Any directions on how to fix the problem?

**Comment by admorgan** [comment]
It is strange. I won't have a chance to investigate until the evening of Jan 14th. I will let you know what I find then.

**Comment by ronaldocpontes** [comment]
Great, thanks!
