### ISSUE TITLE
Failure in repo with 0 commits: "You can't clone into an empty repository"

### ISSUE THREAD

**Issue by ComFreek** [ingydotnet/git-subrepo#515]
## How to reproduce

1. `mkdir dir && cd dir`
2. `git init .`
3. `git subrepo clone <some remote> subrepo` outputs
  
   > git-subrepo: You can't clone into an empty repository

Running `touch dummy.txt && git add --all && git commit -m "dummy commit"` before step 3 fixed it for me.

## Expected

The error message should state more clearly that one needs at least one commit.

**Comment by admorgan** [comment]
I don't think that there is a significant difference between "not an empty repository" and "at least one commit". The error message as it is now is consistent with messages from git with similar restrictions. If you feel really strong about this please post the error message as you believe would be most descriptive.
