### ISSUE TITLE
Is there a way to always reference the latest changes of a sub-repo

### ISSUE THREAD

**Issue by digital-h** [ingydotnet/git-subrepo#516]
Hi,

I'm currently evaluating git-subrepo for my scenario and it looks quite promising.
But I couldn't find anything in the documentation, which really helps me out with the following requirement.
As I would like to include one repository as subrepo in a lot of other projects I'm afraid to run into a maintenance-hell and have to run a `git subrepo pull` everywhere for every change. What I would like to see is, that all my repositories always reference to the latest commit of my sub-repo without having to do any manual action.
I came over a message saying "Try to 'git subrepo fetch myExternalCode' of add the '-F' flag to always fetch the latest content.". Unfortunately the -F flag does not work with `git subrepo fetch` and I couldn't find any documentation for it. Would this be my way out if I get this to work or is there a better way?

Thanks for your help!

**Comment by admorgan** [comment]
I am a little confused by what you are asking for. I read this to say that you wish for subrepo to automatically do a pull to get the newest code in the remote repository. While you could create a hook to do this for you, every pull creates a commit and that sounds like ti would be a new level of hell. It would also likely lead to unstable code.

**Comment by digital-h** [comment]
> I read this to say that you wish for subrepo to automatically do a pull to get the newest code in the remote repository

Yes you got me right. But I was hoping this can be done by sub-repo without having to add something new.
The unstability would be okay for me as I consider it the same way unstable as I do while referencing a Docker or Gradle to "latest".
But in my scenario having to update/maintain a lot of repositories would result in more hell, than the risk of having eventually an unstable master-branch.

**Comment by admorgan** [comment]
I am going to be honest I can't even fathom how I would implement this in a sane way. I still think your best option would be to use git hooks to accomplish your goal, but if you want to put together a bit of a design doc I will consider it.

**Comment by digital-h** [comment]
Ok, I understand. However thanks for this exchange. If I have a good idea how to do it I will come back and let you know.
