### ISSUE TITLE
Question: is it possible to clone a lfs repo with subrepo?

### ISSUE THREAD

**Issue by johnneren** [ingydotnet/git-subrepo#518]
Hi.

I would like to use subrepo to manage dependencies for a project which requires 3 remote repositories which are all running with lfs.

But does this work with subrepo? because i cannot get it to work.

As a demo i tried creating a test repository in devops with something like this:
```
git init external_repo
cd external_repo
git lfs install
git lfs track *.exe
<add working exe file>
git commit everything
git tag v1.0
git push origin -all
git push origin tag
```

Then I created another test repository locally with:
```
git init main_repo
cd main_repo
git lfs install
git lfs track *.exe
git commit .gitattribute
```

If I do a `git clone <https remote devops url> external_repo_clone -b v1.0` I get the tag cloned to the external_repo_clone folder and everything works. LFS does a fetch of the exe file.

If I do a `git subrepo clone <https remote devops url> external_repo_subrepo -b v1.0` the LFS fetch fails on:
_Error downloading object: external_repo_subrepo/Tool.exe (c905c52): Smudge error: Error downloading external_repo_subrepo/Tool.exe (c905c529cc2bc7918dbb6e4c63dbec4c52d9e8abdb22988221f24fddea4875e8): batch request: missing protocol: ""_

Does subrepo not support clone of lfs or am I missing something?

Tested with version 0.4.3 and a 0.4.2-LFS (a open pull request I decided to try out)

Any feedback would be appreciated :)

**Comment by admorgan** [comment]
See #152
