### ISSUE TITLE
Multiple git subrepo pull commands lead to merge conflict in unrelated file

### ISSUE THREAD

**Issue by falken42** [ingydotnet/git-subrepo#522]
First of all, thank you for git subrepo!  We've been using it for a few years already and it's helped not only save us time but help keep our repos nice and tidy.

I've noticed that while using subrepo to pull changes, subrepo occasionally throws merge conflicts on unrelated files which have not been modified by us.  Normally I just patch the changes manually and commit, but I've always considered it odd since it should be automatic.  I decided to look into this today, and put together a short repro script which exhibits this issue:

```
#!/bin/bash

# create/init a temporary git repo to perform work in
rm -rf tmp && mkdir tmp && cd tmp && git init .
echo "test" > test.txt
git add test.txt && git commit -m "initial commit"

# clone libssh2-1.8.0
git subrepo clone git@github.com:libssh2/libssh2.git libssh2 -b libssh2-1.8.0

# edit a file which hasn't changed since libssh2-0.15, add and commit
(echo "# hello" && cat libssh2/m4/autobuild.m4) > x && mv x libssh2/m4/autobuild.m4
git add libssh2/m4/autobuild.m4 && git commit -m "say hello"

# pull/merge libssh2-1.8.1
git subrepo pull libssh2 -b libssh2-1.8.1

# attempt to pull/merge libssh2-1.8.2 (fails)
git subrepo pull libssh2 -b libssh2-1.8.2
```
(This script is also available at: https://github.com/falken42/git-subrepo-merge-bug )

After successfully pulling the changes for `libssh2-1.8.1`, attempting to pull the next set of changes for `libssh2-1.8.2` results in the following failure:

```
...
Subrepo 'libssh2' pulled from 'git@github.com:libssh2/libssh2.git' (libssh2-1.8.1).
The "git merge" command failed:

  Auto-merging src/userauth.c
  Auto-merging RELEASE-NOTES
  CONFLICT (content): Merge conflict in RELEASE-NOTES
  Automatic merge failed; fix conflicts and then commit the result.
```

As I mentioned above, this seems odd since the `RELEASE-NOTES` file was not modifed by the test script.  I'm currently not seeing why git merge couldn't automatically merge the changes for only that one file between `libssh2-1.8.1` and `libssh2-1.8.2` while it was able to do it for `src/userauth.c`.

I've also noticed that either:
1. Not modifying the `m4/autobuild.m4` file (not committing any changes), or
2. Attempting to `pull libssh2 -b libssh2-1.8.2` without the previous `pull libssh2 -b libssh2-1.8.1`

will result in a successful automatic merge.

If there's any further information needed, please let me know!  While it's not a major issue by any means, I'd be happy to help get this nuisance fixed.

**Comment by admorgan** [comment]
The problem is that you are trying to change branches that are not ancestors of each other. If you look at the history, 1.8.0 has a common history with all branches, 1.8.1 Has 4 patches that are on it's own branch, but only 2 of them reside on the 1.8.2 branch, and those 4 patch nor the 4 addition patches on the 1.8.2 branch are on the 1.9.0 branch.

Git doesn't know how to traverse these dead ends when attempting a merge and therefore asked you for help. Even github doesn't show a consistent history for the RELEASE-NOTES file https://github.com/libssh2/libssh2/commits/master/RELEASE-NOTES.

The reason you didn't see this as an issue if you don't modify the m4/autobuild.m4 file is that git just fast forwards to the new position, if you modify a file then it has to replay the subsequent patches on top of it.

**Comment by falken42** [comment]
Ah you're totally right, I didn't even notice that until I examined libssh2's branch graph in more detail just now.  There is indeed some funkyness going on starting from commit `6394c0d`.

Redoing the script so it skips over those problematic branches (ensuring the tags have the same common ancestor):
```
# clone libssh2-1.7.0
git subrepo clone git@github.com:libssh2/libssh2.git libssh2 -b libssh2-1.7.0

# edit a file which hasn't changed since libssh2-0.15, add and commit
(echo "# hello" && cat libssh2/m4/autobuild.m4) > x && mv x libssh2/m4/autobuild.m4
git add libssh2/m4/autobuild.m4 && git commit -m "say hello"

# pull/merge libssh2-1.8.0
git subrepo pull libssh2 -b libssh2-1.8.0

# pull/merge libssh2-1.9.0
git subrepo pull libssh2 -b libssh2-1.9.0
```
...works just fine!

Thanks for pointing that out, I'll close this issue for now.
