### ISSUE TITLE
Wrong tracking branch when re-cloning

### ISSUE THREAD

**Issue by SDesch** [ingydotnet/git-subrepo#533]
Assume I have a repo `foo` that I want to clone into `bar/copy`. Let's say `foo` has two tagged commits `v1` and `v2`.

When I first clone `v1` using `git subrepo clone --branch v1 copy` and then later `git subrepo clone --branch v2  --force copy` and I check `git subrepo status` it tells me that `Tracking Branch` is `v1`. Is this intentional? I (maybe naively) assumed `clone --force` would have the same effect as me manually deleting `copy` and then doing a regular `clone` in which case `Tracking Branch` correctly says `v2`. 

**Side note:**
When I use `git subrepo pull --force --branch v2 copy` everything seems to work. Can anyone fill me in what the differences between `clone --force` and `pull --force` are when used with branches?

**Comment by jrosdahl** [comment]
Related: #388

**Comment by admorgan** [comment]
Nope, that is not intentional. More specifically I do this all the time with the correct results so it is time to pull out the debugging hat.

Specifically git subrepo pull --force internally actually calls git subrepo clone see https://github.com/ingydotnet/git-subrepo/blob/2f6859642ae9104a9699021218bf607598f5a0ea/lib/git-subrepo#L531

Standard debug questions:
git subrepo version:
OS:
shell:
git version:

Do you have a public repo that demonstrates this?

**Comment by SDesch** [comment]
It appears some problems get solved by doing nothing ... I setup a new dummy repo this morning so that I could share it here and all of a sudden everything works as expected (both in the new dummy repo and in the real repo). For reference

git subrepo version: 0.4.3
OS: macOS 11.2.3
shell: zsh
git version: 2.24.2

Maybe something in my shell I used yesterday got messed up and opening up a new shell this morning "fixed" the issue. 
--- 

> Specifically git subrepo pull --force internally actually calls git subrepo clone

So `subrepo pull --force` is basically a shortcut or is there any other difference? My usecase for `git subrepo` is managing generic dockerized applications i.e. there is `foo` which is the source code plus dockerfile and project might then clone `foo` (and possibly make some experimental local changes), add some `deployment.yaml`, build the thing and deploy it. Is using tags on `foo` and then using `git subrepo pull --branch someTag --force` the way to do this?

**Comment by admorgan** [comment]
It is a shortcut, but it is my favorite shortcut because it most accurately describes what your intent is. Yes `git subrepo pull --branch someTag --force` is the correct way to handle the situation you described.

If this happens again please reopen this issue.
