### ISSUE TITLE
git subrepo status doesn't show subrepos that have a common prefix

### ISSUE THREAD

**Issue by cciocov** [ingydotnet/git-subrepo#534]
If you have 2 subrepos named "aaa" and "aa", running "git subrepo status" would only show the "aa" subrepo and omit "aaa".

**Comment by admorgan** [comment]
Good catch. I created a test and am able to reproduce your issue.

**Comment by admorgan** [comment]
Good news is that you can do operations on the aaa repo, but it is still a bug that has been hiding since the beginning.

**Comment by ilCatania** [comment]
additionally, any operation with the --all flag will skip all the subrepos that share the same prefix as the name of an existing subrepo. For example, keeping in line with this issues' original example, doing `git subrepo pull --all` will pull `aa` but not `aaa`. It still works if you pull `aaa` explicitly though.

**Comment by admorgan** [comment]
What version are you using? There hasn't been a release for w while, but PR #536 addressed these issues for me. They are on the release/0.4.5 branch

**Comment by admorgan** [comment]
Nevermind, just looked and it is on my local release/0.4.5 branch, but is still pointing to the wrong branch on the actual PR. I will rebase it and push it myself.
