### ISSUE TITLE
.rc script inside .bash_profile throws filepath error when Bash is opened from other directories

### ISSUE THREAD

**Issue by athreyr** [ingydotnet/git-subrepo#540]
I use Git for Windows on Windows 10.

I had cloned git-subrepo to `C:\Program Files\Git\usr\bin\git-subrepo`, and added the line `source 'C:/Program Files/Git/usr/bin/git-subrepo/.rc'` to my `C:\Users\<usr>\.bash_profile`.

When I go to my project folder `my/project`, right-click, and choose `Git Bash here`, the terminal opens and shows the error: `bash: cd: my/project/C:/Program Files/Git/usr/bin/git-subrepo: No such file or directory`.

I have managed to resolve it by modifying the line that I added to `.bash_profile` file as:
````
old_dir="`pwd`";
cd 'C:/Program Files/Git'
source '/usr/bin/git-subrepo/.rc'
cd "$old_dir"
````

I'm opening this as a new issue because I couldn't find other issues related to this, possibly because people usually don't open bash _after_ navigating to another folder.

**Comment by admorgan** [comment]
Git Bash wants the paths in the .bash_profile to be in unix style. I should have been "/c/Program Files/Git/usr/bin/git-subrepo/.rc". It has to make assumptions about state when you use the C: nomenclature.

**Comment by athreyr** [comment]
Ah okay. That worked perfectly. Thank you 🤗
