### ISSUE TITLE
What is the last release? 0.4.3 or 0.4.5 ?

### ISSUE THREAD

**Issue by olfway** [ingydotnet/git-subrepo#546]
It seems the last release is 0.4.3 in https://github.com/ingydotnet/git-subrepo/releases

But there is also branches release/0.4.4 and release/0.4.5 exists

**Comment by admorgan** [comment]
0.4.3, Ingydotnet likes to have the master contain the latest release, 0.4.5 is being prepared for release. I believe I will be making on next week as a Christmas present.

**Comment by thecontstruct** [comment]
Any word on 0.4.5? is `release/0.4.5` branch stable enough to use since it's been almost 9 months since this was posted?
