### ISSUE TITLE
path layering/remapping possible?

### ISSUE THREAD

**Issue by Yajo** [ingydotnet/git-subrepo#555]
Hello. Thanks for this great project. 😁

I'm evaluating to use it. In our workflow we'd like to be able to map some specific paths in the main monorepo to some specific paths from the subrepo.

Basically, the thing that https://gilt.readthedocs.io/ does, but with the features of git-subrepo, specifically the easiness to contribute back from the main repo to the subrepo upstream.

Is this supported or achievable somehow with git-subrepo?

**Comment by admorgan** [comment]
subrepo does not work with partial sections of an upstream repository. With git there is a tradeoff between contributing upstream and locality of what is consumed from upstream. git-subrepo falls heavily on the ability to upstream, and therefore will not support your requested feature.
