### ISSUE TITLE
Can't pull from subrepo's remote if main repo has local changes

### ISSUE THREAD

**Issue by evil-shrike** [ingydotnet/git-subrepo#559]
Hi,
I'm a new to the tool but encountered an issue with very a basic task.

I have a repo where I created a subrepo with `git subrepo clone <url> dashboard/runner`.
Now I want to pull changes from the subrepo. But there're uncommited changes in my main repo. Though there are no local changes in the subrepo. But I can't pull!
Is it intended behavior? It seems very limiting.

```
/Users/segy/work/campaign-setup-analyzer$ git status dashboard/runner                           ↑
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
-------------------------------------------------------------------------------------------------
/Users/segy/work/campaign-setup-analyzer$ git subrepo pull dashboard/runner                     ↑
git-subrepo: Can't pull subrepo. Working tree has changes. (/Users/segy/work/campaign-setup-analyzer)
```

**Comment by admorgan** [comment]
The "Working tree has changes." means that it found a dirty repository. You need to commit or stash your changes and try again.

**Comment by evil-shrike** [comment]
I understand that, yes, my repo has changes that haven't been committed yet. But there're no changes in the subrepo, but the tool doesn't allow me to update to latest changes from remote. That seems weird.

**Comment by admorgan** [comment]
subrepo does a lot of work merging the external repo with your local repo. This is not safe with a dirty worktree as the worktree is modified during these operations. As we can't guarantee how your files would survive, it is much safer to have you stash them before running the operation. I am going to disagree with you that this is weird behavior.

An important element to remember about subrepo is you can have a change that effects subrepo(s) and files in the parent repo. This makes operations like this have a level of complexity beyond that of a typical merge.

**Comment by evil-shrike** [comment]
Sorry, I don't get it. What affects what? Changes in main repo affect a subrepo? Or on the contrary? But in anyway I don't see how it can happen. Basically I'm choosing between the usage of subrepo and cloning a repo into a subfolder manually.  And the latter seems much more convenient.

Imagine you have a repo with some kind of queries and a tool that executes them. The tool lives in another repo. So you used subrepo to bring it to you project with queries. And now you can't update the tool while working with queries.

Anyway, I understand it's intended behavior and "by design". Thanks for clarifying.
