### ISSUE TITLE
can we submit this also to the main git project?

### ISSUE THREAD

**Issue by frank-dspeed** [ingydotnet/git-subrepo#564]
The Main git project got a contrib folder there is ongoing work on a git subtree -P folderinRepo/subRepo clone *
command it is in fact the same as this but not so good working and it would help maybe to show people that this exists.

if you do not want to do it i can setup a workflow to auto send patches to git and put that into the contrib folder

**Comment by admorgan** [comment]
I was not aware of the contrib folder. I will investigate it this weekend.

**Comment by frank-dspeed** [comment]
@admorgan but we got git-subtree also in our README so some one was aware of that it is the first in the Benefits section of the README :) but anyways i guess that is blocked by using our own bash framework we can close this for now i am at present refactoring git anyway moving away from Linux Shell.
