### ISSUE TITLE
Git subrepo push leaves worktree

### ISSUE THREAD

**Issue by admorgan** [ingydotnet/git-subrepo#568]
```
$ git subrepo --version
0.4.5
$ git branch
    issue_6
  * main
$ git subrepo push whatever
Subrepo 'whatever' has no new commits to push.
$ git branch
    issue_6
  * main
  + subrepo/whatever
```

This causes future operations to require a clean before they can be run.

**Comment by admorgan** [comment]
Copied from comments left on #391 by @pauleckhardt

**Comment by admorgan** [comment]
An immediate workaround is to run git subrepo clean subrepo/whatever.

**Comment by doak** [comment]
I can't reproduce it. Does the bug still exists?
This even seems to be the corresponding test: 3994d709850fd4d30de118aa55b25db2a1e46966
