### ISSUE TITLE
Please add Github topic "git"

### ISSUE THREAD

**Issue by guettli** [ingydotnet/git-subrepo#571]
Please add the label "git" to this Github project, so that it gets listed here: https://github.com/topics/git

I wish I had found this tool sooner :-)

**Comment by admorgan** [comment]
@ingydotnet I don't have permissions to add a topic to this repo, but I agree that it is a good idea. See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics#adding-topics-to-your-repository on how to accomplish this task.

**Comment by ingydotnet** [comment]
TIL...
Done!
