### ISSUE TITLE
`git subrepo branch` and `git subrepo push` create different branches

### ISSUE THREAD

**Issue by tpwrules** [ingydotnet/git-subrepo#574]
Suppose I've done the following sequence of commands:
1. Create main repo
2. Do stuff in main repo
3. `git subrepo clone --method rebase` 
4. Do more stuff in main repo, some of which affects subrepo
5. Upstream subrepo does stuff
6. `git subrepo pull`
7. `git subrepo clean`
8. Do even more stuff in main repo, some of which affects subrepo

At this point, if I do `git subrepo branch`, the branch contains my changes based on top of the upstream commit in step 3, including the squashed commit created by step 6. But if I instead do (`git subrepo clean` and then) `git subrepo push` then the branch contains my changes based on the upstream as of step 6 and no squashed commit.

I would expect `git subrepo branch` to create the latter branch but It's possible I'm not understanding what the commands are supposed to do.

**Comment by admorgan** [comment]
The behavior is correct. subrepo branch separates your work in code related to the parent from the rest of the repo, but in exactly the same manner it was performed. subrepo push is designed to submit your changes up-stream to the parent repo, and you can't do that in the past and therefore your changes need to be rebased on the top of the parent repo for submital. push literally clones a copy of the parent and then applies your patches.
