### ISSUE TITLE
Question: Subrepo with full history

### ISSUE THREAD

**Issue by jcalfee** [ingydotnet/git-subrepo#586]
Is it possible to preserve history without a squash or merge, just rebase, in both directions (push, pull)?  I noticed that pulling tends to collapse things and I'm already using rebase.  I suppose that you may be limited in what git has in terms of this.  Perhaps my issue is that I have to force pull or it fails.  Or is this not supported?

thank you..

**Comment by admorgan** [comment]
This is not supported in subrepo. If you desire avoiding the squash merge I suggest seeing if subtree is a good fit for you. The failure that is causing forced pull is not related to the squash merge and should be addressed separately.

**Comment by jcalfee** [comment]
I have really dug into the other options more than once.  I keep getting led back to subrepo as the best architecture.  If an issue becomes well known I'm sure someone can publish exactly what causes it esp. that if it takes years to fix (for example) and reduce surprises.  But, yea, I'm REALLY happy to have subrep.  I can appreciate the complex in pulling all this off.  I tend to use unit test in nodejs a lot for stuff like this.
