### ISSUE TITLE
Can't pull-make changes-push - 

### ISSUE THREAD

**Issue by MaurGi** [ingydotnet/git-subrepo#610]
I really don't understand how a normal workflow is supposed to work.

Assuming I just cloned it a subrepo in my ci/_lib folder- 

I want to:
1 - Pull the latest changes from the subrepo remote master
2 - Make some local changes on top
3 - Push to the subrepo remote, possibly in another branch so I can create a PR on the upstream

I am doing:
```sh
$ git subrepo clean --ALL                          
$ git subrepo pull -v ci/_lib --force
```

without even adding any change, if I try to:
```sh
$ git subrepo push --branch=subrepo/ci/_lib ci/_lib
git-subrepo: There are new changes upstream, you need to pull first.
```

well darn, I just pulled...

**Comment by MaurGi** [comment]
mpte: the commit id in the subrepo file is the correct sha of master on the remote subrepo

**Comment by MaurGi** [comment]
anyone can help?
my question is what is the sequence of commands to be able to pull the changes from subrepo remote master, make local changes, then push to another branch on remote so I can do a PR on the subrepo.

**Comment by admorgan** [comment]
```bash
git init .
touch "file1"
git add file1
git commit -m "Add file1"
git subrepo clone git@github.com:youruser/repo lib1
touch lib1/file2
git add lib1/file2
git commit -m "Add file2 to lib1"
git subrepo push -b "file2-in-lib1-branch" lib1
```
