### ISSUE TITLE
Missing remove subrepo command

### ISSUE THREAD

**Issue by PilnyTomas** [ingydotnet/git-subrepo#618]
I could not find any command to remove the subrepo. My target is to get to the original state before adding the subrepo (having the commit history is acceptable and understandable).
The only way is to manually delete the folder, remove it in github and commit+push.
It would be nice if there was `git subrepo remove my_subrepo` which would do this.

**Comment by admorgan** [comment]
I would like some clarification. Are you wanting to remove the code in the subrepo, or are you just wanting to remove the link to the external repository for the directory?

**Comment by admorgan** [comment]
@seanlandsman I see you thumbs up'ed this request. Since I haven't heard from @PilnyTomas can you help me understand how you would use this feature?

**Comment by admorgan** [comment]
I will close this if there isn't a response by August 1st 2024.

**Comment by afcuttin** [comment]
@admorgan, I know this has been closed, but I have the exact same request, and I'm willing to provide the requested feedback if this will be reopened
