### ISSUE TITLE
.gitignore files can mess up certain things

### ISSUE THREAD

**Issue by ingydotnet** [ingydotnet/git-subrepo#62]
The git commands used by subrepo are effected by the current ignores. Need to
find out how to turn that off at times.

**Comment by ingydotnet** [comment]
From my research, disabling gitignore wholesale does not seem to be a
possibility.

Another strategy is to warn or error when we know gitignore is getting in our
way.

**Comment by grimmySwe** [comment]
This might be improved with #150 where we don't reuse directories.

**Comment by grimmySwe** [comment]
#150 has reached master so I close this now.
