### ISSUE TITLE
README: update "Status"

### ISSUE THREAD

**Issue by guettli** [ingydotnet/git-subrepo#621]
README, Status:

> The git-subrepo command has been in use for well over a year and seems to get the job done. Development is still ongoing but mostly just for fixing bugs.

I think this needs an update.

**Comment by admorgan** [comment]
Do you suggest changing it to indicate that it is used in production or something else?

**Comment by guettli** [comment]
I read "over a year" and then in the copyright I saw that now more than ten years have passed!

Of course in the mathematical sense "over a year" is correct, but most humans will think this is less than three years.

**Comment by admorgan** [comment]
@guettli I would appreciate you looking at the PR and let me know if it makes sense to you.

**Comment by admorgan** [comment]
Don't worry about the failing tests, they are a known issue that I am working on actively.
