### ISSUE TITLE
git-subrepo 0.4.8 doesn't work on Windows

### ISSUE THREAD

**Issue by pkrebs-am** [ingydotnet/git-subrepo#627]
After updating to version 0.4.8, git-subrepo shows an error on Windows:
```
$ git subrepo status Common
D:/Development/git-subrepo/lib/git-subrepo.d/bash+.bash: line 1: ../../ext/bashplus/lib/bash+.bash: No such file or directory
```
Same error is shown for GIT 2.39 and GIT 2.45.2.
Version git-subrepo 0.4.7 works well
Is it necessary to do any additional settings?

**Comment by admorgan** [comment]
I found the issue in 7816a571fe46a4f53ba7c767735d4e34a9bd135d. It uses symbolic links to address issues when using `make install`. This doesn't work on Windows and an alternate solutions will have to be found. Thank you for making me aware of this.

**Comment by pkrebs-am** [comment]
Thank you for the quick fix. Btw, tag 0.4.9 does not belong to any branch (master).
