### ISSUE TITLE
`git subrepo init` fails silently if `git config init.defaultbranch` is not set

### ISSUE THREAD

**Issue by cquickstad** [ingydotnet/git-subrepo#631]
When following the instructions at https://github.com/ingydotnet/git-subrepo/wiki/FAQ, the `git subrepo init` step fails silently.  It just quits and no .gitrepo file is created.  I debugged it back to line https://github.com/ingydotnet/git-subrepo/blob/ea108868fe0998c912c411830bfc50dc259cc635/lib/git-subrepo#L215

The `git config init.defaultbranch` was not set for my repo.  The command output was therefore empty.  The `git subrepo init` command failed silently without creating a .gitrepo file.  Adding more verbosity to the `git subrepo init` command also was of very little help.

To get it to work I set `git config init.defaultbranch master`.  After that, `git subrepo init` completed successfully.

I suggest that the script be updated to either assume master is the default branch or to fail with a nice message telling the user to set init.defaultbranch.

**Comment by cquickstad** [comment]
Thanks!

**Comment by admorgan** [comment]
It was a very good bug report, thank you for all the effort.
