### ISSUE TITLE
Untracked files and uncommitted changes block pulls in completely unrelated paths (annoying)

### ISSUE THREAD

**Issue by moritz** [ingydotnet/git-subrepo#67]
It's very annoying that when I write a script that calls `git subrepo pull ...`, I can't run and test it before I commit it. Also I don't see why the presence of untracked files that aren't even in subrepos should prevent a pull or clone.

**Comment by ingydotnet** [comment]
@moritz, a couple thoughts:

1) The pull commit is non-destructive. In other words, pull, test, and if you
don't like it, then revert.

2) The doc lists the steps of a pull:

    git subrepo fetch <subdir>
    git subrepo branch <subdir>
    git rebase subrepo/<subdir>{/upstream,}
    git checkout ORIG_HEAD
    git subrepo commit <subdir>

You can run these by hand, and test where you need to.

2b) Use `git subrepo pull -v -d …` to see the steps for real.

As I told you on IRC, we can address this issue now. I started off dev being
extra cautious, but now things are more stable.

See PR #65. This allows untracked files *in* the subdir. @AndrewSmart, maybe
you can do the work for this issue as well?

**Comment by grimmySwe** [comment]
@moritz Could you please test the latest master and give an update if this is still a problem?

**Comment by ingydotnet** [comment]
I think this is related to #23 

I just tested a `git subrepo pull` with untracked changes in both the top level dir and in the subdir being pulled. Worked fine.

Closing for now.
