### ISSUE TITLE
Can clone a repo as subrepo right after create a new repo

### ISSUE THREAD

**Issue by enzochiau** [ingydotnet/git-subrepo#68]
When I try command like this:

    mkdir test_repo
    cd test_repo
    git init
    git subrepo clone https://github.com/buildinspace/peru

I got error message like this:

    fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'
    fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'

**Comment by ingydotnet** [comment]
@enzochiau, do you have the latest version?

This was reported as #26 and fix a couple days ago by #63.

Let me know. Closing this for now. Reopen if it's still an issue.
