### ISSUE TITLE
Perhaps too smart about subrepos

### ISSUE THREAD

**Issue by kentfredric** [ingydotnet/git-subrepo#7]
Just saw this and puzzled be a bit till I worked out what was happening:
```bash
$ git subrepo status
Subrepo: ./File-ShareDir-ProjectDistDir-0.5.3/maint-travis-ci/

Subrepo: ./maint-travis-ci/

kent@katipo2 ~/perl/File-ShareDir-ProjectDistDir $ 
```

One is a copy of the other, probably not a problem, just surprising is all =).

You could perhaps record the repo-relative path of the clone as some sort of QA check "Hey, this is not something we made".

And it makes me curious what happens when you sub-repo a repo with a subrepo in it =).

**Comment by grimmySwe** [comment]
Nested subrepos are discussed in #82 so I close this issue.
