### ISSUE TITLE
Make a release.

### ISSUE THREAD

**Issue by a1russell** [ingydotnet/git-subrepo#71]
I'd like to make git-subrepo installable via Homebrew and have already created a [git-subrepo pull request in the head-only tap](https://github.com/Homebrew/homebrew-head-only/pull/105). Making a release would allow creation of a true Homebrew formula.

**Comment by a1russell** [comment]
Any feedback about this? Any plans to do so?

**Comment by ingydotnet** [comment]
I like the idea. What do I need to do?

**Comment by ingydotnet** [comment]
Oh. You want me to tag a release?

Done. Pushed tag 0.2.1.

Please close this if the resolves it.

Enjoy, Ingy

**Comment by AlJohri** [comment]
@a1russell It seems the latest release on Homebrew is 0.3.0 which is from December 2015 (https://github.com/ingydotnet/git-subrepo/releases)

@ingydotnet would you mind making a new release on Github?

**Comment by ingydotnet** [comment]
I'll make a 0.3.1 release later today and hopefully get the major new stuff released as 0.4.0 later this week.

**Comment by ingydotnet** [comment]
0.3.1 tagged (released)

https://github.com/ingydotnet/git-subrepo/tree/0.3.1
