### ISSUE TITLE
'local varname="$(' style conflicts with 'set -e'

### ISSUE THREAD

**Issue by adrelanos** [ingydotnet/git-subrepo#72]
That is good, generally a good idea:
```
# Exit on any errors:
set -e
```

Glad that's your view. But if that is your view, then I see an issue with the following:

```
 local sha1="$(git rev-parse --short "${BASH_REMATCH[1]}")"
```

Since you are using `local`, the `set -e` is ineffective. Consider this minimal test script.

```
#!/bin/bash
set -x
set -e
testfunct() {
   local testvar=$(false)
   exit $?
}
testfunct
```

Output:

```
+ set -e
+ testfunct
++ false
+ local testvar=
+ exit 0
```

It needs more space, but I think this would be better:
```
 local sha1
 sha1="$(git rev-parse --short "${BASH_REMATCH[1]}")"
```

I just picked `git rev-parse` as a random example. Applies anywhere. There is no specific reason to believe it could become and issue one day. So why fix it? It cannot be foreseen. I would argue, that's why one sets `set -e`. A situation where for example this could fail is when there are [virtual] hdd issues. I am using VirtualBox and I made the mistake to cause high disk load on the host. A bug in VirtualBox makes the virtual hdd inaccessible. The system starts acting weird then for any disk access, but doesn't totally crash. In such situations, I think it would be wrong to report success, while it failed. To handle such corner cases, an effective `set -e` is useful.

**Comment by ingydotnet** [comment]
Thank you for pointing this out. I've made the fixes, but it uncovered problems
that make the tests fail! :)

I'll push what I have to issue-72 branch.

**Comment by ingydotnet** [comment]
Pushed to branch issue/72

@adrelanos, If you'd like to code review some of my other bash repos, here are
the important ones:

* https://github.com/ingydotnet/git-hub
* https://github.com/ingydotnet/json-bash
* https://github.com/ingydotnet/test-more-bash
* https://github.com/ingydotnet/test-tap-bash
* https://github.com/ingydotnet/bashplus

**Comment by adrelanos** [comment]
Glad you like it!

**Comment by ingydotnet** [comment]
Finally got around to fixing this and the errors it uncovered.
