### ISSUE TITLE
fatal: Invalid revision range

### ISSUE THREAD

**Issue by marcussousa** [ingydotnet/git-subrepo#78]
i've made changes on my subrepo dir, but got this output when i push them. 
git status shows the differences but 'subrepo push' don't...

$ git subrepo push [path/to/subrepo_dir] -v
* Fetch the upstream: '[project_repo]' (master):
  * Fetch '[project_repo]' (master)
  * Get the upstream subrepo HEAD commit.
  * Create ref 'refs/subrepo/path/to/subrepo_dir/fetch'.
* Create subrepo branch 'subrepo-push/path/to/subrepo_dir':
  * Check if the 'subrepo-push/path/to/subrepo_dir' branch already exists.
  * Make sure there is at least one commit after the last pull.
fatal: Invalid revision range 4739a91db94fa6b..HEAD
Subrepo 'path/to/subrepo_dir' has no new commits to push.

**Comment by AndrewSmart** [comment]
Might be related to #69, also #70 may fix it, if you want to try that.

Also, try running the push with `-v -d` to see debug output, so you can trace down the line where things go wrong.

**Comment by grimmySwe** [comment]
@marcussousa Could you test the latest master and see if this is still a problem?

**Comment by ingydotnet** [comment]
Closing this as it is likely fixed.

Please re-open if the problem still exists.
