### ISSUE TITLE
`upgrade` command referenced in documentation but unimplemented

### ISSUE THREAD

**Issue by jawshooah** [ingydotnet/git-subrepo#81]
The docs [reference](https://github.com/ingydotnet/git-subrepo/blob/master/doc/git-subrepo.swim#L338) a `git subrepo upgrade` command that doesn't seem to exist. Was this intended to document future, unimplemented functionality?

**Comment by ingydotnet** [comment]
Good catch. I'll look into it.

**Comment by grimmySwe** [comment]
Handled in #118
