### ISSUE TITLE
Backporting the changes after a merge conflict

### ISSUE THREAD

**Issue by dzzh** [ingydotnet/git-subrepo#86]
I can't figure out how I can propagate my changes back to a host (external) subrepo repository after a merge conflict occurs.

My setup is the following. I have a repository S that is used as a subrepo in repositories A and B. I pull the recent changes from S to A and B and then update one of the subrepo files in both A and B in different ways to introduce a merge conflict. Then, I push subrepo changes introduced in A to S repo. So far so good.

Then, I pull S changes to B subrepo. A merge conflict occurs, as expected, and I get a message suggesting me to resolve the conflicts and do a hand merge. I resolve the conflict I have manually and do ````git add .; git rebase --continue````. Then, I switch back to my working branch and do ````git subrepo commit my-subrepo````, as suggested in the output of pull command. After this, repository S contains a commit from A and my repository B contains a merged commit AB. I would like to push this AB commit to S, but it seems to me there is no way to do so. If I do regular ````git subrepo pull```` and ````git subrepo push````, nothing happens, the repo reports me it's in sync (because commit command updated .gitrepo file). If I do a force push to S instead of ````git subrepo commit```` in B, I face a merge conflict again. 

So, I believe there should be a way to propagate conflct resolution changes from a subrepo to its host repository.

**Comment by dzzh** [comment]
To perform such backporting, the following has to be done.

1. Assume you are in repository B and just did ````git subrepo pull <subrepo>````. You get a merge conflict.
2. Resolve the conflicts.
3. Do ````git add .; git rebase --continue````. After these commands, you'll have a commit you want to backport on top of the subrepo history. You are in ````subrepo/<subrepo>```` branch now. 
4. In this branch do ````git push <remote> HEAD:<branch>````. In my case with subrepo named ````tests```` with ````master```` branch as a working branch this command was looking as ````git push subrepo/tests HEAD:master````.
5. ````git checkout <working branch>````
6. ````git subrepo commit <subrepo>````
7. ````git subrepo pull <subrepo>````

Except for the steps 4 and 7, this is a regular conflict resolution flow suggested in git-subrepo output during a merge conflict. Step 4 does backporting of a conflicting change to a subrepo host repository. Step 7 just updates the reference in ````.gitrepo```` to point to a new tip of a remote branch. 

Is there something that can go wrong here?

The command executed at step 4 can be run manually, but it would be handy to introduce ````git subrepo backport```` command to simplify such backporting.

**Comment by grimmySwe** [comment]
I believe that this issue is solved in the 0.3.0 version.
