### ISSUE TITLE
Colons in file names prevent cloning to git-bash and cygwin

### ISSUE THREAD

**Issue by lgaravaglia** [ingydotnet/git-subrepo#87]
I get the following error when trying to clone the git-subrepo using cygwin or git bash:

$ git clone https://github.com/ingydotnet/git-subrepo ./subrepo
Cloning into './subrepo'...
error: Invalid path 'ext/bashplus/test/source-bash+-:std.t'
error: Invalid path 'ext/test-more-bash/ext/bashplus/test/source-bash+-:std.t'

The file  source-bash+-:std.t does not exist.

**Comment by grimmySwe** [comment]
I tested to clone the git-subrepo just recently in gitbash and it worked without problems. 

Do you have any more information regarding git version? Is this still a problem?

**Comment by ingydotnet** [comment]
Closing this, as it must not be an issue now.
