### ISSUE TITLE
How to merge existing, but partially newer code with code from subrepo?

### ISSUE THREAD

**Issue by ulfw** [ingydotnet/git-subrepo#88]
This is more a how to question, but the problem came up while we were "fighting" with submodules and stree. So this is the problem description:

We have a few projects with a common core, we name it "A".
When starting a new project we copy over the code of "A" to the project and develop the project. (yes, I know, not the best way, we are working an that).
Of course there are changes to the code of "A" also. And these changes are committed only into the repository of the project, but not "A". Some developers are smart and make the same changes again on the repository of "A". So we have the problem, that we have different code changes in "A" and in he project.

We want to use the subrepo concept to update the repository of "A". Its a nice way to develop our projects and our core and merge changes of the core in the projects more often.

But to use it, we have to merge the code initially. Is there a way to merge these changes? 
Maybe I don´t see the wood for the trees?

Or ist this more a  stackoverflow question?

**Comment by AndrewSmart** [comment]
So you have multiple branches of "A". Glad you're looking to do things better.

My advice would be to merge the branches of "A" with a merge tool, like kdiff3 or meld. Not all merge tools can compare & merge directories. Commit the merged result, so you only have one copy of "A" in it's own repo, remove the other copies. Then use subrepo to put "A" wherever it's used.

If you want a history from one of the branches of "A", try out the init/split command implemented in #79 to pull "A" out of one of the projects it was used in. Then merge the other branches of "A" onto that one.  Good luck.

**Comment by grimmySwe** [comment]
@ulfw 
We are testing a new update in branch **issue/98** that might be helpful in this case. Lets say that you have a repo bar and another repo foo where you once have copied the bar repo.

```
bar repo - currently with two files:
bar/bar1
bar/bar2

foo repo with a copy of bar repo with another state:
foo/bar/bar1
foo/bar/foo1
```

If you now init a subrepo for bar in foo
``` 
# cd foo
# git subrepo init bar -r ../bar/.git
Subrepo created from '../bar/.git' (with no remote).
```

Now you can try to perform `git subrepo pull bar`. It will now fetch all commits from the bar repo in to a local branch, then create a local version of the bar directory and compare tree hashes between them. If it finds a common tree hash, it can then perform a regular pull operation and you will have to solve any merge conflicts.

In the case above, it might find that when bar was copied into foo it contained only bar1 and that will be detected as an equal tree. so the result would be:

```
foo/bar/bar1
foo/bar/bar2
foo/bar/foo1
```
And now you can `git subrepo push bar` to make the bar repo look the same.

**Comment by grimmySwe** [comment]
These changes are now on master so please test and see if they help.
