### ISSUE TITLE
Impossible to push if there are several commits that don't contain subrepo changes.

### ISSUE THREAD

**Issue by dzzh** [ingydotnet/git-subrepo#89]
For a host repository A with a subrepo B, if after a subrepo pull there are several commits in A that do not introduce changes to subrepo code, subrepo push will fail with a weird exception. Test and fix will follow.

**Comment by ingydotnet** [comment]
@dzzh, @grimmySwe, is this fixed? If so please close. Cheers.

**Comment by ingydotnet** [comment]
@dzzh, @grimmySwe, also could you review #91, #93, #95, #96

**Comment by grimmySwe** [comment]
I consider this one fixed.
