### ISSUE TITLE
--ours and --theirs for push/pulls

### ISSUE THREAD

**Issue by ml31415** [ingydotnet/git-subrepo#93]
I quite frequently run into the issue, that I know that no external changes have happened for the subrepo, but when I want to push changes from the master repo to the subrepo, the rebase does not work automatically, but instead wants me to manually add all changes again. Though this is probably an issue for itself, having the flags --ours and --theirs as for usual pulls would be incredibly helpful in this situation, just to force the subrepo to look like the master repo for pushes and vice versa.

**Comment by grimmySwe** [comment]
@ml31415 Hi could you test the new branch issue/98 for your cases and see if it solves your problems?

In that branch there is some new logic that will use the `rebase -X theirs` inside to avoid conflicts during the subrepo push step.

**Comment by ml31415** [comment]
Ok, I'll see if it helps.

**Comment by grimmySwe** [comment]
@ml31415 Any news on this?

**Comment by ml31415** [comment]
Hi! Well, actually my workflow changed a bit, so I haven't used it recently to be honest. I'd be fine closing it and reopen, in case I run into other complaints later on!
