### ISSUE TITLE
Rebase is incorrect after branching

### ISSUE THREAD

**Issue by dzzh** [ingydotnet/git-subrepo#96]
When working on #95, I found that when I do `git subrepo pull`, the newly created branch gets rebased incorrectly into `refs/subrepo/<subrepo_name>/fetch`. I have reproduced this in a test, will commit it soon.

In my test I have a subrepo that is called sub. After `git subrepo branch` is invoked, in my subrepo I have two files. The first is called `subrepo` with the first change from subrepo, the first one is called `subrepo-host` and contains changes introduced in my host repositort. 

Before rebasing my branch with these two files, in main subrepo repo I only have subrepo file with two changes from subrepo. 

When rebase command is invoked, I expect that it will complete successfully and will contain the following:
- `subrepo` file with two changes from subrepo repo
- `subrepo-host` file with changes from host repo

Instead I get a conflict. `subrepo-host` looks valid, for subrepo I get this.

```
direct change in sub
+<<<<<<< HEAD
+another direct change in sub
+=======
+>>>>>>> change from host
```

So my second change in `subrepo` file that is only present in subrepo repository conflicts with a change from host that was committed to a different file.

Git 2.4.6, OS X 10.10. 

Maybe it's better to not rebase after `git subrepo branch`, but rather squash all commits into one during  branching and then cherry-pick this single commit onto `refs/subrepo/<subrepo_name>/fetch`? If doing it this way, the previous pull commit should remain intact and contain all the previous history. So the newly created branch would look like

```
hgfedcba squashed changes after the last pull
abcdefgh git subrepo pull (and all preceding subrepo history)
```

**Comment by dzzh** [comment]
I have implemented cherry-picking instead of rebasing and updated .gitrepo to contain separate references to pull parent and push parent. Now the application seem to work fine for my usage scenario. I'm not done with the fix, there are some issues with the code that can cause bugs and/or have to be otherwise improved. Do you think this can be integrated into the mainline after I complete the code and tests? If so, it will require to also write a migration script for the users installing the new version.

**Comment by grimmySwe** [comment]
Test case for this issue is included in suite and it works, so I consider this issue closed.
